### ISSUE TITLE
Batch Update Values for Speed

### ISSUE THREAD

**Issue by stuartlynn** [CartoDB/cartoframes#1]
Explore both Update ; method and the weird version here: http://stackoverflow.com/questions/18797608/update-multiple-rows-in-same-query-using-postgresql

**Comment by andy-esch** [comment]
POSTs are capped at 1MB (or will be in the near future): https://carto.com/docs/faqs/carto-engine-usage-limits. This means that the limit for a query is around 1 million characters.
