### ISSUE TITLE
Upload dataframe with several geometries

### ISSUE THREAD

**Issue by oleurud** [CartoDB/cartoframes#1005]
If a dataframe has several geometries, we use it in a Dataset and call to the upload method, we are saving one as the `the_geom` as `geometry` column and the rest as `text` columns
```
df = pd.DataFrame(
            [['POINT (0 0)', 'POINT (1 1)', 'POINT (2 2)']], columns=['geom', 'the_geom', 'geometry'])
Dataset(df).upload(....)
```

We should detect the geometries and save them in geometry columns

**Comment by oleurud** [comment]
Corner case, very low priority

**Comment by Jesus89** [comment]
This is already done in the new implementation of the upload because now it detects the type of the column for each column.
