### ISSUE TITLE
Size legends, a case study

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#1009]
The values that the ramp is being created off are either 0, 1, or 2. I first tried to create a `size_category_layer` but got an error that my values were not of type category (they are integers). So I went with `size_bins_layer` and got the following legend, where it's unclear to me whether those values are rounded or not:

<img width="1019" alt="Screen Shot 2019-09-19 at 9 00 43 AM" src="https://user-images.githubusercontent.com/1041056/65246183-068b2580-dabc-11e9-8cbf-960f6aa27707.png">

`size_continuous_layer` might be an improvement, but since the values are discrete not continuous I feel like we can guide the user better on the marker sizes and what they mean:
<img width="1073" alt="Screen Shot 2019-09-19 at 8 59 55 AM" src="https://user-images.githubusercontent.com/1041056/65246099-e491a300-dabb-11e9-85ed-544a5aef552c.png">

Data: [car_bike_crash_fairfax_drive.csv.zip](https://github.com/CartoDB/cartoframes/files/3631293/car_bike_crash_fairfax_drive.csv.zip)

cc @makella

**Comment by makella** [comment]
hi @andy-esch! i haven't had a chance to look at your example in detail, but wondering if you tried the option for `breaks` in the `size_bins_layer`? Basically doing manual classification? I know that won't fix the legend issue you bring up, but that way you can set your bins explicitly to the values you want to map and get three breaks for 0,1,2 in addition, you can set 3 symbol sizes in the array as well.

In the `size_contiuous` example, I'm not sure why there are four sizes if there are only three possible values... I would only expect to see three.

**Comment by Jesus89** [comment]
We will cover this with the new legends implementation in the WebSDK cc @VictorVelarde
