### ISSUE TITLE
Dataset().upload() does not work with non-master API keys

### ISSUE THREAD

**Issue by jdgodchaux** [CartoDB/cartoframes#1011]
When using `Dataset().upload()`, I'm able to use my master API key to create and update tables. However, when I create a table in my CARTO dashboard, then create an API key with full access to that table, `Dataset().upload()` throws an `Access denied.` error (see the full error message below. Here is the API key configuration:

<img width="669" alt="Screen Shot 2019-09-19 at 10 22 31 AM" src="https://user-images.githubusercontent.com/631015/65259210-efebcb00-dac9-11e9-883f-882dfc1945d2.png">

**Code snippet that produced the error**
```
from cartoframes.auth import set_default_credentials, Credentials
from cartoframes.data import Dataset
import pandas as pd
import geopandas as gpd

USER_NAME = 'jdgodchaux-carto' #@param {type:"string"}
API_KEY = '4ESdfFKKQvtTPwm5sTV3pA' #@param {type:"string"}

credentials = Credentials(USER_NAME, API_KEY)

food_trucks_df = pd.read_csv('https://data.sfgov.org/resource/rqzj-sfat.csv')
food_trucks_gdf = gpd.GeoDataFrame(food_trucks_df, geometry=gpd.points_from_xy(food_trucks_df.longitude, food_trucks_df.latitude))
# clean dataset
food_trucks_gdf = food_trucks_gdf[food_trucks_gdf.latitude != 0]
food_trucks_gdf = food_trucks_gdf[food_trucks_gdf.longitude != 0]
food_trucks_gdf = food_trucks_gdf[food_trucks_gdf.latitude.notnull()]
food_trucks_gdf = food_trucks_gdf[food_trucks_gdf.longitude.notnull()]

food_truck_dataset = Dataset(food_trucks_gdf)

food_truck_dataset.upload(table_name='food_truck_dataset', if_exists='replace', credentials=credentials)

```

**Relevant error messages**
```
---------------------------------------------------------------------------
ForbiddenErrorException                   Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/carto/sql.py in send(self, url, http_method, json_body, http_header)
    174                                     json=json_body)
--> 175             data_json = self.client.get_response_data(data)
    176         except CartoRateLimitException as e:

9 frames
ForbiddenErrorException: Access denied

During handling of the above exception, another exception occurred:

CartoException                            Traceback (most recent call last)
CartoException: Access denied

During handling of the above exception, another exception occurred:

CartoException                            Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/cartoframes/data/registry/dataframe_dataset.py in _create_table(self, normalized_column_names, with_lnglat)
    105             raise err
    106         except CartoException as err:
--> 107             raise CartoException('Cannot create table: {}.'.format(err))
    108 
    109     def _create_table_query(self, normalized_column_names, with_lnglat=None):

CartoException: Cannot create table: Access denied.
```

**cartoframes version (find it with print(cartoframes.__version__))**
1.0b2

**Python version (e.g., 3.5, 2.7, etc.)
Operation system (Windows, Linux, etc.)**
This is running in a Colab Noebook:
https://colab.research.google.com/drive/1ufJXb9uXLzI5CozJsYGs_VyaiBRVZiSZ#scrollTo=7XC-lyH7Z6EU

**Comment by oleurud** [comment]
Hi @jdgodchaux 

When you call to:
```
food_truck_dataset.upload(table_name='food_truck_dataset', if_exists='replace', credentials=credentials)
```
you are creating a new table `food_truck_dataset`, because with `if_exists='replace'` basically we are droping the table if exists and recreating it based on the dataframe. And for doing that, you will need the master key.

If you use `if_exists='append'` it should work (it will append the dataframe data to an existing table)

**Comment by alrocar** [comment]
There's a new grant for API keys, that allows creating tables in your CARTO account. It's quite recent but it's documented [here](https://carto.com/developers/auth-api/guides/CARTO-Authorization/)

I'm closing this one and since we are doing an effort on documenting how authorization works in CARTOframes, will include that kind of details there.

Thanks for reporting!

**Comment by jdgodchaux** [comment]
Hi @alrocar and @oleurud , thank you for your responses! 

@alrocar you can see above that for the API key I created, I did check the box next to `CREATE` which should give that API key permissions to create a table. If I create an API key with the `CREATE` permission granted (like above), I think I should be able to run `Dataset().upload()` with `if_exists` is set to 'replace`, and it looks like I've done all that above but I'm still getting `Access denied`. I'm reopening this issue because I think there is a bug somewhere, either with the Auth API or in CARTOframes. 

Thank you!

**Comment by alrocar** [comment]
Thanks for reopening @jdgodchaux 

Now I get what's happening.

An API key with `CREATE` permission cannot `DROP` tables which is not the owner (not created with it). This is what's happening in this case.

So, we have different alternatives:

1. Be more clear with the exception + add some documentation about it.
2. React to the `Access Denied` error on `DROP` and do a `TRUNCATE` instead. This has the problem that `if_exists=replace` won't work if the dataframe schema does not match the table schema. Imagine you added a column and want to overwrite the table, it won't work.

@oleurud Thoughts?

**Comment by oleurud** [comment]
Thanks @jdgodchaux. With the `if_exists='replace'` you are dropping and creating the table and as @alrocar said:

> An API key with CREATE permission cannot DROP tables which is not the owner (not created with it). This is what's happening in this case.

So if you create the table with that API key and then do the upload it should work.

In the documentation we are saying:

> CREATE datasets: allows you to create tables in the user schema by using the SQL API, and also modify or delete the tables previously created.

Maybe we could be more explicit about this case adding:

> CREATE datasets: allows you to create tables in the user schema by using the SQL API, and also modify or delete the tables previously created **with it**.

But I think we can not change the message in CARTOframes because we know nothing about the API key used by the user. The `Access denied` could become from an API key with any table permissions. I think it is the correct message. 

And about doing a TRUNCATE, the previous reason works too, but also with an upload usign `if_exists='replace'` the user could want to change a previous table for a new one (new columns structure).

As summary, I think we can only improve the documentation

**Comment by alrocar** [comment]
> So if you create the table with that API key and then do the upload it should work.

Right. This is valid as well for OAuth tokens even if you refresh them.

> But I think we can not change the message in CARTOframes because we know nothing about the API key used by the user. The Access denied could become from an API key with any table permissions. I think it is the correct message.

What I was proposing was having a fallback in the DROP method and try a TRUNCATE when an `Access denied` error occurs, if it fails again, then raise the error. Another option is to have an `if_exists=truncate` and let the user decide.

In any case I've updated the docs, so we can refer users facing that problem to the developer center.

**Comment by jdgodchaux** [comment]
Hi @alrocar, 

Thanks for that explanation. Now I understand what's happening. A few questions came up in my mind though 

> An API key with `CREATE` permission cannot `DROP` tables which is not the owner (not created with it). This is what's happening in this case.

So if I created an API key with `CREATE` permission, ran an `.upload()` on a dataset, then ran another `.upload()` to the same table with `if_exists="replace"`, the API key would have permission to do the `DROP` on that table and `CREATE` a new table, even if the schema has changed?

> 2. React to the `Access Denied` error on `DROP` and do a `TRUNCATE` instead. This has the problem that `if_exists=replace` won't work if the dataframe schema does not match the table schema. Imagine you added a column and want to overwrite the table, it won't work.

I can see how allowing an API key with `CREATE` permission to do a `TRUNCATE`, but only if the schema is identical could cause problems for our customers. They might expect that `if_exists=replace` will always replace the table no matter if the schema changed or not, but they'll understand the explanation that you need the master API key because you are dropping the table and recreating it. Most of my customers will probably just always use the master API key so they don't run into permission problems that they need to debug. 

Thanks!!

**Comment by oleurud** [comment]
> So if I created an API key with CREATE permission, ran an .upload() on a dataset, then ran another .upload() to the same table with if_exists="replace", the API key would have permission to do the DROP on that table and CREATE a new table, even if the schema has changed?

Yes, you would be creating a table, dropping it and creating a new one.

**Comment by jdgodchaux** [comment]
Awesome, thanks Simon!

**Comment by oleurud** [comment]
We have updated the developer center documentation https://carto.com/developers/auth-api/guides/CARTO-Authorization to be more clear about the API key with CREATE permissions.

I think we can close this one, if not, please reopen it
