### ISSUE TITLE
should be cartodb_id a column?

### ISSUE THREAD

**Issue by oleurud** [CartoDB/cartoframes#1015]
### Download 
```
ds = Dataset('your_table')
df = ds.download()
df.head()
```
you get a dataframe with `cartodb_id` as index and not as a column
![image](https://user-images.githubusercontent.com/421145/65322696-d5881f00-dba7-11e9-9627-9b17bc3fba87.png)

### Upload
```
ds2 = Dataset(df)
ds2.upload(table_name='your_table', if_exists="replace")
df.head()
```
![image](https://user-images.githubusercontent.com/421145/65322875-40395a80-dba8-11e9-9926-d6a6ad912658.png)

When a user creates a Dataset from a DataFrame, we are saving the index as a column (if the index has a name and there is no other column with the same name). The idea behind that it is not to lose data.

In my opinion we should unify these 2 different behaviors, so the cartodb_id is always a index and a column, or is a index but no a column.

**Comment by Jesus89** [comment]
@andy-esch what do you think about it?

**Comment by andy-esch** [comment]
I think the better behavior is "cartodb_id is always an index". Honestly, I think it's fine if it's just a normal column and we do nothing fancy with the index (I used to strongly believe the cartodb_id should always be the index, but it's so easy to set/reset indexes in pandas I don't think it's a big deal either way). I don't like the behavior of duplicating the `cartodb_id` column as both a normal column and an index.

**Comment by Jesus89** [comment]
I like the idea of unifying it. Now if there is no `cartodb_id` in the DataFrame, the index is used in the upload, so we can do the same in the download. :tada:

**Comment by andy-esch** [comment]
One big problem of using the dataframe index is that there are different constraints on cartodb_ids and dataframes indexes. DataFrame indexes can be strings, negative numbers, and more. cartodb_ids are natural numbers (ints greater than zero)

**Comment by Jesus89** [comment]
Oh. I think this has not been taken into account cc @oleurud @jgoizueta. Using the DF index as cartodb_id is already implemented.

Do you see a good solution to this?

**Comment by alasarr** [comment]
Duplicated of https://github.com/CartoDB/cartoframes/issues/1231
