### ISSUE TITLE
Discussion: how to symbolize isochrones and isodistances

### ISSUE THREAD

**Issue by makella** [CartoDB/cartoframes#1017]
As discussed in today's meeting, symbolizing returned features will be a blocker for users during CF workflows.

Below I present the problem with currently available "out-of-the-box" methods and propose a couple of ideas for how we can overcome. The solutions will require some work to think about how we provide more suitable styling by default.

In the examples below, I am using a dataset of Whole Foods and Safeway grocery stores in the city of Denver. For each location, I've created walk time polygons at 5,10 and 20 minute intervals.

### Default symbology
By default, the polygons draw from lowest to highest values. In this case, that means that the largest (20 minute) polygon is covering the other two polygons:

<img width="1010" alt="Screen Shot 2019-09-23 at 1 29 16 PM" src="https://user-images.githubusercontent.com/1566273/65456285-36149780-de06-11e9-99bc-ec7f82e08d23.png">

### Helper cartography
If styled with something like our `color_bins_layer` the default still doesn't solve the issue and also aren't suited for mapping these values.
<img width="1023" alt="Screen Shot 2019-09-23 at 2 32 09 PM" src="https://user-images.githubusercontent.com/1566273/65460377-f69e7900-de0e-11e9-8609-878246730933.png">

### Customize color bins
If using this helper, the classification method should change to Equal Intervals and the number of class breaks should reflect the number of data range values. Even with those modifications, we still can't really "see" the result as this has been applied to the fill of the symbol and these are modifications that might not be readily apparent to the user. Also, the legend still isn't what we would expect to see on this kind of map
<img width="1000" alt="Screen Shot 2019-09-23 at 3 10 46 PM" src="https://user-images.githubusercontent.com/1566273/65463076-58151680-de14-11e9-8b3a-30a9d5ab5cb1.png">

### Alternative ideas
- of course the ideal scenario would be to have the polygons ordered from max to min, but since that is a limitation we have, we need to think of other ideas.
- change the default opacity for polygons. This isn't the best path forward because that will have implications for all polygon data that is added. If for example someone has small polygons, they would be really hard to see with such a high level of opacity.
- Return lines. If we returned lines, we would need to create a new helper method and make sure we have a matching legend. Also, we would not be able to add any fill color to the polygons because we will once again run into the same issue of the larger polygon obscuring the smaller ones.
<img width="1023" alt="Screen Shot 2019-09-24 at 8 10 54 AM" src="https://user-images.githubusercontent.com/1566273/65519297-f8198100-dea2-11e9-82b0-061fd2b380b8.png">

- Have a precanned default style that loads with the output. Instead of modifying the opacity of all polygon features, we could think of a way to only add opacity to output isochrone/distance polygons. And in VL terms, use `filter` instead of opacity to have it at the layer level. But if we go back through the styling loop here, we will still run into the same problems outlined above when people begin to apply their own styling
<img width="905" alt="Screen Shot 2019-09-24 at 8 16 15 AM" src="https://user-images.githubusercontent.com/1566273/65519704-9d345980-dea3-11e9-897d-be3098c52971.png">

cc @jgoizueta @cmongut @alasarr

**Comment by makella** [comment]
another thought I had was providing users some recommended cartography accessible inside of the notebook. for example, to see helper parameters, you can access them inside the notebook:
```
from cartoframes.viz import helpers
help(helpers.size_continuous_layer)
```

Similarly, if we had something like `help(isochrones)` we could print out some recommended styling like the line and filter options shown in the previous two maps along with legend recommendations, etc.

**Comment by Jesus89** [comment]
I think having a default helper method for isolines would be really nice!

**Comment by makella** [comment]
@jgoizueta i guess this is irrelevant now with your new approach, right? if so, should we close?

**Comment by jgoizueta** [comment]
Yes, I think we should now advise the users to use the _exclusive_ parameter for visualization.

**Comment by makella** [comment]
ok! i haven't tried it yet, but closing this and if needed, we can reopen to discuss symbolizing. thanks!

**Comment by makella** [comment]
reopening so we can discuss symbology for the current implementation presented by @jgoizueta today.

thinking through the available helper methods and the resulting legends, the one option i see is to use the `color_category_layer` but that means we would need a string attribute for `data_range` the other issue will be that by default, we will return category colors, not sequential ones. This will require that the user, no matter what, change the default colors that we provide and know to put them in a sequential order via buckets.

The other option is to create a new helper for this styling. This would still require a string for `data_range` since none of the numeric legends we have will work in this scenario.

If this is put into the plan, I can spend some time looking at the options. If not, we can wait til next cycle or after sdsc.

**Comment by jgoizueta** [comment]
After having added the `exclusive` option, overlapping is not a problem, and color ramps can be easily added, but the legends are not appropriate:

```python
isochrones = iso.isochrones(dataset, [1200,2400,3600], mode='car', exclusive=True).data
from cartoframes.viz import Map, Layer
from cartoframes.viz.helpers import color_bins_layer
Map([color_bins_layer(isochrones, 'data_range',  method='equal', bins=3), Layer(dataset)])
```

![Screenshot 2019-10-02 at 13 20 29](https://user-images.githubusercontent.com/5909/66040375-8f23b000-e517-11e9-9776-caeec870c641.png)

This is because our data already is in ranges, and we're creating new equal ranges based on the top values of our ranges.

One possible solution is to use a categorical column:

```python
isochrones.dataframe['range'] = isochrones.dataframe.apply(lambda r: '{} to {}'.format(r['lower_data_range'],r['data_range']), axis=1)
from cartoframes.viz.helpers import color_category_layer
Map([color_category_layer(isochrones, 'range', palette='purpor'), Layer(dataset)])
```

![Screenshot 2019-10-02 at 13 23 21](https://user-images.githubusercontent.com/5909/66040470-c5612f80-e517-11e9-9f20-53484ca54aaa.png)

Now legends and hover values are fine. But we must either always add the new text column and waste space or instruct the user how to create it.

**Comment by jgoizueta** [comment]
Another related problem is that users will often need the non-exclusive areas for some computation (e.g. aggregating some data) AND the exclusive areas for map representation. They can compute both and spend twice the credits, but that doesn't sound very nice.

I included a hint in the documentation on how to convert between the two area forms by using these methods:

```python
def inclusive_to_exclusive(inclusive_table_name, exclusive_table_name, if_exists='fail', credentials=None):
    sql = """
        SELECT
            cartodb_id,
            source_id,
            data_range,
            COALESCE(
                LAG(data_range, 1) OVER (PARTITION BY source_id ORDER BY data_range),
                0
            ) AS lower_data_range,
            COALESCE(
                ST_DIFFERENCE(the_geom, LAG(the_geom, 1) OVER (PARTITION BY source_id ORDER BY data_range)),
                the_geom
            ) AS the_geom
        FROM {table_name}
    """.format(table_name=inclusive_table_name)
    Dataset(sql, credentials=credentials).upload(table_name=exclusive_table_name, if_exists=if_exists)

def exclusive_to_inclusive(exclusive_table_name, inclusive_table_name, if_exists='fail', credentials=None):
    sql = """
        SELECT
            cartodb_id,
            source_id,
            data_range,
            ST_UNION(the_geom) OVER (PARTITION BY source_id ORDER BY data_range) AS the_geom
        FROM {table_name}
    """.format(table_name=exclusive_table_name)
    Dataset(sql, credentials=credentials).upload(table_name=inclusive_table_name, if_exists=if_exists)
```

This has the limitation that persistent tables must be used for the areas.

We could provide those methods in the `Isolines` class, but then to avoid confusion/unnecessary complexity we could remove the `exclusive` parameter and tell the user to use these methods [cc/ this is something @Jesus89 has discussed with me]

I'm tempted to do so, but, then we should either keep those methods in their simple form and force the user to save isolines to tables (`table_name=...`) to use them or make more complicated versions of those methods that can handle Dataframes etc. Also, as @Jesus89 has suggested, it'd be nice to save the round trip to the database and be able to do the conversion with Geopandas.

**Comment by alasarr** [comment]
Legend looks good to me 👍 

I will keep the current version as it is and include at the doc this new legend.

I'll create a separated issue for the transformation of the geometries, so we can prioritize it properly.

**Comment by Jesus89** [comment]
@jgoizueta @makella could we close this ticket?

**Comment by jgoizueta** [comment]
Currently we're converting the range values to categories to obtain nice legends:
```
isochrones.dataframe['range_label'] = isochrones.dataframe.apply(lambda r: '%.0f to %.0f min.' % (r['lower_data_range']/60, r['data_range']/60), axis=1)
Map([color_category_layer(isochrones, 'range_label', palette='purpor', title='Isochrone Areas'), Layer(dataset)])
```
![Screenshot 2019-10-21 at 16 47 25](https://user-images.githubusercontent.com/5909/67215872-817c8e80-f422-11e9-9144-69ba24533391.png)

The `apply` to generate the categories/legend texts is a little ugly, but I think this is good enough for now, if @makella agrees we can close this.

**Comment by makella** [comment]
@jgoizueta so can we talk about the legend? that is different than the other ones we have and i thought that we weren't going to use the word `to` because it is english centric? i mean if we can use `to` there are other places we should think about doing that... also, why is it capitalized? anyway, would be good to do a review of it if possible

**Comment by jgoizueta** [comment]
I'm also puzzled by the capitalization, the category names aren't.
Regarding the format, since the labels/categories are being explicitly constructed by the user, it is up to them (up to my ignorance in this case, the use of "to" etc.). Do you think CF should provide some kind of helper for generating legends/categories in this case?

**Comment by makella** [comment]
@jgoizueta hiii! 
ok, I see. I think I know why the legend is capitalizing "to" that is because in the legends, even if the attribute name is lowercase, we convert the first letter to uppercase which why this is happening. hmmmmm.... this is a totally different case than our original thinking with category names therefore, yes! I definitely think there should be a helper for this... but I'm not sure what we should do about the capitalization. 

I haven't tried this myself yet (probably a good step)

**Comment by makella** [comment]
hiii ok! sooo I took a look and i get what is going on! sorry i wasn't really clear about how this was happening earlier and din't realize you could do a custom legend like that!! wow!

Also, REALLY like the conversion to minutes 🙏 so good!

Based on that,
- yes! a simple fix for the legend ranges `-`

<img width="575" alt="Screen Shot 2019-10-22 at 3 58 59 PM" src="https://user-images.githubusercontent.com/1566273/67337921-40997e00-f4e5-11e9-9520-cfbd54b4d48e.png">

- alternatively, I think we could even do away with the ranges

<img width="630" alt="Screen Shot 2019-10-22 at 3 57 18 PM" src="https://user-images.githubusercontent.com/1566273/67337959-5444e480-f4e5-11e9-8240-0b56ea1206f1.png">

### Regarding a helper
Two things come up for me to answer this:
- will a user know how to make this legend? 
- will a user know to use a `color_category_layer` for numeric ranges and to switch the color scheme to a sequential one?

I'm guessing the answer to both is no... so I think having a `iso_layer` helper (or something) would be a great idea. 

Sorry about the misunderstanding earlier... now I gotta learn more about how you did that custom legend :)

**Comment by alrocar** [comment]
👋 

Reading the whole thread, I think we decided to add an `iso_layer` helper, right? At the same time we hace a couple of methods for exclusive vs non-exclusive polygons to visualize or analyze.

My doubt is: since we are in the stabilization phase to get to a RC1 in a few weeks, do we want to implement that helper? or is it just fine to leave the user the responsibility to style the isolines?

**Comment by Jesus89** [comment]
IMO it's easy to add this method so we can provide a simple solution to visualize isolines, which, on the other hand, is not trivial to do.

**Comment by makella** [comment]
i agree!

**Comment by Jesus89** [comment]
Helper method done in https://github.com/CartoDB/cartoframes/pull/1135
