### ISSUE TITLE
Datasets by geometry

### ISSUE THREAD

**Issue by alrocar** [CartoDB/cartoframes#1031]
We have these two entities in the catalog 

```sql
CREATE TABLE datasets
(
id TEXT  PRIMARY KEY ,
provider_id TEXT,
category_id TEXT,
data_source_id TEXT,
name TEXT,
description TEXT,
country_iso_code3 TEXT,
language_iso_code3 TEXT,
geography_id TEXT,


CREATE TABLE geographies
(
id TEXT PRIMARY KEY,
provider_id TEXT,
name TEXT,
description TEXT,
country_iso_code3 TEXT,
language_iso_code3 TEXT,
version TEXT,
geom_coverage GEOMETRY, -- admin,quadkey,zipcode...
```

Where `geography_id` is a FK.

Given a polygon, we want to be able to select the datasets in the catalog with available data for  that region. Something like:

```python
datasets = catalog.datasets(polygon)
```

The format of the polygon is yet to be defined (but it can be a shapely geometry).

We'd need to query the catalog with a query like this:

```sql
SELECT d.*
FROM geographies g
LEFT JOIN datasets d
ON g.id = d.geography_id
WHERE ST_Intersects(ST_geometryfromtext(local_polygon_wkt, 4326), geom_coverage)
```

So basically, convert the polygon to a WKT or WKB and perform the spatial intersection to get the list of datasets.

**Comment by alrocar** [comment]
cc. @oleurud

**Comment by alasarr** [comment]
First version working:

![image](https://user-images.githubusercontent.com/1161870/66350516-d2d54a00-e95b-11e9-844e-8a989340fad0.png)

It only supports a dataset as input, but I'd like to add support to:
- Pandas dataframe in WKT or WKB
- GDF
- Single geom in WKB

**Comment by alasarr** [comment]
Just added support for WKT and GeoPandasDataFramw 💪
