### ISSUE TITLE
Cannot filter catalog using standard Pandas 

### ISSUE THREAD

**Issue by alasarr** [CartoDB/cartoframes#1032]
I've tried to filter the catalog using the standard Pandas method.

What did I  try to do?
1. Get all datasets of USA
2. Filter theses datasets to get only open_data 

What did it happen?
It looks our instance of data frame returns a boolean when it should return a pd.Series

Notebook with the issue and the workaround with Pandas: [catalog_filter_bug.ipynb.zip](https://github.com/CartoDB/cartoframes/files/3659029/catalog_filter_bug.ipynb.zip)

![image](https://user-images.githubusercontent.com/1161870/65709936-4345b680-e092-11e9-94dc-2c5402e0e4e3.png)

**Comment by esloho** [comment]
Should we close this bug? @alasarr @alrocar

**Comment by alrocar** [comment]
Being tackled [here](https://github.com/CartoDB/cartoframes/issues/1038)
