### ISSUE TITLE
Should Map's title and descriptions kwargs be added to legend?

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#1037]
The `title` and `description` kwargs don't seem to do anything when viewing the map in the notebook. Inspecting the HTML though it looks like they do set the `<title>` tag and `<meta name="description">`. This isn't apparent from the notebook, and the `title` may be overwritten by the `Map().publish('map title')` operation.

I found this out struggling to get an overall legend title on my map to explain the three different layers in a concise way.

**Comment by Jesus89** [comment]
Using Layer title instead for the legend. Also, title, description, and footer can be set to each legend
