### ISSUE TITLE
Enrichment compatibility Input data

### ISSUE THREAD

**Issue by alasarr** [CartoDB/cartoframes#1039]
After some tests, it looks augmentation doesn't work at the following cases:

1. Input is a remote Dataset: it looks download is skipped.

2. Input is a dataframe with the geom in wkb.

**Comment by alasarr** [comment]
Ping @cmongut and @alrocar for awareness

**Comment by alasarr** [comment]
Maybe the reason of this issue is the lack of doc: https://github.com/CartoDB/cartoframes/issues/1040

**Comment by alrocar** [comment]
cc. @oleurud

**Comment by oleurud** [comment]
> Input is a remote Dataset: it looks download is skipped.

We are not downloading the data by default. The reason is: it is needless to download the data in visualization (because VL is requesting against Maps API)

**Comment by alasarr** [comment]
>We are not downloading the data by default. The reason is: it is needless to download the data in visualization (because VL is requesting against Maps API)

Sure, I mean we're skipping the download at the enrichment process
