### ISSUE TITLE
Documentation: geometry format for dataframe

### ISSUE THREAD

**Issue by alasarr** [CartoDB/cartoframes#1040]
At the current doc, it's not clear how the geometry format of a dataframe should be. I've had to fight a little bit with the library to understand it. I think it's quite important because it could be too hard for users without a strong GIS knowledge.

Current doc: 

>Generic data class for cartoframes data operations. A Dataset instance can be created from a dataframe, geodataframe, a table hosted on a CARTO account, an arbitrary query against a CARTO account, or a local or hosted GeoJSON source. If hosted, the data can be retrieved as a pandas DataFrame. If local or as a query, a new table can be created in a CARTO account off of the Dataset instance.

We don't specify the format of the geometry for a dataframe. I think we support:
- Shapely
- WKB
- WKT
- I think we'll make life easier for developers if we create a mechanism to create a geom based on a lat,lng column. 

cc: @cmongut @alrocar

**Comment by alrocar** [comment]
> I think we'll make life easier for developers if we create a mechanism to create a geom based on a lat,lng column

It's already possible.

Adding the documentation label.

Thanks!

**Comment by alasarr** [comment]
Already done in CartoDataFrame

**Comment by Jesus89** [comment]
```py
cdf = CartoDataFrame(...)

cdf.set_geometry_from_xy('lng', 'lat', drop=False/True, inplace=False/True)
```
