### ISSUE TITLE
Enrichment parameters - complete support

### ISSUE THREAD

**Issue by alasarr** [CartoDB/cartoframes#1042]
Enrichment signature was defined at the beginning as:

```python
enrich.points(df, “point_field”, *enrich_object*) #df is a dataframe
```

**enrich_object** was defined as:
```
Array of Variables objects,
Variable object
Dataset object
Variable or Dataset id (string)
Array of variable ids
```

We have implemented:

```python
enrich.enrich_points(df,enrich_object)`
```
Enrich object supported at the current version is: Variable object or Variables object.

We need to improve it to:

1. Add support for standard list or tuples. [Variable1,Variable2] or (Variable1, Variable2). Variables object is just a list so it will be supported via standard list.
2. Add support for Dataset object or [Dataset]
3. Add support for enrichment using ids. 
4. Add support for selecting a dataframe with multiple geom columns. For that, we need a parameter to specify the column to pick. I think we could create an optional parameter geom_field=None for this.

**Comment by alrocar** [comment]
Points 1, 2 and 3 duplicate this [issue](https://github.com/CartoDB/data-observatory/issues/188)

Also take into account we were considering this approach as well as the input for enrichment:

```
credentials = Credentials(`username`, `api_key`) # the API key has permissions to list the purchased datasets
datasets = catalog.datasets(credentials) # internally it calls the list purchased datasets APIs, gets a list of dataset IDs and returns a list of Dataset instances
variables = datasets.variables() # we need a way to get all the variables from the datasets or filter them. It can be anything more manual or involved if we don't support a method like this
enrich(df, variables) # we pass the variables instances
```

See related [issue](https://github.com/CartoDB/data-observatory/issues/194).

**Comment by oleurud** [comment]
As @alrocar 1, 2 and 3 are already solved. 

And the last one is solved too because we have a `data_geom_column` in `enrich_points` and `enrich_polygons`. 

So, I am going to close this one, reopen it if I am losing something
