### ISSUE TITLE
Avoid dataframe copy

### ISSUE THREAD

**Issue by oleurud** [CartoDB/cartoframes#1045]
We are doing a copy of the original dataframe in the enrichment function. I understand we are trying to avoid changing the original dataframe, but since the user is doing an enrichment (we are adding info, removing nothing) I suppose it is not important for the user, but we are using 2x memory which could be a problem easily using GB's datasets. 

What do you think?

**Comment by alrocar** [comment]
More [context](https://github.com/CartoDB/cartoframes/pull/989/files/df96d3f3a1ba64a84f7202285b87efa83e0d7b23#discussion_r324688073) about this.

I'm in favour on looking for more performant solutions, although it might be not a priority right now.

**Comment by Jesus89** [comment]
This should not be needed with the Enrichment API, so this ticket is superseded. Closing it.
