### ISSUE TITLE
Download geographies filtering by BBOX (or geometry)

### ISSUE THREAD

**Issue by alrocar** [CartoDB/cartoframes#1048]
Related to https://github.com/CartoDB/data-observatory/issues/189

**Comment by oleurud** [comment]
@arredond prefers filtering by any shapely geometry and I agree with it because it is more generic and you can use it to filter by the BBOX as a geom

**Comment by alrocar** [comment]
I agree. OTOH, bbox are still very handy since they are just an array of 4 point coordinates. There are [widely used tools](http://bboxfinder.com/#0.000000,0.000000,0.000000,0.000000), that allow you to easily copy paste a bbox and use it all around.

Could we add an example to show how to from an array of 4 coords representing a bbox, we create a shapely geometry and then filter the download?

**Comment by arredond** [comment]
@alrocar since we already use GeoPandas, which depends on Shapely, I'd recommend just using that:

```python
from shapely.geometry import box

my_bbox = box(0, 0, 1, 1) #minx, miny, maxx, maxy

print(type(my_bbox))

<class 'shapely.geometry.polygon.Polygon'>

```

**Comment by alrocar** [comment]
Great then :)

Thanks @arredond

**Comment by Jesus89** [comment]
This will be done in the Enrichment API, so this ticket is superseded. Closing it.
