### ISSUE TITLE
feature request: add intuitive `centering` options for maps

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#105]
This would make it nice and easy to tell stories in a notebook:

```python
# view of projects in Bangladesh
cc.map('green_energy_projects', center='bangladesh')
<displays map data centered on Bangladesh>

# view of projects in West Texas
cc.map('green_energy_projects', center='west texas')
<displays map centered in West Texas>
```

If `center` kwarg is present, it should override `zoom`, `lng`, and `lat` (or vice versa).

**Comment by andy-esch** [comment]
Maybe use carto geocoding to get a latlong and zoom and print a warning if no match is found

**Comment by alrocar** [comment]
Stale issue. Closing 👋
