### ISSUE TITLE
Integrate licensing

### ISSUE THREAD

**Issue by alrocar** [CartoDB/cartoframes#1055]
So we have brand new APIs in our backend to license datasets and we need to integrate them into the CF workflow.

I'm adding here a high-level description of the work to do:

- Request licensing information to the backend: A `Dataset` in the catalog should have some method to request licensing information. It could be something like this:

```python
dataset = Dataset.get(id)
dataset.license_info(credentials) # Request to the corresponding licensing API
```

Check this [comment](https://github.com/CartoDB/data-observatory/issues/122#issuecomment-533977834) for information about `license_info`

- licensing:

```python
dataset = Dataset.get(id)
dataset.license(credentials) # This will make a request to the corresponding licensing API, depending on the availability the backend will do a speed or normal licensing
```

@cmongut This is the task to integrate the licensing in CARTOframes. You might want to review/change the approach.

NOTE: I update this ticket with `Dataset.get(id)` instead of `catalog.dataset(id)`.

**Comment by alrocar** [comment]
This issue supersedes [this other one](https://github.com/CartoDB/data-observatory/issues/157).

**Comment by Jesus89** [comment]
Superseded by https://github.com/CartoDB/cartoframes/issues/1079
