### ISSUE TITLE
Feature request: helper layers should be able to accept arbitrary widget inputs

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#1059]
Currently helper layer functions only accept `widget=True|False`, indicating whether the user wants a widget for the variable being symbolized on the map. It is also common to want to add arbitrary widgets off of other variables in the helper layers. For example, in this code snippet I want a category map but also have included the distribution of visits:

```python
color_category_layer(
    point_sql,
    'hvl',
    title='Locations of Census Block Groups',
    widget=histogram_widget('num_visits')
)
```

**Comment by makella** [comment]
closing since we've addressed with latest updates!
