### ISSUE TITLE
Force CHANGELOG.md to be updated on every PR

### ISSUE THREAD

**Issue by alrocar** [CartoDB/cartoframes#1065]
Not sure how to configure this in Github.

Maybe @alberhander can help on this? 🙏

**Comment by alberhander** [comment]
Hey @alrocar I've googled it and it doesn't look like Github implements and automatic way to update those. 

On the other hand, there is a current project that seems to be working: [Github Changelog Generator](https://github.com/skywinder/github-changelog-generator).

I'm testing implementing it in a Jenkins Job to keep the [Changelog.md](https://github.com/CartoDB/IT-stuff/blob/master/Changelog.md) of my repo updated. I'll let you know how it works.

**Comment by alrocar** [comment]
Sorry I wasn't more specific. I was referring to the same thing we do in https://github.com/CartoDB/cartodb where a PR needs to update the `NEWS` file or there's an alert otherwise.

**Comment by Jesus89** [comment]
This is not required anymore. Thanks!
