### ISSUE TITLE
Remove warnings from carto-python in CARTOframes

### ISSUE THREAD

**Issue by alrocar** [CartoDB/cartoframes#1090]

**Comment by oleurud** [comment]
We are already filtering some messages from `carto-python`:
```
from warnings import filterwarnings
filterwarnings("ignore", category=FutureWarning, module="carto")
```

We need to filter others messages that are not `FutureWarning` ones, but:
```
warnings.warn('xxx)
```

**Comment by alrocar** [comment]
We used FutureWarnings for APIs in carto-python that are not public and we didn't want them to be used by other people (other than us).

So, for this case, in CARTOframes it's fine to silence FutureWarnings. In carto-python they still make sense.

About the rest of the warnings, I'd consider to remove them from the code (ideally substitute them by a logger).
