### ISSUE TITLE
Implement retry policy with rate limits and upload

### ISSUE THREAD

**Issue by oleurud** [CartoDB/cartoframes#1095]
We did in the `download` https://github.com/CartoDB/cartoframes/blob/develop/cartoframes/lib/context/api_context.py#L32-L42 and we should implement it in the `upload` case too.

We could use a decorator for that, using it in both methods

**Comment by Jesus89** [comment]
https://app.clubhouse.io/cartoteam/story/93723/optimize-upload-to-carto

**Comment by Jesus89** [comment]
Done. It will be available in the next stable release 1.0.5
