### ISSUE TITLE
Method to make df.carto_map permanent 

### ISSUE THREAD

**Issue by stuartlynn** [CartoDB/cartoframes#11]
Probably actually a argument to df.carto_map( persist=True)

**Comment by andy-esch** [comment]
After speaking with @rochoa, I found out that for the current state of Engine/Builder, this is only possible for Maps API + carto.js, not for persistent maps (e.g., like the type used in iframe embeds) made through the carto interface.

**Comment by stuartlynn** [comment]
If we take the CSS and SQL and generate a .carto file from it and upload that through the import API, it will generate a persisted map I think

**Comment by andy-esch** [comment]
Ah, nice... I'll just template a carto.json to fill in the important bits.

**Comment by andy-esch** [comment]
omg it happened: https://cartoframes.readthedocs.io/en/v1.0b1/kuviz.html
