### ISSUE TITLE
Small tweaks to  catalog

### ISSUE THREAD

**Issue by alasarr** [CartoDB/cartoframes#1100]
[x] 1. Return slug at every object with slug. For example, Dataset.slug doesn't work but it appears at dataset.to_dict. We talked about removing slug for the model but I'm regretting it after I've played a little bit with the library. 

[x] 2. Dataset.to_dict(): remove summary_jsonb.

[x] 3. Rename Catalog to CatalogDataset

[ ] 4. Custom `__repr__` for Variable objet. 

![image](https://user-images.githubusercontent.com/1161870/66732255-6bd3fb80-ee5b-11e9-8e2e-975222e564ef.png)

That would be great to include only for Variable object the description fields at the __repr__.

For longer description (bigger than 20 characters  let's add an ellipsis.

<Variable('CRMCYPERC_1a97ab94', 'My cool short description')>
<Variable('CRMCYPERC_1a97ab94', 'My cool long description bla bla bla ...'  )>

**Comment by esloho** [comment]
> 1. Return slug at every object with slug. For example, Dataset.slug doesn't work but it appears at dataset.to_dict. We talked about removing slug for the model but I'm regretting it after I've played a little bit with the library.

I finally added the slug property at #1093 since I needed it for the CatalogList.get(slug) to work :)

**Comment by esloho** [comment]
> 2\. Dataset.to_dict(): remove summary_jsonb.

I assume we want that for all entities with a summary_jsonb field (like Variable or Geography), don't we @alasarr ?

**Comment by alasarr** [comment]
>I assume we want that for all entities with a summary_jsonb field (like Variable or Geography), don't we @alasarr ?

Yes, but only for `to_dict` the property should be available for describe

**Comment by esloho** [comment]
> 3\. Rename Catalog to CatalogDataset

I think this will be included as part of #1018 . Should we handle it now or wait for that issue? @alrocar @oleurud

**Comment by alrocar** [comment]
As for know I'd do what @alasarr requests, since these changes may affect directly the demo notebook and he's the owner of it.

**Comment by esloho** [comment]
Perfect, I'll change it here then :+1:

**Comment by esloho** [comment]
> For longer description (bigger than 20 characters let's add an ellipsis.
> 
> <Variable('CRMCYPERC_1a97ab94', 'My cool short description')>
> <Variable('CRMCYPERC_1a97ab94', 'My cool long description bla bla bla ...' )>

Maybe we should make it for longer than 30 characters or so (even the string 'My cool short description" exceeds the 20 characters limit).
