### ISSUE TITLE
Popup backgrounds don't update when in dark mode

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#1106]
When the basemap is changed to dark matter, almost all style elements are switched from white to black for backgrounds and black to white for text. It seems that the popup backgrounds is not updated so the white text is not visible against the white background. Here I'm doing CTRL+A to select all text on the page to get it highlighted against the background:

<img width="420" alt="Screen Shot 2019-10-14 at 1 40 26 PM" src="https://user-images.githubusercontent.com/1041056/66771499-6345ea00-ee88-11e9-849a-65b4f671d00b.png">

cc @djfan

**Comment by djfan** [comment]
another example
<img width="1360" alt="Screen Shot 2019-10-14 at 4 27 11 PM" src="https://user-images.githubusercontent.com/13675438/66780736-9ba4f280-ee9f-11e9-96a3-ffebdbf288da.png">
<img width="1188" alt="Screen Shot 2019-10-14 at 4 27 03 PM" src="https://user-images.githubusercontent.com/13675438/66780741-9cd61f80-ee9f-11e9-8dda-0bcda9002230.png">

**Comment by makella** [comment]
@andy-esch 

I think @elenatorro fixed this last week! Will test again too!

https://github.com/CartoDB/cartoframes/issues/1099

**Comment by makella** [comment]
@elenatorro just to verify the test! now that i'm updated, checked again in develop and we're all good with dark popups and white text! 

@andy-esch woot!! :)

<img width="1029" alt="Screen Shot 2019-10-22 at 12 32 24 PM" src="https://user-images.githubusercontent.com/1566273/67317999-1eddce00-f4c8-11e9-8c4a-5879e4f2d779.png">

**Comment by andy-esch** [comment]
💥
