### ISSUE TITLE
Kuviz can not be embedded in an Iframe

### ISSUE THREAD

**Issue by cmongut** [CartoDB/cartoframes#1114]
When trying to show a kuviz inside an Iframe, we get the following error message:

`Load denied by X-Frame-Options: https://team.carto.com/u/eschbacher/kuviz/d39be4fc-53f7-44e8-8293-f4ed1a40af95 does not permit framing.`

People will want to show their kuvizs in their blog posts, for example.

[Related issue](https://github.com/CartoDB/cartodb/issues/15019)

**Comment by makella** [comment]
as a side note, for the blog posts I've been helping with, we've been pushing the maps to the [carto-vl-maps repo](https://github.com/CartoDB/carto-vl-maps/tree/master/blog) as per @albertoac request to overcome

**Comment by alrocar** [comment]
Dups https://github.com/CartoDB/cartodb/issues/15019

**Comment by Jesus89** [comment]
Closed in https://github.com/CartoDB/cartodb/pull/15230
