### ISSUE TITLE
DO API re-definition

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/cartoframes#1126]
The goal of this issue is to define the final CF DO API in detail with the features that we want to include in the 1.0 release.

This is the current structure of the API:

```
cartoframes/data/
└── observatory
    ├── catalog
    └── enrichment
```

```py
from cartoframes.data.observatory import Catalog, Category, Country, CatalogDataset \
    Geography, Provider, Variable, enrich_points, enrich_polygons
```

**Comment by alrocar** [comment]
This is the document where we can define what is needed for DO in the RC1: 

https://docs.google.com/document/d/1I6hH7Ag7JzYbmBDx6bUY7A3C8Z35PurQVPFjO3Uo1oQ/edit?usp=sharing
