### ISSUE TITLE
Use the long-form of the error codes for the import api. 

### ISSUE THREAD

**Issue by ljwolf** [CartoDB/cartoframes#113]
@mehak-sachdeva showed me [this table](https://carto.com/docs/carto-engine/import-api/import-errors) in slack. 

When you get one of these errors in cartoframes, it should raise a relevant subclass of `Error` in python, with a correct error message drawn from this table. We could scrape the table on the fly at import (or if there's somewhere internally with the metadata about what errors are possible), or we could just dump this into json and ship it with cartoframes.

**Comment by ljwolf** [comment]
@andy-esch has the right idea with #112 

after the import api stabilizes, I think that an in-CLI solution will be more helpful. If that inline solution can grab valid error codes on the fly, that'd mean future API changes would not require the package to change.

**Comment by andy-esch** [comment]
Agreed. Not having to leave the notebook is important to me.

**Comment by andy-esch** [comment]
Based on the last five months of experience, we haven't noticed a big need for error reporting beyond what's in the current state of the code. The errors for write operations are reported here and cover the most basic cases: https://github.com/CartoDB/cartoframes/blob/cf30860c911bce67bd428c74a23b708d91f149f7/cartoframes/context.py#L520-L565
