### ISSUE TITLE
[DO - Enrichment] - Fix enrichment API

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartoframes#1137]
After last changes in DO, it's needed to modify the Enrichment methods, as well as define a clear workflow to understand the different steps a user should follow to enrich data.

- [x] Public datasets:
    - [x] points
    - [x] polygons
    - ~id (?) https://github.com/CartoDB/data-observatory/issues/211~
- [x] Private datasets:
    - [x] points
    - [x] polygons
    - ~id (?)~
- [x] Tests
- [x] Docs (_examples_)
    - [x] public dataset
        - [x] points
        - [x] polygons
    - [x] private dataset - subscription workflow

**Comment by Jesus89** [comment]
Closed in #1140
