### ISSUE TITLE
Add best practices section to viz/map documentation

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#1147]
There are several best practices for creating maps that we should tell users about. One that quickly comes to mind:

1. When create a map from a local dataset, it's best to subset the dataset as much as possible: `df[['col1', 'col2', 'geometry']]` This only includes the data to be mapped, which reduces the memory footprint of the local map. I frequently have issues with sluggish local maps since all of the geojson is in the iframe embed.
2. Uh.. I'll get back to you ;)

**Comment by cmongut** [comment]
Mmm, what about doing #551 to solve this?

**Comment by andy-esch** [comment]
That'd be a nice solution

**Comment by Jesus89** [comment]
This is already done in beta6

**Comment by andy-esch** [comment]
❤️
