### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by FerGolden** [CartoDB/cartoframes#1149]
Hi, 
In the following section the link to download the "arlington" dataset used in the example seems to be broken: cartoframes/docs/developer-center/guides/04-Quickstart-Part-1.md
Thanks!

**Comment by makella** [comment]
hi @FerGolden! thank you for pointing this out we will update as soon as possible!

**Comment by makella** [comment]
closing this as it is a duplicate of: https://github.com/CartoDB/cartoframes/issues/1150 where we can update progress.

for reference, the _correct_ link to the dataset is here!
https://github.com/CartoDB/cartoframes/blob/develop/docs/developer-center/data/arlington_bikeshare_july_agg.geojson
