### ISSUE TITLE
Missing link for example dataset in documentation

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/cartoframes#1150]
In the [Quickstart part 1 section](https://carto.com/developers/cartoframes/guides/Quickstart-Part-1/#explore-your-companys-data) of the CARTOframes documentation, there is a file named `census_track.geojson` which is used in the quickstart as a layer for the CARTOframes map. However, there is no link to download the file.

![Screenshot 2019-11-04 at 08 58 00](https://user-images.githubusercontent.com/11177693/68106235-3b730080-fee1-11e9-908b-3983c98e6ac4.png)

This doesn't give the user the possibility to download the file and replicate the final part of the quickstart.

**Comment by makella** [comment]
thanks for pointing out @oriolbx! taking a look now...

**Comment by makella** [comment]
also reported by a user here: https://github.com/CartoDB/cartoframes/issues/1149

**Comment by elenatorro** [comment]
Now it's merged in develop 👌 however, the user won't be able see the link until the next release (docs can't be changed between releases)

Meanwhile, if anyone asks, please address them to this file https://github.com/CartoDB/cartoframes/blob/develop/docs/developer-center/guides/data/census_track.geojson
