### ISSUE TITLE
Remove dependency between releases and developer center

### ISSUE THREAD

**Issue by cmongut** [CartoDB/cartoframes#1161]
The idea is to be able to update the documentation of a release without the need of patching the release.
Options:
- Use a branch that starts from the release tag.
- Use tags that starts from the release tag.
- Create a new repo

**Comment by Jesus89** [comment]
I like the second option: `Use tags that start from the release tag.`. Branches can be removed and a new repo only for docs would increase the project complexity a lot. However, if we release with more frequency this will be automatically solved.

I add an example of a use case here:

We want to create a "release of documentation" for the `v1.0b4`.
1. Create a branch from the tag `v1.0b4` called `doc/v1.0b4-doc.0` (for example)
2. Commit all the documentation changes to that branch
3. When everything is ready, create the tag `v1.0b4-doc.0` pointing to the last commit of the branch
4. Merge the changes in `develop` or `master` depending on the release type
5. Remove the branch

In the Developer Center, we should make a little change to allow passing the version number (to show in the combo) and the tag (to load the data).
