### ISSUE TITLE
[DO - Enrichment] Download improvements

### ISSUE THREAD

**Issue by oleurud** [CartoDB/cartoframes#1164]
After https://github.com/CartoDB/data-observatory/issues/189 we have more ideas to improve the download method. We can create several issues for each case if needed.

- [ ] Use Big Query Storage API (we need to validate if it is possible to use: user permissions and is a beta feature)
- [ ] Download geographies filtering by BBOX https://github.com/CartoDB/cartoframes/issues/1048
- [ ] In dataset.download method, add a option to download the geometry (at the user's risk  because might get a huge dataframe with repeated geometries)

Still open to discussion/decision: 
- [ ] Check if enrichment could use download method (take advantage of the download improvements)

**Comment by Jesus89** [comment]
Dup https://github.com/CartoDB/cartoframes/issues/1257
