### ISSUE TITLE
Add range_label with unit conversion to isochrone output at the service level

### ISSUE THREAD

**Issue by makella** [CartoDB/cartoframes#1177]
hello!

Right now, when isochrones are created, they don't contain a categorical column to symbolize by unless used inside of the `isolines_layer` helper which does this conversion and legend creation for the user behind the scenes.

## Request
This ticket is to request that we add the categorical attribute `range_label` **_and_** the unit conversion at the service level so even if this dataset is exported and used with a different mapping library or with different styling that we still provide the pieces needed to create a proper map.

## Current blockers
The problem with the not having these fields is that if a user wants to create a map outside of a helper or use a different one, without the `range_label` column they won't be able to easily do that. The reason is because even if they do something like an equal interval classification (since there is the numeric `data_range` column), the legend, no matter which type you use, won't be correct, not to mention that they would have to know VL to construct the proper ramp and/or create a new string field that converts the ranges to categories and also the conversion.

Here are some visual examples of this blocker:

<img width="977" alt="Screen Shot 2019-11-07 at 11 34 13 AM" src="https://user-images.githubusercontent.com/1566273/68418537-a88ecc00-0155-11ea-832b-66f00c978ec2.png">
<img width="976" alt="Screen Shot 2019-11-07 at 11 33 53 AM" src="https://user-images.githubusercontent.com/1566273/68418558-afb5da00-0155-11ea-9089-97cbe28915ca.png">

cc @Jesus89 @elenatorro

**Comment by Jesus89** [comment]
Closed via https://github.com/CartoDB/cartoframes/pull/1130

**Comment by elenatorro** [comment]
I don't think we should close this one. When setting a label value, if the type is numeric it fails, I think we should take a look at this cc @Jesus89 @makella

**Comment by Jesus89** [comment]
The label value is generated in the service and it's always a string. The helper `isolines_layer` is an extension of a `color_category_layer`, so it does not work with numeric columns by definition.

**Comment by Jesus89** [comment]
Let's update the geojson file (to include the label column) and then close this.

**Comment by elenatorro** [comment]
Done, added in the drive directory, in both csv and geojson format 👍
