### ISSUE TITLE
Define privacity for kuviz

### ISSUE THREAD

**Issue by VictorVelarde** [CartoDB/cartoframes#1179]
Set privacity to private by default.

**Comment by VictorVelarde** [comment]
cc/ @csubira @cmongut

**Comment by alasarr** [comment]
Dup of https://github.com/CartoDB/cartoframes/issues/1286

**Comment by Jesus89** [comment]
In #1286 we are going to improve a bit the CF interface to publish maps (password by default, etc), but this is not exactly related to this issue, which consists of adding real private Kuviz maps (like Builder) to be accessible only from your account or organization.

As far as I know, these Kuviz improvements are not in progress right now, so we should tackle this in CF once the endpoint contains the new features.
