### ISSUE TITLE
[DO] fix DO user dataset name

### ISSUE THREAD

**Issue by oleurud** [CartoDB/cartoframes#1189]
Due to https://github.com/CartoDB/cartodb-central/issues/2582, we need to do the same as https://github.com/CartoDB/cartodb-central/pull/2591 did for getting the DO user dataset name in
https://github.com/CartoDB/cartoframes/blob/develop/cartoframes/auth/credentials.py#L223-L224

**Comment by gonzaloriestra** [comment]
We have finally changed only the name for the service account, but not for the datasets, so we don't need any change here. Sorry for the miscommunication, I mentioned @oleurud [here](https://github.com/CartoDB/cartodb-central/pull/2592), but I didn't realize about this issue.

**Comment by alrocar** [comment]
upp, I'm closing the issue + PR then. 

Thanks

**Comment by oleurud** [comment]
Ok, thank you!
