### ISSUE TITLE
A method like cc.query for writing custom CartoCSS for maps

### ISSUE THREAD

**Issue by mehak-sachdeva** [CartoDB/cartoframes#119]
It would be great to have a method with the cc.map() function to define custom CartoCSS for maps

**Comment by andy-esch** [comment]
Good idea. `cc.map` should have a `kwarg` for `cartocss` that overwrites `color` and `size` keys.

**Comment by michellechandra** [comment]
S/B: 13296911

**Comment by alrocar** [comment]
Stale issue. Closing 👋
