### ISSUE TITLE
Need a legend type to use with basic point, line, and polygon features

### ISSUE THREAD

**Issue by makella** [CartoDB/cartoframes#1192]
As I've been working with our DS team and others on their CF maps, I'm noticing several patterns and areas where we are missing some visualization pieces.

One of these is that there isn't a "basic" point, line, and polygon legend type. For cases when there is a map like the one below (which is the result of an extensive analysis), there isn't a straightforward way to get a legend for the point and polygon features in the map:

<img width="1564" alt="Screen Shot 2019-11-12 at 12 24 33 PM" src="https://user-images.githubusercontent.com/1566273/68703546-22ed9080-0548-11ea-94b4-ee8746b83ee0.png">

## Current Options
Currently, the only option that would work for this map is the legend type `color-category`. In the map below, that's what I've used and set the `title` of the legend to serve as the description of the single legend item.

There are a couple of issues with this approach:
- First, a user may not automatically know to use a `color-category` legend to add a legend to this map because it isn't coloring categories
- Second, the label "Color" isn't modifiable and isn't really descriptive of what the layer on the map is and becomes a distraction and a blocker for use.
- In this case, the `variable` option would not help because again, this map uses basic symbology, not based on an attribute.

<img width="1439" alt="Screen Shot 2019-11-08 at 2 10 20 PM" src="https://user-images.githubusercontent.com/1566273/68705539-79a89980-054b-11ea-984e-c6792a0d6579.png">

## Proposal
We have the `default_legend` type which I think could work in these scenarios with a couple of enhancements:
- First, and most obviously is to add the features on the map to draw in the legend
- Second, is to add a `label` option for the legend item description, similar to this [Airship Example](https://carto.com/developers/airship/examples/#example-as-legend-wrapper-basic-usage) 
  - by default features would have no text like we do in Builder:
<img width="696" alt="Screen Shot 2019-11-12 at 1 33 46 PM" src="https://user-images.githubusercontent.com/1566273/68708497-16216a80-0551-11ea-9c37-4e339c03da6e.png">
  - using the `label` option would give users the flexibility to be able (or to not) label the legend item

**Comment by Jesus89** [comment]
Can we close this issue @elenatorro?

**Comment by elenatorro** [comment]
Yes :)
