### ISSUE TITLE
from cartoframes.data import Dataset fails

### ISSUE THREAD

**Issue by sanjitpal09** [CartoDB/cartoframes#1193]
from cartoframes.data import Dataset command fails with the following error

No module named 'cartoframes.data'

**Comment by andy-esch** [comment]
Please include the cartoframes version and python version you are using

```python
from cartoframes.__version__ import __version__
print(__version))
import sys
print(sys.version)
```

**Comment by Jesus89** [comment]
Dataset class has been deprecated. Use CartoDataFrame in the beta6.
