### ISSUE TITLE
Dataset.exists raise AttributeError for local dataset

### ISSUE THREAD

**Issue by jorisvandenbossche** [CartoDB/cartoframes#1206]
This might be something users will not typically (I was just playing around and exploring the API), but if you create a Dataset from a local in memory dataframe, some of the Dataset methods (logically) do not work:

(from https://github.com/CartoDB/cartoframes/blob/develop/examples/downloading_and_uploading_data/create_dataset_from_geojson.ipynb)

```
import geopandas

df = geopandas.read_file('../files/sustainable_palm_oil_production_mills.geojson')
df.head()

from cartoframes.data import Dataset

ds = Dataset(df)
df.exists()
```
gives `AttributeError: 'NoneType' object has no attribute 'execute_query'` for me (cartoframes 1.0b5). 
A more informative error message could probably be raised to the user.

**Comment by Jesus89** [comment]
Hi @jorisvandenbossche. The bug you point is a "Dataset" concept issue because a Dataset of a DF has no "exists" implementation, as a remote SQL query.

Fortunately, we have deprecated this "Dataset" class in this PR https://github.com/CartoDB/cartoframes/pull/1130, so we can close this issue.
