### ISSUE TITLE
Fix links in reference docs for py:class in the arguments of a method

### ISSUE THREAD

**Issue by alrocar** [CartoDB/cartoframes#1210]
Example `set_default_credentials` has a `Credentials` class as part of its args. It's being rendered in italics, but there's no link to go to the `Credentials` class reference.

```
Args:

        credentials (:py:class:`Credentials <cartoframes.credentials.Credentials>`, optional):
          A :py:class:`Credentials <cartoframes.credentials.Credentials>`
          instance can be used in place of a `username | base_url`/`api_key` combination.
```

![Screenshot 2019-11-18 at 15 32 24](https://user-images.githubusercontent.com/623650/69061055-c5aa8100-0a18-11ea-9ad9-801affb99c03.png)

**Comment by alrocar** [comment]
cc. @elenatorro @Jesus89 for awareness (I don't think it's prioritary right now)

**Comment by alrocar** [comment]
upss I checked the docs generated by sphinx and it's not a link, so maybe it's just a matter of the tag being used (maybe :obj: instead of :py:class:).

I assign this to me and I'm going to investigate.

Sorry for the noise 🙏

**Comment by Jesus89** [comment]
This is because the path is cartoframes.auth.Credentials

**Comment by Jesus89** [comment]
https://app.clubhouse.io/cartoteam/story/93700/fix-links-in-reference-docs-for-py-class

**Comment by josemazo** [comment]
PR [CARTOframes#1665](https://github.com/CartoDB/cartoframes/pull/1665)
