### ISSUE TITLE
Handle multiple geometries in a DataFrame

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartoframes#1212]
Context
---

CARTO VL does not support multiple geometries per layer. Therefore, it raises an error when, for instance, the data the layer receives contains more than one geometry. This error appears in the browser console, but we don't provide any feedback from CARTOframes.

![Screenshot 2019-11-18 at 17 08 29](https://user-images.githubusercontent.com/3824953/69070175-fb0a9b00-0a27-11ea-841a-8f605a7a7d9c.png)

The best solution would be to display an error in the notebook cell when this happens. Another possible solution (which will require more time) would be to detect the different types of geometries and add a layer per each geometry detected, but this will affect the helper methods.

Maybe we could have some utils function in CARTOframes to split the data into different dataframes, one per geometry.

How to reproduce it
---

```py
import geopandas as gpd
from cartoframes.viz import Map, Layer

geojson = {
    "type": "FeatureCollection",
        "features": [{
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [102.0, 0.5]
            },
            "properties": {
                "prop0": "value0"
            }
        },{
            "type": "Feature",
            "geometry": {
                "type": "LineString",
                  "coordinates": [[102.0, 0.0], [103.0, 1.0], [104.0, 0.0], [105.0, 1.0]]
            },
            "properties": {
                "prop0": "value0",
                "prop1": 0.0
            }
        },{
            "type": "Feature",
            "geometry": {
                "type": "Polygon",
                "coordinates": [[[100.0, 0.0], [101.0, 0.0], [101.0, 1.0], [100.0, 1.0], [100.0, 0.0]]]
            },
            "properties": {
                "prop0": "value0",
                "prop1": {"this": "that"}
             }
           }
         ]
    }

df = gpd.GeoDataFrame.from_features(geojson)
Map(Layer(df))
```

**Comment by cmongut** [comment]
I would just handle the error for now

**Comment by cmongut** [comment]
This issue has been also reported by customers that had several geometries in their dataset.

**Comment by Jesus89** [comment]
Closed in https://github.com/CartoDB/cartoframes/pull/1541
