### ISSUE TITLE
[DO - Enrichment] sources problems

### ISSUE THREAD

**Issue by oleurud** [CartoDB/cartoframes#1213]
```
from cartoframes.data.observatory import Enrichment
from cartoframes.data import Dataset

ds = Dataset('test_do_geography', credentials=credentials)

enrichment = Enrichment(credentials)

enriched_dataset_df = enrichment.enrich_polygons(
    ds,
    variables=['MLTCY44111_31a6b6a8']
)
```

Also fails reading a CSV with pandas and using the dataframe in the enrichment

**Comment by cmongut** [comment]
Should we wait until the cdf is merged to see if it makes sense to tackle this?

**Comment by oleurud** [comment]
ummm, good point. We could wait, but we could do it testing it only with geoDataFrames

**Comment by oleurud** [comment]
More coomon errors happening (I am not saying to solve them, because of they are user-related)
- error uploading source dataframe to BQ: `400 Error while reading data, error message: Invalid polygon loop: Edge 241 has a duplicate vertex with edge 245`
- the source dataframe has some null geometries:  'NoneType' object has no attribute 'wkt'

**Comment by Jesus89** [comment]
Hi. I have updated the enrichment functions to be like `CDF = enrichment(DF)`. You can test it in the branch: https://github.com/CartoDB/cartoframes/tree/carto-data-frame.

I have changed the way the geojson data is computed, so maybe the polygon loop issue and the null geometries issue could be solved "de rebote". Could you test it?

**Comment by oleurud** [comment]
from @alejandrohall: the wkt to geojson function should be:
```
g1 = shapely.wkt.loads(s)

g2 = shapely.geometry.mapping(g1)

json.dumps(g2)
```

**Comment by Jesus89** [comment]
Yes, that's exactly what it does now, but even better, because it does not need the wkt, it can load directly the geometry:

- https://github.com/CartoDB/cartoframes/blob/carto-data-frame/cartoframes/utils/geom_utils.py#L219
- https://github.com/CartoDB/cartoframes/blob/carto-data-frame/cartoframes/data/observatory/enrichment/enrichment_service.py#L86

**Comment by oleurud** [comment]
Cool! And checking the things you have changed in enrichment, looks very nice :muscle:
