### ISSUE TITLE
BUG Widget Animation - Visualization layer helpers

### ISSUE THREAD

**Issue by mabarin** [CartoDB/cartoframes#1215]
Hey!

I was trying to add to the map the animation widget as it done in the example for the Visualization layer helpers section but it didn't work.

The dataset was the Seattle_collisions.

I got troubles with CF and my laptop when I'd be able to reproduce it I'll attach the notebook. But at the moment, I wanted to leave a comment to let you know. 

Thank you!

**Comment by makella** [comment]
thanks for letting us know @mabarin! 

so to be clear, you were using the animation_layer helper? if so, you should get a time-series widget by default.

at this time you can't add a widget inside of a viz layer...

but yes, please share when you are back up and running!

**Comment by mabarin** [comment]
Yes, but I didn't get any times-series widget. It didn't appears anything by the side.

You are welcome!! Always happy to help :)

**Comment by cmongut** [comment]
Let's close this as we have deprecated the visualization helpers in favour of using style helpers.
Thanks @mabarin!
