### ISSUE TITLE
Add SQLClient to documentation reference

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#1217]
The `SQLClient` class and methods are really useful for doing database operations that are intensive, like big `UPDATE`s, `INSERT`s, `CREATE TABLE ... AS SELECT ...`. It is especially useful for these because `SQLClient().execute(query)` 1. Won't time out, 2. Not a use case for `Dataset(query)`. Therefore this class allows one to do DB operations in their workflow without having to use other tools.

These methods allow us to add new columns to a table and update them:
```python
set_default_credentials('eschbacher', 'abc123')
sql_client = SQLClient()

sql_client.execute('''
ALTER TABLE mytable ADD COLUMN newcol numeric;

UPDATE mytable
SET newcol = CASE WHEN category_col = 'a' THEN 1
                  WHEN category_col = 'b' THEN 2
                  ELSE 0 END
''')
```

cc @elenatorro

**Comment by Jesus89** [comment]
This can be closed when https://github.com/CartoDB/cartoframes/pull/1327 is merged.
