### ISSUE TITLE
Upload / download / enrichment times

### ISSUE THREAD

**Issue by oleurud** [CartoDB/cartoframes#1218]
**download 220MB**: 5 minutes (the lib make the download by bunch of rows, stops during some seconds, download another bunch, stops, ...)

**upload 220MB**:  1 minute

**Enrichment (source: 5Mb file, 412 polygons, 1 var enrichment)**
- prepare_data (wkt to geojson) 2.634431838989258
- upload 15.490696430206299        
- query 7.78495979309082
- download 0.8898262977600098
- geojson to wkt 1.2111029624938965

My connection:
![image](https://user-images.githubusercontent.com/421145/69168677-6bccb880-0af7-11ea-938f-28da19f36bb8.png)

It seems like we should try the Storage API way

cc/ @alasarr

**Comment by alasarr** [comment]
Totally agree with these numbers we need to integrate with storage API. 

But a couple of things that looks odd to me:

1. Why is upload (220MB) 5x faster than download? Because of the client? 
2. Why on enrichment upload is 15x slower than download?

**Comment by oleurud** [comment]
- Why is upload (220MB) 5x faster than download? Because of the client?
Yes, the client download a bunch of rows, stops during some seconds, download another bunch, stops, ... In the upload, it does it as expected without stops.

- Why on enrichment upload is 15x slower than download?
The size of the uploaded data is much bigger (~5Mb) than the downloaded data (I suppose in order kb). In the enrichment, we are uploading 2 columns: geometry and the join id. In this case in the download, I was downloading 2 columns: an aggregated variable and the join id.

**Comment by alasarr** [comment]
Thanks! It makes sense and interesting because with these numbers the priority is to improve upload first because it will improve enrichment and it's more important than download functionality.

cc: @cmongut

**Comment by cmongut** [comment]
If I understood it correctly, this means the geometry column is the problem and we should try to convert it to another format before uploading it?

**Comment by Jesus89** [comment]
I'm not sure if we are using `geojson` because is the only format BQ admits, but it would be nice if we can pass the geometry column encoded in WKB.

**Comment by alasarr** [comment]
>If I understood it correctly, this means the geometry column is the problem and we should try to convert it to another format before uploading it?

Why is this related with the geometry format?

Not sure about priorities... Because the more variables the slower the download at the enrichment.

Upload in enrichment is at 0,32Mb/s  (5Mb/15.49s). @oleurud it's 5Mb or 5MB
Upload outside enrichment is at 3.66MB/s (220MB/60s) = 0.45 Mb/s

That would be great if we could test a bigger enrichment, because maybe with an small dataset we could have some latencies issues.

**Comment by alasarr** [comment]
To speed up upload we can upload to a bucket and from the bucket to BQ. @josemazo works on a similar workflow and this approach gives us much better times

**Comment by alasarr** [comment]
>I'm not sure if we are using geojson because is the only format BQ admits,
@alejandrohall it only admits geojson and wkt, right?

**Comment by oleurud** [comment]
### Streaming API
Reading the docs from BQ, the faster way should be using the Streaming API https://cloud.google.com/bigquery/streaming-data-into-bigquery but using it from the client does not work fine:

This is the network usage using the default values from the Python client:
![image](https://user-images.githubusercontent.com/421145/69417575-37384700-0d19-11ea-9a04-a6ce6d6f1070.png)

If I increase the chuck rows, we can fail in quota errors easily (like `HTTP request size limit: 10 MB`) but the network usage is not enough:
![image](https://user-images.githubusercontent.com/421145/69432843-bee27d80-0d3a-11ea-8329-1b8331f8f0ae.png)

### Jobs
![image](https://user-images.githubusercontent.com/421145/69424096-10cdd800-0d28-11ea-8a65-4eb649608321.png)

One important thing is the real time uploading info is a half part of the total in the results. I show in the network manager how it is not using the network, but the job is not ended. I suppose BQ takes time to create the table in the dataset.

### Geometries vs other types
In my first comment, I was uploading a dataset of only integers (131 columns). The result was: 
- 220MB in a minute, so 3.66MB/s

In this case, I am working with a dataset with a geometry column and an integer one (the enrichment case). The result is:
- 80MB in ~150 seconds, so 0.5 MB/s.
- 300 MB in ~420 seconds, so 0.7 MB/s

I would like to check the last option, doing the upload to a bucket and then to BQ. But it has the pain of adding a bucket for each user or organization at least...

**Comment by oleurud** [comment]
### POINTS - 1 var - 11MB
variables 0
prepare 3.8
upload 26.0
query 0.6
download 25.1
data append 0


### POINTS - 130 vars - 11MB
variables 0
prepare 3.8
upload 29.6
query 1.0
download 324.1
data append 0


### POLYGONS - 1 var - 600MB
variables 0
prepare 37.4
upload 759.8
query 0.5
download 33.9
data append 0


### POLYGONS - 130 vars - 600MB  [WIP]
variables 0
prepare 38.3
upload 638.7
query 0.8

**Comment by alasarr** [comment]
I've just implemented the upload via GCS. It's a good improvement for big datasets it's 2.45x faster. For me, it's reasonable since we're uploading complex polygons.

### POINTS - 1 var - 11MB
Variables 0
Prepare 4.1
Upload 20.8 (4.6 GCS + 16.1 BQ)
Query + download 23.205592155456543

###  POLYGONS - 1 var - 600MB
Variables 0.29
Prepare 38.25
Upload 309.1 (70.89 GCS +  238.1 BQ)
Query + download 24.6

**Comment by alasarr** [comment]
I've successfully run an enrichment with all the Pitney Bowes POIs. 23M.

### POINTS - 1 var - 1.6GB
Variables 1
Prepare 614
Upload 519 (294 GCS + 223 BQ)
Query + download 1539

**Comment by alasarr** [comment]
Improvements with the Storage API: https://github.com/CartoDB/cartoframes/issues/1257

### POLYGONS - 50 vars - 600MB 
Total time = 756s = 12 minutes
Without storage API it was 1082s.
Download has been improved from 282s to 25.8s. 11 times faster 

Breakdown:

2019-12-02 14:43:47,585 - CARTOframes - DEBUG - prepare_variables in 1.97 s
2019-12-02 14:45:05,574 - CARTOframes - DEBUG - _prepare_data in 77.99 s
2019-12-02 14:45:05,632 - CARTOframes - DEBUG - Uploading to GCS
2019-12-02 14:45:58,582 - CARTOframes - DEBUG - Importing to BQ from GCS
2019-12-02 14:50:14,127 - CARTOframes - DEBUG - upload_dataframe in 308.49 s
2019-12-02 14:53:21,960 - CARTOframes - DEBUG - _execute_enrichment in 187.02 s
2019-12-02 14:53:21,961 - CARTOframes - DEBUG - **enrich_polygons in 576.35 s**
2019-12-02 14:53:46,647 - CARTOframes - DEBUG - to_dataframe in 25.82 s
