### ISSUE TITLE
Unable to select highest value in a dataset with histogram widget

### ISSUE THREAD

**Issue by makella** [CartoDB/cartoframes#1223]
hello!

When using a histogram widget, I'm unable to select the highest value in the histogram when filtering a range.

I'm mapping a earthquake dataset and there is one value with mag 8:
<img width="391" alt="Screen Shot 2019-11-20 at 10 38 16 AM" src="https://user-images.githubusercontent.com/1566273/69263186-0d98e780-0b82-11ea-8e11-715227c429fe.png">

When I try and select the highest range of values, I don't get that value, you'll see that I am trying several different range selections to see if I can grab it:
![hist_max](https://user-images.githubusercontent.com/1566273/69263356-61a3cc00-0b82-11ea-8cdb-b9898ed37389.gif)

There are other times when it says that I have the highest value selected, but it isn't on the map and the other labels of `7.5` for the rest of the histogram, I'm not sure how to explain:
![hist_max_2](https://user-images.githubusercontent.com/1566273/69263644-f4446b00-0b82-11ea-9954-4d05ed34fd3d.gif)

Here is the map to play around with:
- Colab ("Map 2")
  - https://colab.research.google.com/drive/1qeCqda5DtHtijvgngp5_nuirHYu2tXW-#scrollTo=wdPsix6V0pl-
- Published Map
  - https://cartoframes.carto.com/kuviz/718dfc8b-c0ac-49c4-aee0-e3c7b5ac953a

**Comment by Jesus89** [comment]
Fixed in https://github.com/CartoDB/airship/pull/676

**Comment by jdgodchaux** [comment]
@Jesus89 @cmongut @elenatorro @Mmoncadaisla Just had a conversation with the customer mentioned in https://github.com/CartoDB/support/issues/2412 and was wondering when to expect this updated. Will this wait for the release of the CARTOframes v1.0.2 or will this be available sooner than that?

**Comment by elenatorro** [comment]
Hi @jdgodchaux 👋 This was an Airship bug that was fixed here https://github.com/CartoDB/airship/pull/676 and should be working fine now :)

Airship fixes can be added in the last cartoframes version automatically, so If there's any other issue, please let me know and we'll work on that :) Thanks!
