### ISSUE TITLE
Rename `set_default_credentials` to `set_session_credentials`?

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#1225]
When using `set_default_credentials` right now I was momentarily confused about whether this sets the credentials on my system and that I would have to use another method to set the credentials for my current session.

It made me wonder if we should rename `set_default_credentials` to `set_session_credentials` to clearly describe that the credentials being set are being used for the Python session that the function is being called within. I almost expect `set_default_credentials` to set credentials in a way that can be used in other sessions similar to what happens with `Credentials(...).save()`.

@Jesus89 what do you think?

**Comment by Jesus89** [comment]
I see your point. I think we should improve the documentation to make this clear. However, using `set_session_credentials` can be confusing because of the `session` parameter in the credentials instance. Another name like `set_credentials` could be also not explicit enough.

I will think about it, but it would be nice to see how other libraries solve this.

**Comment by andy-esch** [comment]
Good point about `session`. I think I like the approach of making sure the documentation is clear but I'm also curious if a better name/method exists out there :)

**Comment by cmongut** [comment]
I don't have a strong opinion about this. I have checked some libraries with two different patterns:

- Client creation that will be used for every action.
- Environment variable with a token or credentials.

I understand the issue between `session` and `default` but I wouldn't think about changing the naming until we get more feedback about it.

**Comment by Jesus89** [comment]
OK, let's close this for now, and reopen it if we have a proposal from product :)
