### ISSUE TITLE
decode_geom=True not returning shapely.geometry type

### ISSUE THREAD

**Issue by alexsroth** [CartoDB/cartoframes#1230]
In `cartoframes==1.0b5`, the `decode_geom=True` parameter for `Dataset.download()` is returning a WKB type, rather than the expected `shapely.geometry` type. 

**example notebook:** https://colab.research.google.com/drive/14eOqiQpvch0Rga46sN5b4r02aKNC9kqU

![image](https://user-images.githubusercontent.com/29546714/69430935-a8213400-0d04-11ea-84a6-dfa0370dcc12.png)

**Comment by alasarr** [comment]
@alexsroth it should be fixed at the new beta version with the new Object CartoDataFrame.

**Comment by Jesus89** [comment]
![](https://user-images.githubusercontent.com/2227572/70130789-78b5e400-1681-11ea-8c67-d97820907afd.png)
