### ISSUE TITLE
How to implement cartodb_id at CARTOframes

### ISSUE THREAD

**Issue by alasarr** [CartoDB/cartoframes#1231]
Right now, what we're using is to set cartodb_id as the index of the CartoDataFrame.

It has some special uses cases where it could be strange. At the following example, we're returning a CartoDataFrame with a different index. 

![image](https://user-images.githubusercontent.com/1161870/69431743-9f4a5580-0d38-11ea-9268-d92054bc2019.png)

For me it has the following issues:

- We're modifying the index of the DataFrame, the user could have their current workflow based on an index and we're changing it.

- The index could even have valuable information. If they, for example, created a special index for access to the data. For example a data

![image](https://user-images.githubusercontent.com/1161870/69432773-9e1a2800-0d3a-11ea-853b-fc78ab28f6f7.png)

From Pandas's [getting started guide](https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html)
![image](https://user-images.githubusercontent.com/1161870/69519627-cd0ee480-0f5a-11ea-81a7-e3e490dbe27b.png)

- The user will expect an index of dataframe starts in 0.

- It gives the sensation we're not respecting user's data, we're being very invasive here

Solution: 

I know lots of time cartodb_id is a pain, but it's something our platform needs, I'll make it explicit as we already have at our tables, a CartoDataFrame should have a `cartodb_id`. It will make our life easier and the users will understand what is happening. If they want to remove the column they will do it.

**Comment by alasarr** [comment]
@arredond @giuliacarella @andy-esch @alejandrohall @djfan @mbforr @josemazo @cayetanobv feedback?

**Comment by cmongut** [comment]
I wouldn't touch the original index for sure. I would only add an extra column if it's adding information to the user, not because it will make our life easier.

@andy-esch thoughts?

**Comment by josemazo** [comment]
For CARTOframes being more Pandas-like, it should behave like reading a CSV file: adding all the columns to the DataFrame, event the `cartodb_id`. If you want `cartodb_id` to be the DataFrame index, you should indicate it using an `index_col`-like parameter. Also, the documentation should say that `cartodb_id` starts at 1 because is a Postgres index.

**Comment by jorisvandenbossche** [comment]
I agree you ideally shouldn't change the index silently as is now the case (eg even if you have a index with strings or datetimes, it gets replaced with the integer 1, ..n).

The most explicit is probably to include a `cartodb_id` column when reading from CARTO, as mentioned above. And I suppose you can then also potentially use it if present when writing to CARTO? (if the column doesn't violate the constraints like no duplicated values).

For the actual (original) index of the DataFrame: the default in most pandas IO methods is indeed to include the index by default as a column (eg `to_csv` has a `index=True/False` parameter that defaults to True, `to_sql` has the same). So doing that here as well would probably be most consistent. 
We are actually just dealing with this as well in GeoPandas: https://github.com/geopandas/geopandas/pull/1059. Currently, the `GeoDataFrame.to_file` (the function that can write to any file format supported by GDAL) does not write the index of the DataFrame, loosing this information. In that PR we are adding support for writing the index, but with a slight deviation from pandas' defaults. We only write the index if it is a "non-default" index (basically if it has a name, and potentially also if it has a different dtype), to avoid writing unnecessary data to the file.

**Comment by alasarr** [comment]
Assigned to @Jesus89 for the implementation

**Comment by Jesus89** [comment]
Yes, there is a bug when the index column changes, but it's because we are not uploading the index of the DF to the table as a cartodb_id. Now it only uploads the index as cartodb_id if the `cdf.index.name` is `"cartodb_id"`. So if we rename the index it works:

![](https://user-images.githubusercontent.com/2227572/69655713-70edb280-1077-11ea-98ed-01569fc04a49.png)

![](https://user-images.githubusercontent.com/2227572/69655722-7519d000-1077-11ea-8ccf-64a5bff9c891.png)

I recap here info about the `cartodb_id` and the Panda's index:

- `cartodb_id`: it must be a number (it can be 0 or neg AFAIK, but the automatic Postgres index starts in 1 by default). Every "cartodbfied" table contains that column. There is also an issue in the Dashboard because tables without cartodb_id are not shown.
- `Pandas index`: it can be numeric, but also string, DateTime, etc. The name of the column can be None.

I agree it's more explicit to use the cartodb_id as a column, but we can have more situations than this one. Also, the user should provide an index_label (by default is None) to store the index in carto, but how can we know that this was the index once we download the data?

Let's explore some use cases:
- Download data from carto:
    - Does the "cartodb_id" exist in the table:
        - Yes: map "cartodb_id" as df.index
        - No: use default df.index
- Upload data to carto:
    - Does the "cartodb_id" exist in the DataFrame:
        - Yes:
            - It's a column: check if valid (number, unique), else No:
            - It's the index: check if valid (number), else No:
        - No: use default cartodb_id
- Geocoding: this runs in the carto platform and then downloads, so it's the same as case 1 (for DF) and 2.
- Isolines: this requires a cartodb_id always to perform the job.

I'll think a bit more about it to try to provide a "more related to pandas" way of managing the index, delegating the final decisions to the user.

**Comment by Jesus89** [comment]
Hi. I have implemented an API similar to how pandas manages CSV. I have also refactored the upload process, and now you can upload dataframes without geometry (selective cartodbfy). These are the changes in terms of API:

- Added "index_col" and "decode_geom" in "read_carto/from_carto". The user can set the index of the dataframe from an existing column called "index_col". By default is None.

- Added "index" and "index_label" in "to_carto". By default, as a difference with "to_csv", is False. It is set to True, it tries to upload the index as a column in the table. First, it uses the "index_label" for the column name, if this is not specified, it tries to use "index.name". If finally, this value is None it raises an exception.

- I have removed the "convert" method from the CDF, so now the geometry decoding is done in the "set_geometry" method.

I'll show you an example. Let's begin with a simple object with a custom index:

![](https://user-images.githubusercontent.com/2227572/69744893-58e26580-1141-11ea-979e-b4c2c26fd988.png)

After "to_carto" without extra params it uploads the data to a table, without the index column:

![](https://user-images.githubusercontent.com/2227572/69745429-79f78600-1142-11ea-8998-a207203a3324.png)

![](https://user-images.githubusercontent.com/2227572/69745446-8085fd80-1142-11ea-8593-7a2a4f318db9.png)

And if "index" param is provided:

![](https://user-images.githubusercontent.com/2227572/69745504-9abfdb80-1142-11ea-8609-d0759772c4cd.png)

![](https://user-images.githubusercontent.com/2227572/69745510-a01d2600-1142-11ea-9194-5ef42f052364.png)

Then, in the "from_carto" method, by default, it downloads the table with all the columns, and if the user wants to restore the index, it can pass "index_col"

![](https://user-images.githubusercontent.com/2227572/69745667-f2f6dd80-1142-11ea-9db7-0ddbd8c13531.png)

Finally, if the user has a geometry, the data is uploaded to a "cartodbfied" table, in this case we can set the index as the "cartodb_id", but this is always controlled by the user.

![](https://user-images.githubusercontent.com/2227572/69746207-10787700-1144-11ea-9c10-928a79334d3c.png)

![](https://user-images.githubusercontent.com/2227572/69746220-140bfe00-1144-11ea-8fd6-13bc6bad4d06.png)

**Comment by jorisvandenbossche** [comment]
@Jesus89 looks good! 
One remark, based on the images, when a user does `from_carto(..., index_col='my_index')`, you should also ensure that the name of that column is used as the index name (in the picture it seems that this name is lost)

**Comment by alasarr** [comment]
Looks good to me! +1 @jorisvandenbossche comment about the index

**Comment by Jesus89** [comment]
Thanks, @jorisvandenbossche. I'm removing the name on purpose to be like the default pandas index (name=None), but it makes sense to keep then name as index.name, so I will change it.

**Comment by jorisvandenbossche** [comment]
FWI, I don't think that is the default of pandas:

```
In [36]: df = pd.DataFrame({'a': [.1, .2, .3], 'index': [1, 2, 3]}).set_index('index') 

In [37]: out = df.to_csv()  

In [38]: print(out)
index,a
1,0.1
2,0.2
3,0.3


In [39]: pd.read_csv(StringIO(out), index_col='index')
Out[39]: 
         a
index     
1      0.1
2      0.2
3      0.3
```

So the name gets preserved both in outputting as when reading in (when `index_col` is specified). 
I suppose the `index_label=None` default means to use the name of the index if it has one, not to set the name to None (so you can use that argument to overwrite an existing name, or to provide a name if the index has no name).

**Comment by Jesus89** [comment]
Yep, it's not the default when you use "set_index" but when the default index is used, which name is None (I might not express myself quite well :P).

So now the behavior is the same as pandas. And yes, if `index_label=None` it uses the `index.name` if exists.

**Comment by Jesus89** [comment]
Closed via https://github.com/CartoDB/cartoframes/pull/1265
