### ISSUE TITLE
source_id missing on isolines

### ISSUE THREAD

**Issue by alasarr** [CartoDB/cartoframes#1233]
If isolines are created from a dataset without cartodb_id, the source_id column is missing. So it's not possible to match the isochrones with the original geodataframe.

![image](https://user-images.githubusercontent.com/1161870/69435785-834ab200-0d40-11ea-991c-48e3fc3e1655.png)

```
from cartoframes.data.services import Isolines

iso = Isolines()
# 3 minutes by car isolines (3*60 secs)
cdf_iso = iso.isochrones(cdf_stores, [3*60], mode='car').data
```
```
cdf_iso.head()
```

![image](https://user-images.githubusercontent.com/1161870/69435867-a37a7100-0d40-11ea-9af9-e43c7745f6df.png)

If I add a cartodb_id it works fine:
```
cdf_stores['cartodb_id'] = cdf_stores.index
```

Could be fixed directly by:  https://github.com/CartoDB/cartoframes/issues/1231

**Comment by Jesus89** [comment]
Hi @elenatorro, I remember to see something about "source_id" in your PR. Could you check if this is fixed with your changes?

**Comment by elenatorro** [comment]
I added a `source_id` by index, but I don't think it fixes this issue and it requires further work and testing.

**Comment by Jesus89** [comment]
It seems that this issue is solved. We can re-open it if the bug appears again.
