### ISSUE TITLE
Additional options to `dataset.download()`

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#1235]
Sending a full dataset to disk is great, but it'd be really useful to offer the user more options, like so:

- download location: oftentimes people would just want `./`
- include_geom=True|False. We should make it easier to include the geometry along with the data
- variables list: User can specify the variables they would like included in the data download. `None` means get all variables.

So the signature would look something like:

```python
def download(self, path=DEFAULT_LOCATION, include_geom=False, variables=None):
    pass
```

cc @arredond

**Comment by Jesus89** [comment]
Done in `to_csv`: file_path, sql_query, add_geom
