### ISSUE TITLE
CartoDataFrame ignoring CRS

### ISSUE THREAD

**Issue by alasarr** [CartoDB/cartoframes#1237]
The following snippet loses the crs definition of the original GeoDataframe
```python
from cartoframes import CartoDataFrame
from geopandas import GeoDataFrame
from shapely.geometry import box
gdf = GeoDataFrame([{'id': 1, 'geometry': box(1, 1, 2, 2)}])
gdf.crs = 'epsg:4326'
cdf = CartoDataFrame(gdf)
type(cdf.crs)
# NoneType
```

Related with: https://github.com/CartoDB/cartoframes/pull/1130#issuecomment-557695873

**Comment by Jesus89** [comment]
This also happens in the GeoDataFrame:

![](https://user-images.githubusercontent.com/2227572/69803855-8846b000-11dd-11ea-9fb1-4f26d73fa2ca.png)

However, I will fix it in the CDF.

**Comment by Jesus89** [comment]
Done in https://github.com/CartoDB/cartoframes/pull/1265
