### ISSUE TITLE
Should `dataset.subscribe()` automatically subscribe to geography table too?

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#1242]
When subscribing to a new dataset and be able to do spatial operations (e.g., enrichment) with it with the recommended geography table, a user has to do this:

```python
dataset.subscribe()
# click yes/buy/etc.
Geography.get(dataset.geography).subscribe()
# click yes/buy/etc.
```

The first time I encountered this workflow, I didn't know about the second step and kept getting bigquery errors in enrichment about not having data access to one of the tables (it turned out it was the geography table but I thought it was the data table and subscribe didn't work).

This was the error:

```
NotFound: 404 Not found: Dataset carto-do-public-data:acs was not found in location US
```

I see a few ways to help the user understand what's going on:

1. Subscribing to a dataset automatically subscribes to the geography table too
2. When enriching, give an error that it's not possible to enrich with the given dataset if the user has not already subscribed to the geography table
3. Give a message when subscribing to the dataset that its not possible to enrich if the user does not also subscribe to the geog dataset too...

**Comment by cmongut** [comment]
Yeap, this should be improved but not a priority for now.

**Comment by Jesus89** [comment]
This is not required. Closing this
