### ISSUE TITLE
[DO - catalog] geography geom_coverage

### ISSUE THREAD

**Issue by oleurud** [CartoDB/cartoframes#1249]
For @arredond geography geom_coverage method should return something usable, because right now we are returning a binary (from PostGIS) as string.

His proposal is to return a shapely object:  
´´´
shapely.wkb.loads(geom, hex=True)
´´´

We have thought about returning a Map, but he told me that the user could want to use it for other things, not only visualize it.

**Comment by Jesus89** [comment]
`geom_coverage` returns a map. It internally applies the geom decoding to shapely.

However, we can add a flag to return the GeoDataFrame instead (disabled by default to keep the current behavior):

```py
geom_coverage(raw_data=True)
```

What param name does work better for you?
