### ISSUE TITLE
review behavior of histogram widget bars and values with one feature

### ISSUE THREAD

**Issue by makella** [CartoDB/cartoframes#1252]
hello!

I'm noticing that when there is one feature, whether through filtering other widgets and/or in the current view, that the histogram widget doesn't seem to know exactly what to do.

in the screenshot below, I have histogram widgets on numeric attributes in a polygon dataset. when I have one polygon in view, the histogram loses the bars and all values across the x-axis are labeled with the value of the polygon:

<img width="881" alt="Screen Shot 2019-11-26 at 2 01 09 PM" src="https://user-images.githubusercontent.com/1566273/69673246-23f9e400-1057-11ea-90df-a2088758c05f.png">

if this is better in Airship, let me know!

**Comment by Jesus89** [comment]
cc @VictorVelarde

**Comment by VictorVelarde** [comment]
Ok, we'll have a look once we integrate Histograms, see https://app.clubhouse.io/cartoteam/story/66024/widget-histogram-widget-i-readonly

**Comment by VictorVelarde** [comment]
Not happening anymore or no longer relevant?
