### ISSUE TITLE
[DO - enrichment] column data types support

### ISSUE THREAD

**Issue by oleurud** [CartoDB/cartoframes#1259]
Comes from https://github.com/CartoDB/cartoframes/issues/1243 

We need to do 2 improvements in enrichment:
- weighted average
- support enrichment with no numeric values

Some things/tips to take into account: we could return the area intersection of the polygons allowing to do the aggregation locally.

**Comment by Jesus89** [comment]
Dup https://github.com/CartoDB/cartoframes/issues/1297
