### ISSUE TITLE
[Guides] - Review guides

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartoframes#1262]
- [x] Review all the guides final versions together in the developer center, fixing style issues and making changes when needed.
- [x] Add missing links
- [x] Add HTML links in Introduction section
    - [ ] change links & copies

PR: https://github.com/CartoDB/cartoframes/pull/1266
Developer Center: http://cartoframes-guides-review.developers.carto-staging.com/developers/cartoframes/guides/Introduction/

**Comment by Jesus89** [comment]
Done in https://github.com/CartoDB/cartoframes/pull/1266
