### ISSUE TITLE
Publish privacy levels enhancements

### ISSUE THREAD

**Issue by alasarr** [CartoDB/cartoframes#1286]
**UPDATED**:

- [x] Use 'privacy': 'link' and 'privacy': 'password' in the output.
- [x] Require password param, so the user must set it to None to explicitly disable the password.
- [x] Update the documentation

**Comment by Jesus89** [comment]
Kuviz does not allow private maps. You have:
- Public maps
- Protected maps (with password)

We should add this information to the documentation (guides?)

**Comment by Jesus89** [comment]
In the publish method, the password param must be required

**Comment by cmongut** [comment]
Check `update_publication` method to see if we can use the same behaviour in the publish method. Maybe we need to add an `if_exists` parameter as in datasets.

**Comment by cmongut** [comment]
I am renaming this issue to focus on the privacy level. This issue could be divided in three steps:

- [ ] About communicating the privacy level to the user, we will use the same levels as in builder: "link" and "password".
- [ ] About the default privacy level, we need to get some feedback from DS. We will come back here later.
- [ ] Update the documentation

**Comment by Jesus89** [comment]
Cool. I'm going to update the ticket description.

**Comment by alasarr** [comment]
My two cents: If the method is named publish it's clear what we're doing is making it public. 

To address the privacy I think we should have something like.

```python
map = Map(...)
map.to_carto('name') # Save the map in CARTO, it should appear in the dashboard and it will be privated
map = map.from_carto('name') #Get a map from CARTO
map.publish()
```

@cmongut I think you should check with CS.

**Comment by cmongut** [comment]
We could think about doing something like that if possible but we can't today.
We can't make a kuviz private, it needs research from backend.
We can't generate a map from a kuviz because it wasn't thought for that. We can think about saving the code that generated the kuviz as metadata to do this (this comes to my mind thanks to something that @andy-esch shared with me for the dashboard :))

**Comment by Jesus89** [comment]
Cool. I think it's a good approach to take into account in the future. But in summary for this ticket, these are the tasks (I'm going to update the ticket description too):

- Use 'privacy': 'link' and 'privacy': 'password' in the output.
- Require `password` param, so the user must set it to None to explicitly disable the password.
- Update the documentation

With that done we can complete the ticket. For the private Kuviz proposal and other improvements related to map publications, we should create new tickets and prioritize them in the future.

**Comment by alasarr** [comment]
Yes, of course, my idea is for a future implementation.

**Comment by Jesus89** [comment]
Hi @cmongut, could you confirm that the goals of the ticket in the description are correct?

**Comment by cmongut** [comment]
Hey, let's do that. After talking with the data scientists, the approach makes sense for them although publishing a map will be a bit harder from now on. We can make the `password` param optional when we are able to make kuvizs private.

**Comment by Jesus89** [comment]
Awesome! Thanks for taking the time to validate this proposal :D
