### ISSUE TITLE
CartoDataFrame vs Composition vs Helpers

### ISSUE THREAD

**Issue by alasarr** [CartoDB/cartoframes#1287]
We need to make the decision on this sprint about the final API we're going to provide for 1.0

Related with https://github.com/CartoDB/cartoframes/issues/1260 and https://github.com/CartoDB/cartoframes/pull/1130#issuecomment-557695873

cc: @oleurud @Jesus89

**Comment by Jesus89** [comment]
This is duplicated, so we can close this one.
