### ISSUE TITLE
Homogenize Popups/Legends/Widgets API

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/cartoframes#1300]
### Legend + LegendList

```py
# Using Legend class
Layer(
    legend=Legend('color-category', title='...', description='...')
)

# Using dict
Layer(
    legend={
        'type': 'color-category'
        'title': '...',
        'description': '...'
    }
)

# Using dict (+multi type)
Layer(
    legend={
        'type': {
            'point': 'color-continuous-point',
            'line': 'color-continuous-line',
            'polygon': 'color-continuous-polygon'
        },
        'title': '...',
        'description': '...'
    }
)

# Using Legend class + dict
Layer(
    legend=Legend({
        'type': 'color-category'
        'title': '...',
        'description': '...'
    })
)

# Using LegendList class
Layer(
    legend=LegendList([Legend('color-category', title='...', description='...')])
)

# Using list
Layer(
    legend=[Legend('color-category', title='...', description='...')]
)

# It uses singular `legend` for one and multiple legends
```

### Widget + WidgetList

```py
# Using Widget class
Layer(
    widgets=Widget('formula', value='viewportSum($amount)', title='...', 'description': '...')
)

# Using dict
Layer(
    widgets={
        'type': 'formula',
        'value': 'viewportSum($amount)',
        'title': '...',
        'description': '...'
    }
)

# Using Widget class + dict
Layer(
    widgets=Widget({
        'type': 'formula',
        'value': 'viewportSum($amount)',
        'title': '...',
        'description': '...'
    })
)

# Using WidgetList class
Layer(
    widgets=WidgetList([Widget('formula', value='viewportSum($amount)', title='...')])
)

# Using list
Layer(
    widgets=[Widget('formula', value='viewportSum($amount)', title='...')]
)

# Using helper methods
Layer(
    widgets=formula_widget(value='viewportSum($amount)', title='...')
)

# It uses plural `widgets` for one and multiple legends
```

### Popup

```py
# Using Popup class
Layer(
    popup=Popup({
        'hover': ['$name'],
        'click': ['$name', '$pop_max']
    })
)

# Using dict
Layer(
    popup={
        'hover': ['$name'],
        'click': ['$name', '$pop_max']
    }
)

# Using dict attrs
Layer(
    popup=Popup({
        'hover': [{
            'title': 'Name',
            'value': '$name'
        }],
        'click': [{
            'title': 'Name',
            'value': '$name'
        }, {
            'title': 'Pop max',
            'value': '$pop_max'
        }]
    })
)

# Hover and Click popups are contained in the same class
```

## Proposal

The API allows multiple ways of creating UI components: classes, dicts, lists, helper methods, etc.
Every UI components have a different API. The goal is to simplify and homogenize the API.

- Use helper methods to create UI components in the map
- Use the plural for the Layer params: legends, widgets, popups
- Do not expose: Source, Style, Legend, LegendList, Widget, WidgetList, Popup
- Expose:
    - Map
    - Layer
    - legends
        - basic_legend
        - size_bins_legend
        - size_category_legend
        - size_continuous_legend
        - color_bins_legend
        - color_category_legend
        - color_continuous_legend
    - widgets
        - basic_widget
        - formula_widget
        - category_widget
        - histogram_widget
        - animation_widget
        - time_series_widget
    - popups
        - click_popup
        - hover_popup

### Legend

```py
from cartoframes.viz.legends import color_category_legend, size_category_legend

Layer(
    legends=color_category_legend(title='...', description='...')
)

Layer(
    legends=[
        color_category_legend(title='...', description='...'),
        size_category_legend(title='...', description='...')
    ]
)
```

### Widget

```py
from cartoframes.viz.widgets import formula_widget, category_widget

Layer(
    widgets=formula_widget('amount', title='...')
)

Layer(
    widgets=[
        formula_widget('amount', title='...'),
        category_widget('collisiontype', title='...')
    ]
)
```

### Popup

```py
from cartoframes.viz.popups import click_popup, hover_popup

Layer(
    popups=click_popup('name', title='...')
)

Layer(
    popups=[
        hover_popup('name', title='...'),
        click_popup('name', title='...'),
        click_popup('pop_max', title='...')
    ]
)
```

cc @makella @cmongut

**Comment by cmongut** [comment]
Nice work @Jesus89!

I think it's easy to see the improvement. My only doubt is about using helpers instead of dictionaries, what was the rationale?

**Comment by Jesus89** [comment]
Hi @cmongut. In Python is generally more pleasant to work with functions + params than dictionaries: smaller characters, easier to read/write, autocomplete, better documentation.

**Comment by andy-esch** [comment]
Hey @Jesus89, looks great overall -- I love the consistent syntax and would feel comfortable if it froze like this right now.

About namespace/module. I'm not sure I'm comfortable importing these elements from `viz`. What about a submodule like:
```python
from cartoframes.viz.elements import category_widget, category_legend, click_popup
```

Or maybe specific submodules for each one (`cartoframes.viz.widgets`) that is more in line with how we organize helper layers (`cartoframes.viz.helpers`). I agree it puts some burden on the user, but it also guides them on how things are structured.

And to be honest, I feel a little scared about hiding away/limiting users by templating the functionality in helpers. There is a lot of power in customization that I feel like we still haven't unlocked in the helpers so I don't want to hide away too much the classes the helpers are based upon.

**Comment by cmongut** [comment]
@Jesus89 LGTM! I agree with @andy-esch about moving them to submodules namespaces.

@andy-esch could you add an example about your concerns?

**Comment by Jesus89** [comment]
Hi @andy-esch, @cmongut.

This is related to #1301, which completes the Viz API changes.

I thought yesterday about putting everything in `cartoframes.viz` because the user can import it in one line. It makes sense when you are using style helpers, for example `from cartoframes.viz import Layer, color_category_style`, but maybe it was not a super good idea, so having structured namespaces seems better.

The point of removing the classes from the API is to guide the user to use only one API, so they are used only internally. However, we can keep them by now, and evaluate their deletion when we review altogether.

**Comment by elenatorro** [comment]
We all agree it's ok to remove the `widgets`, `helpers`, `popups` namespaces, and after talking with @makella we also prefer to keep everything under the `viz` namespace as @Jesus89 suggests.

Nice! If there's any other thing, remember we can keep adding comments to each task :)
