### ISSUE TITLE
Improve CartoDataFrame documentation

### ISSUE THREAD

**Issue by alasarr** [CartoDB/cartoframes#1307]
We need to improve the reference: https://carto.com/developers/cartoframes/reference/#heading-CartoDataFrame

- [x] Add example for `to_carto`

- [x] Description for `set_geometry` and `set_geometry_from_xy`

- [x] Remove from doc `astype`, `merge`, `dissolve`, `explode`

**Comment by elenatorro** [comment]
Although this should be really easy to add, I did a quick test on `develop` branch and I got some sphinx errors when building the docs, they're really easy to solve cause they're related with the format (for example: `Bullet list ends without a blank line; unexpected unindent.`).

When testing it, please remember to run them locally to see if there's any format error and check the final result :) The instructions to run docs locally are [here](https://raw.githubusercontent.com/CartoDB/cartoframes/develop/docs/developers/documentation.rst).

**Comment by Jesus89** [comment]
Elena, can we mark somehow the functions to skip the doc generation for the Dev Center reference?

**Comment by elenatorro** [comment]
Sure! it should be done by using `:exclude-members: method_name` in the `.rst` files input files. There's an example in the [cartodataframe.rst](https://github.com/CartoDB/cartoframes/blob/develop/docs/includes/cartodataframe.rst) file where we're skipping the `convert` method.
