### ISSUE TITLE
Explain what is CartoDataFrame at Quickstart

### ISSUE THREAD

**Issue by alasarr** [CartoDB/cartoframes#1308]
- [x] We should explain something like CARTOframes is built on top of GeoPandas to guarantee compatibility between the two libraries. CartoDataFrame is an extension of [GeoDataFrame](http://geopandas.org/reference/geopandas.GeoDataFrame.html) so all operations available in a GeoDataFrame are available. 

- [x] When geocoding is done tell that the instance received is a CartoDataFrame.

- [x] Save the enrichment at CARTO to display how to save data in CARTO (to_carto).  Display the map using the CARTO's table, download using CartoDataFrame.from_carto('table'), display the map using the CartoDataFrame. 

I think it's the main object at the library and it deserves to be explained at the quick start.

**Comment by elenatorro** [comment]
About the third point, in my opinion is a bit complicated cause it involves **three** steps to do something that can be done in just **one**.

An alternative would be to:

1. Display the map directly from the `cdf`
2. Use `to_carto` to save the data
3. Explain you can directly use the table name to create the visualization
4. Explain you can use `from_carto` to download the table

What do you think?
