### ISSUE TITLE
Download OpenData

### ISSUE THREAD

**Issue by alasarr** [CartoDB/cartoframes#1309]
Cannot download an opendata datasets:
```
Geography.get('carto-do-public-data.usa_carto.geography_usa_state_2015').download()
```

It looks we're looking at the wrong path (customers):
```
Not found: Table carto-do-customers:alasarr.view_usa_carto_geography_usa_state_2015
```

**Comment by alasarr** [comment]
That would be great if we could set the file_path as a parameter.

The credentials parameter is a little bit confusing for me. Why is it there? Just to allow to download a dataset using another credential?

**Comment by alasarr** [comment]
The doc should be updated too. We're not doing `Download Geography data as a pandas DataFrame locally.` We're downloading it as a CSV with the column in WKT, right?

**Comment by oleurud** [comment]
It seems like we are considering them as private. 

> The credentials parameter is a little bit confusing for me. Why is it there?

To check if you have permissions over the Dataset / Geography. It works with `set_default_credentials` 

> file_path

Easy to add

> The doc should be updated too. We're not doing Download Geography data as a pandas DataFrame locally. We're downloading it as a CSV with the column in WKT, right?

Ok, and yes, I think so

**Comment by alasarr** [comment]
@mbforr has reported that issue from a customer.

**Comment by Jesus89** [comment]
Closed via https://github.com/CartoDB/cartoframes/pull/1311

**Comment by alasarr** [comment]
Guys, a couple of small ideas, not something required for the beta7. 

1) Can we make file_path a required parameter
2) Instead of download, how about to rename it to `to_csv`?
