### ISSUE TITLE
matplotlib and pako not found

### ISSUE THREAD

**Issue by alrocar** [CartoDB/cartoframes#1310]
I ran locally on a fresh venv `pip install cartoframes==1.0.0-beta6` and I found a couple of errors:

- While running the `visualize_your_data_guide_workflow` example, there's a `pako is not defined` error.
- While printing the histogram of a Variable, `matplotlib` is not found.

cc. @Jesus89 for triage.

**Comment by makella** [comment]
@alrocar this is the same issue I was having when we were writing the guides also heard from @orrholly that she was experiencing with beta 6.

**Comment by makella** [comment]
I should also mention, to narrow it down, it is related to the Layout at the end of the guide: https://carto.com/developers/cartoframes/guides/Visualization/#compare-variables-with-a-layout

**Comment by Jesus89** [comment]
- `matplotlib` is an optional dependency. I'll add more info in the exception to guide the user to install this extra dep.
- `pako` (the library to unzip the geojson) is loaded from the cdn: https://cdnjs.cloudflare.com/ajax/libs/pako/1.0.10/pako_inflate.min.js. I can not reproduce this issue, so I think it could be related to a punctual error with this URL.

**Comment by cmongut** [comment]
@oriolbx I think you have got this error recently. Could you check if you get every time you install it?

**Comment by alrocar** [comment]
@Jesus89 would it make sense to add `pako` to the local bundle instead of using the CDN?

**Comment by oriolbx** [comment]
I will try it @cmongut !

**Comment by Jesus89** [comment]
Good suggestion @alrocar, let's add it to `https://libs.cartocdn.com/cartoframes/dependencies/`

**Comment by Jesus89** [comment]
I have uploaded the lib to our CDN: https://libs.cartocdn.com/cartoframes/dependencies/pako_inflate.min.js, so we will use this from now on.
