### ISSUE TITLE
[DO] - A user without subscriptions can not enrich open data

### ISSUE THREAD

**Issue by cmongut** [CartoDB/cartoframes#1314]
It seems a user can not enrich open data if they haven't subscribed to a dataset before. The error seems to be that Dataset.get_all return None instead of a list.

![image](https://user-images.githubusercontent.com/711025/70142185-f5a08800-1698-11ea-9528-736ff763d683.png)

**Comment by oleurud** [comment]
The check for public data is before that... I am going to check it

**Comment by oleurud** [comment]
I have checked with a user with DO access, without subscriptions and the first variable of the dataset `Dataset.get('acs_sociodemogr_496a0675')` and it works

**Comment by cmongut** [comment]
👍 
Thank you @oleurud! I am checking it with the user to see if we can get the specific dataset.

**Comment by Jesus89** [comment]
It seems that this is directly related to this line: https://github.com/CartoDB/cartoframes/blob/develop/cartoframes/data/observatory/catalog/repository/entity_repo.py#L45.

I'm not sure why it's returning None instead of []

**Comment by oleurud** [comment]
umm, in this case, using a private dataset without having subscribed any one, is going to fail. Checking it

**Comment by oleurud** [comment]
Yes, there is a bug in the described situation but using private datasets. It is solved in https://github.com/CartoDB/cartoframes/pull/1315

**Comment by Jesus89** [comment]
Closed via https://github.com/CartoDB/cartoframes/pull/1311
