### ISSUE TITLE
Review usage of `DatasetInfo` specially in geocoding

### ISSUE THREAD

**Issue by alrocar** [CartoDB/cartoframes#1318]
DatasetInfo makes use of an internal API `api/v1/viz` which is an API for the `visualizations` table, a metadata table for the user postgres tables.

The `visualizations` table is filled some times from the Ghost Tables Manager. This is an async process that might produce errors of the type `table xxx does not exist` when trying to use `api/v1/viz` if a table has not been added to `visualiztaion` by GTM.

This has happened in the `Geocoding` service in an on-premises environment, where GTM is not enabled.

There's a point in the geocoding process in which we do this:

```python
update_table(
            table_name=tmp_table_name,
            credentials=self._credentials,
            new_table_name=table_name,
            privacy='private'
        )
```

Since the table is not in the visualizations metadata table it returns an error and the process cannot finish.

We could just rename the table with a plain SQL query.

In any case, we should tackle this issue at a higher extent. See related [PAIN](https://github.com/CartoDB/product/issues/336).

cc @Jesus89 for triage.

**Comment by alrocar** [comment]
Related [issue](https://github.com/CartoDB/onpremises/issues/842)

**Comment by Jesus89** [comment]
Thanks for the detailed report.

Yes. We can try to rename the table without the DatasetInfo module for this specific case.

I would split this method `update_table` in two methods `rename_table` and `update_privacy`.
