### ISSUE TITLE
"Undo" for cc.data_augment

### ISSUE THREAD

**Issue by michellemho** [CartoDB/cartoframes#132]
Problem:

After running cc.data_augment( ) to get Data Observatory measures for a table, it's rather cumbersome to undo this and get your original table back. Currently, Cartoframes suggests that the user create a copy of the table first and use the new copy instead. But you still need to delete the table from CARTO using cc.query('DROP TABLE...') or using the CARTO interface if you want to redo the augmentation.

Suggested solution:

Within the data_augment function, create a copy of the table, appended with something like "_cartoframe_augment" to indicate it's a copy. If a copy was already created, then overwrite. Then, try to augment the copy. If, for whatever reason, the original table (and therefore copy table) already contains the Data Observatory column, then there is an exception. In the case of an exception, the copy table is dropped and the original table is returned.

```python
def data_augment(self, table_name, metadata):
        try:
            with open(os.path.join(os.path.dirname(__file__),
                                   'assets/data_obs_augment.sql'), 'r') as f:
                augment_functions = f.read()
            self.sql_client.send(augment_functions)
        except Exception as err:
            raise Exception("Could not install `obs_augment_table` onto user "
                            "account ({})".format(err))
        df = self.read(table_name)

        # make a copy of table_name
        self.write(df, '{}_cartoframe_augment'.format(table_name), overwrite=True)
        table_copy = '{}_cartoframe_augment'.format(table_name)

        # augment with data observatory metadata
        augment_query = '''
            select obs_augment_table('{username}.{tablename}',
                                     '{cols_meta}');
        '''.format(username=self.username,
                   tablename=table_copy,
                   cols_meta=json.dumps(metadata))
        try:
            resp = self.sql_client.send(augment_query)
            table_name = table_copy
       # handle exception where the column already exists in the table
        except:
            self.query('DROP TABLE {}'.format(table_copy))

        # read full augmented table
        return self.read(table_name)
```

Notes:
- Sending queries to write and delete tables might slow down the data_augment process.
- In the case of an exception and the copied table being dropped and the original table returned, then a warning message should be issued as well (I will need to look into how to add this). The message can say something along the lines of "Columns [data observatory measure(s)] already exist in table_name, original table is returned in output and has not been altered in CARTO"

**Comment by andy-esch** [comment]
This isn't a problem anymore with the current implementation of data obs enrichment.
Process there:
- pull down augmented data
- write to carto with cc.write
