### ISSUE TITLE
Remove python 2.7 support

### ISSUE THREAD

**Issue by cmongut** [CartoDB/cartoframes#1324]
Let's remove the support for python 2.7 in CARTOframes.

The main reasons are that python 2.7 will not be supported in 2020 https://pythonclock.org/ and some libraries, like geopandas, have already removed their support in their latest versions.

Checking some metrics https://pypistats.org/packages/cartoframes, only 1-2% of the cartoframes downloads come from python 2 :)

**Comment by jorisvandenbossche** [comment]
The upcoming 0.7 version of GeoPandas will indeed be py3 only, and the latest released version of pandas already is py3 only. So I would also recommend already dropping python 2.7 support in Cartoframes (certainly given the 1.0 release is only targetted for early next year)
