### ISSUE TITLE
Check geometry types before enrichment

### ISSUE THREAD

**Issue by arredond** [CartoDB/cartoframes#1330]
Sometimes I've accidentally tried to enrich points with the `enrichment.enrich_polygons` method. This doesn’t automatically raise an error, but instead fails when calculating the area of the points, returning a division by zero error from BigQuery.

This error is strange for a user that doesn't know the SQL being run in BQ, and it's also a waste of time since the geometries must first be uploaded to BQ for the query to fail.

A nice feature would be to check the geometry types in CF (plus, this can't be done in BQ since there's no `ST_GeometryType` function, or similar). The cost is quite low since Shapely Geometry objects already have a `geom_type` property. Here's an example of how that could be done:

```python
def _check_geometry_types(geom_series, geom_types):
    """
    Checks that all elements of a GeoSeries belongs to
    one or several geometry types.
    
    - geom_series: A GeoPandas GeoSeries (such as gdf.geometry)
    - geom_types: A single string defining a Shapely geometry type,
    or a list-like object containing said strings.
    """
    if isinstance(geom_types, str):
        geom_types = [geom_types]
        
    geom_types = set(geom_types)
    
    unique_geom_types = geom_series.geom_type.unique()
    invalid_geom_types = set(unique_geom_types) - geom_types
    if invalid_geom_types:
        raise ValueError(f'Invalid geometries of type {invalid_geom_types} for types {geom_types}')
    else:
        return None

# Example usage - polys_gdf is a GeoDataFrame containing Polygons and MultiPolygons
_check_geometry_types(polys_gdf.geometry, ['Polygon', 'MultiPolygon']) # Passes
_check_geometry_types(polys_gdf.geometry, 'Polygon') # Fails
```

Obviously just a dummy example and the actual implementation could be quite different.

IMHO, we should allow the following geometry types:
- `enrich_points`: _only_ `Point`s (`MultiPoint`s would require aggregation)
- `enrich_polygons`: `Polygon`s and `MultiPolygon`s

**Comment by Jesus89** [comment]
This will be done in the Enrichment API, so this ticket is superseded. Closing it.
