### ISSUE TITLE
Duplicate metadata checks in CF and backend

### ISSUE THREAD

**Issue by arredond** [CartoDB/cartoframes#1331]
Right now, both CARTOFrames and backend are checking that certain fields are filled in the metadata:

- [CARTOFrames](https://github.com/CartoDB/cartoframes/blob/1c8f222107c9776e0029a39bd3896fa75f4f0f89/cartoframes/data/observatory/catalog/utils.py#L43): Only checks that `subscription_list_price` is filled in and returns an Exception otherwise.
- [Backend](https://github.com/CartoDB/cartodb/blob/694fa6f303323fee96b0ab0f4c25f7e0393be318/app/controllers/carto/api/public/data_observatory_controller.rb#L143): Checks that `estimated_delivery_days`,  `available_in` and `subscription_list_price` are not null. In [a latter step](https://github.com/CartoDB/cartodb/blob/694fa6f303323fee96b0ab0f4c25f7e0393be318/app/controllers/carto/api/public/data_observatory_controller.rb#L47), also checks that `estimated_delivery_days` is zero.

IMO, it makes sense to avoid redundancies and only perform this check in one place, and this should be the backend (which is also more complete). Therefore, the check in CF could be removed.

**Comment by Jesus89** [comment]
Yes, this was added to the client before the backend check was available, but now it makes sense to remove the client checks.

**Comment by arredond** [comment]
Yup @Jesus89 , I looked at this last week with @oleurud but we forgot to create an issue to keep track, so I just made this for the future :)

**Comment by arredond** [comment]
@andy-esch just discovered [some additional duplicate checks](https://github.com/CartoDB/cartoframes/blob/2d55dcfaff60fbc42955870b47f3a5ed990d27a4/cartoframes/data/observatory/catalog/entity.py#L120) during the download

**Comment by Jesus89** [comment]
:+1:

**Comment by Jesus89** [comment]
Closed via https://github.com/CartoDB/cartoframes/pull/1391
