### ISSUE TITLE
Change "docs/*" branches settings

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartoframes#1337]
Related issue https://github.com/CartoDB/cartoframes/issues/1161
Related PR in the dev center https://github.com/CartoDB/developers/pull/666

* Block "docs/*" branches from being removed
* Block "docs/*" branches direct push, a PR should be open against them before

**Comment by Jesus89** [comment]
Done!

**Comment by elenatorro** [comment]
Done by @Jesus89 🚀
