### ISSUE TITLE
Style API

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartoframes#1345]
Epic https://github.com/CartoDB/cartoframes/issues/1343

### 1. Helper-Like Parameters

* [x] Add style `value` parameter
* [x] Add style `type` parameter
    - [ ] Check valid types

```python
Layer(
    'starbucks_points',
    style=Style(
        value='revenue',
        type='size_continuous'
    )
)
```

### 2. Legends-Like Parameters

These parameters are used by default in the by default generated Legend. If custom legends are provided along with any of these parameters, they'll be added as a **Default Legend** on top of the rest of the legends.

* [x] Add style `title` parameter
* [x] Add style `description` parameter
* [x] Add style `footer` parameter

### 3. Style-Property Parameters

* [x] Use style-property parameters

```python
Layer(
    'table_name',
    style=Style(
        type='size_continuous',
        value='revenue',
        color='white',
        opacity=0.2,
        stroke_color='blue',
        size= [20, 80]
    )
)
```

### 4. Style Helpers

* [x] Create a style helper by type
    - [x] `size_continuous_style`
    - [x] `color_continuous_style`
    - [x] `color_bins_style`
    - [x] `size_bins_style`
    - [x] `color_category_style`
    - [x] `size_category_style`
    - [x] `animation_style`

- [ ] When not using a Style helper, define the default legend to avoid showing, for example, 'color' as a description of the legend item

```python
Layer(
    'table_name',
    size_continuous_style(
        'revenue',
        color='white',
        opacity=0.2,
        stroke_color='blue',
        size= [20, 80]
    )
)
```

### 5. Animation

- [x] Default animation

* If animate is set, then a user will get a time-series widget by default. 
* If animate is set but the widget is overwritten, the animation will be present the custom widgets won't be animated

### ⚠️ 6. Docs!

This is an implicit task: update documentation

- [ ] Guides
- [ ] Reference
- [ ] Examples

**Comment by Jesus89** [comment]
I would add only Step 4. Using the Style class adds duplicity and also implies to duplicate the functionality for each type. In Step 2, this should be done at the Layer level.

**Comment by elenatorro** [comment]
Yes, let's start doing first the style helpers 👍I think point 5 is also important (and 6 of course but that's implicit 😛)
