### ISSUE TITLE
automatically order by when styling by a column

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#135]
Mapnik draws based on the order in the table, so if styling by values, the highest ones should be drawn on top. This should happen behind the scenes, but a `kwarg` for ordering should be available for the user to overwrite the default behavior.

For example, if a user enters this:
```python
cc.map(layers=Layer('acadia_biodiversity', color='simpson_index')
```

Internally, the query should be
```SQL
SELECT * FROM acadia_biodiversity ORDER BY simpson_index ASC
```

cc @makella

**Comment by Jesus89** [comment]
Old API. This is already covered in the new API
