### ISSUE TITLE
[ Visualization API Redesign ] - Layers

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartoframes#1350]
Epic #1343
Related issue "Homogenize Popups/Legends/Widgets API" #1300

### 1. Change layers helper internal behaviour using the new implementation

* [x] size_continuous_layer
* [x] color_continuous_layer
* [x] color_bins_layer
* [x] size_bins_layer
* [x] color_category_layer
* [x] size_category_layer
* [x] cluster_size_layer
* [x] animation_layer

### ⚠️ 2. Docs!

This is an implicit task: update documentation

- [ ] Guides
- [ ] Reference
- [ ] Examples

**Comment by makella** [comment]
Just want to add a note that this also involves defining the default behavior for components inside of each helper style... for example, we want to explore things like which components are set to true by default (all of them or only legend?), also, what is the workflow for the time-series widget that gets added when a user animates in a helper if `widget=False` -- we have ideas but want to see it in action before making a final decision

**Comment by elenatorro** [comment]
Note: we're thinking about removing the layer helpers since having style helpers would be enough for what we want to accomplish
