### ISSUE TITLE
datset.geom_coverage doesn't show map

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#1361]
The docs for dataset.geom_coverage imply that a map will be shown when calling the property `geom_coverage`:

https://github.com/CartoDB/cartoframes/blob/b4b569543357d231c29cd282ad3f1e128035d065/cartoframes/data/observatory/catalog/geography.py#L132-L136

What is returned instead is the ewkb of the coverage.

**Comment by Jesus89** [comment]
Hi @andy-esch. This `dataset.geom_coverage()` works OK. The documentation you are pointing is referring to the `geography` instance and it's true that there is a bug in the docstring.
