### ISSUE TITLE
Consider changing local URLs in docs to full HTTP links?

### ISSUE THREAD

**Issue by andrewbt** [CartoDB/cartoframes#1363]
In the Developer Center, numerous examples are shown with specific local references to the file structure of this repository:
<img width="829" alt="Screen Shot 2019-12-13 at 7 42 45 PM" src="https://user-images.githubusercontent.com/2013555/70840521-cbf60800-1de0-11ea-8d16-80d4c1813cd2.png">

For ease of the copying/pasting beginner user, who likely doesn't have this whole repo cloned, nor should they need to clone it, and since `pandas.read_csv` will natively accept an HTTP link, what if we were to change these code snippets to use the Raw github content link:

```
stores_df = pandas.read_csv('https://raw.githubusercontent.com/CartoDB/cartoframes/develop/examples/files/starbucks_brooklyn_geocoded.csv')
```

Would save users a step in quickly following the examples. We fixed a similar problem of including full working links with CARTO.js examples in the Developer Center in the past: CartoDB/developers#324

**Comment by Jesus89** [comment]
Done here: https://github.com/CartoDB/cartoframes/pull/1420/commits/70e31cc49e75b590f2204aa00ca25734387a535c as part of https://github.com/CartoDB/cartoframes/pull/1420.
