### ISSUE TITLE
Catch and show errors from BQ

### ISSUE THREAD

**Issue by oleurud** [CartoDB/cartoframes#1364]
Sometimes, an error happens in BigQuery and the user can not see anything about it. I think, we can show the messages from BQ to the client to help them to understand what is going on.

**Comment by Jesus89** [comment]
Is this related to https://github.com/CartoDB/cartoframes/issues/1246?

**Comment by oleurud** [comment]
> Is this related to #1246?

No, it isn't. The idea of the #1246 is to track unexpected errors from BQ. I suppose we can close it in the next iteration since we will have enough users using it.

**Comment by Jesus89** [comment]
:+1:
