### ISSUE TITLE
Add Data Enrichment e2e tests

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/cartoframes#1365]
- Enrich points
- Enrich polygons
- Download to df
- Download to file

Extra:
- Refactor Data Enrichment unit tests

cc @alasarr @oleurud

**Comment by oleurud** [comment]
The objective is to ensure the behavior of enrichment functions, taking into account:
- public and private data
- points and polygons
- dataframe (+ geom column) and geoDataframe as inputs
- aggregation:
  - default
  - none
  - custom for all
  - custom by variable
- filters

The idea is to make enrichment/download of a few rows. 

So, the list of tests:
- [ ] points enrichment
  - [ ] public data with default values
  - [ ] private data with default values
  - [ ] private data with filters
- [ ] polygons enrichment
  - [ ] public data with default values
  - [ ] private data with default values
  - [ ] aggregation none + 2 filters
  - [ ] aggregation custom for all
  - [ ] aggregation custom by variable
- [ ] download
  - [ ] public data to csv
  - [ ] private data to dataframe

**Comment by oleurud** [comment]
:rocket:
