### ISSUE TITLE
[Data Services] check quota before using third party service

### ISSUE THREAD

**Issue by oleurud** [CartoDB/cartoframes#1370]
At least in the isolines service, if the user does not have enough quota, the service is not working as expected and we are returning an unexpected error. 

We need to validate quotas before calling third party service in Data Services, to avoid unexpected error messages in the process.

**Comment by oleurud** [comment]
@jgoizueta I have a doubt in geocoding service. The idea of this issue is to validate if the user current quota is bigger than the estimated and raise an error otherwise. 

But, I see the estimated is calculated https://github.com/CartoDB/cartoframes/blob/develop/cartoframes/data/services/utils/geocoding_utils.py#L221-L222 
but in case of error in the geocoding query execution, you overwrite it https://github.com/CartoDB/cartoframes/blob/develop/cartoframes/data/services/geocoding.py#L414

Makes sense for you doing https://github.com/CartoDB/cartoframes/pull/1372/files#diff-43cb6d0f45a5eee4f84203494bd23914R384-R390?

**Comment by jgoizueta** [comment]
I think it's nice to check for enough quota here and raise that error without running the geocoder.
But you're keeping the error handling showing the remaining/estimated quota, right? (because the quota may have been consumed between the CFs check and the actual geocoding execution).

**Comment by oleurud** [comment]
> But you're keeping the error handling showing the remaining/estimated quota, right? (because the quota may have been consumed between the CFs check and the actual geocoding execution).

Yes, I am. I am going to move the PR forward
