### ISSUE TITLE
Missing images in Developer center Quickstart Authentication section

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/cartoframes#1377]
In the the [Authentication -> Get your Master API Key](https://carto.com/developers/cartoframes/guides/Authentication/#get-your-master-api-key) section, there are two images, which are not correctly loaded:

<img width="627" alt="Screenshot 2019-12-17 at 15 08 55" src="https://user-images.githubusercontent.com/11177693/71002332-53908f00-20df-11ea-85a2-7e95fa8c5e96.png">

In the console, two 404 errors can be seen when trying to access to the images:

```
https://carto.com/developers/cartoframes/img/guides/credentials/api-keys.png 404 (Not Found)
https://carto.com/developers/cartoframes/img/guides/credentials/dashboard.png 404 (Not Found)
```

**Comment by cmongut** [comment]
It's already fixed
