### ISSUE TITLE
Map errors on Quickstart Publish and Share and  Quickstart Visualization sections

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/cartoframes#1379]
In the [Publish and share section of the Quickstart](https://carto.com/developers/cartoframes/guides/Quickstart/#publish-and-share-your-results) and in several maps from the Visualization section of the Quickstart ([add Layers to Map](https://carto.com/developers/cartoframes/guides/Visualization/#add-layers-to-a-map) and [Insights](https://carto.com/developers/cartoframes/guides/Visualization/#insights)) some of the maps are returning an error like the next one:

<img width="816" alt="Screenshot 2019-12-17 at 15 22 25" src="https://user-images.githubusercontent.com/11177693/71003888-9fdcce80-20e1-11ea-80f1-8e4d046bfbc3.png">

**Comment by cmongut** [comment]
It was already fixed :)
