### ISSUE TITLE
[revantage-admin] CARTOframes beta7 isoline viz helper palette not rendering

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartoframes#1382]
default

### Context

* [Zendesk ticket](https://carto.zendesk.com/agent/tickets/32535)
* `username` [revantage-admin](https://carto.com/superadmin/users/402929)
* `orgname` [revantage](https://carto.com/superadmin/organizations/1793)

This user is creating an isochrones map with CARTOframes v10b7. When the isolines are calculated—ie: [15*60] instead of something like [600]—and an isolines vis helper function is used, the isoline polygon is invisible.

### Steps to Reproduce

1. Create Python 3.6 environment (this is what client is using):
`python3.6 -m venv cf10b7py36`
2. Activate it:
`source cf10b7py36/bin/activate`
3. Install CARTOframes beta7:
`pip install cartoframes==1.0b7`
4. Install Jupyter notebook:
`pip install jupyterlab`
5. Run Jupyter notebook
`jupyter notebook`
6. Save a credentials file in virtual environment's project folder (test_creds.json)
6. Create a new notebook and run this script:

```python
from cartoframes.auth import set_default_credentials
from cartoframes.data.services import Geocoding
from cartoframes.data.services import Isolines
from cartoframes.viz.helpers import isolines_layer
import pandas as pd

set_default_credentials('test_creds.json')

gc = Geocoding()
df = pd.DataFrame()

df['carto_address'] = ['307 5th Ave, New York, NY 10016']
geocoded_df, info = gc.geocode(df, street="carto_address")
geocoded_df.head()

iso_service = Isolines()

# TEST 1
isochrones_df, isochrones_metadata = iso_service.isochrones(geocoded_df, [300,600,900], mode='walk')
isochrones_df.head()

isolines_layer(isochrones_df, palette='purpor')

# TEST 2
isochrones_df2, isochrones_metadata = iso_service.isochrones(geocoded_df, [15*60], mode='walk')
isochrones_df2.head()

isolines_layer(isochrones_df, palette='purpor')
```

### Current Result

**TEST 1** renders properly:

![Screen Shot 2019-12-17 at 2 09 29 PM](https://user-images.githubusercontent.com/1779444/71034653-2344f280-20d7-11ea-9ce2-08f98a6e5e6b.png)

**TEST 2** looks like the isochrone polygon exists because of the Pop-Up, but it is not visible:

![Screen Shot 2019-12-17 at 2 09 57 PM](https://user-images.githubusercontent.com/1779444/71034720-44a5de80-20d7-11ea-8f9a-d3faf1765209.png)

 
### Expected result

Isochrones will be visible even if this kind of notation is used to create them:
[15*60]

### Browser and version

Version 79.0.3945.79 (Official Build) (64-bit)

**Comment by ztephm** [comment]
Update: this is happening for single isochrones even if a non-calculated notation is used

```python
isochrones_df2, isochrones_metadata = iso_service.isochrones(geocoded_df, [600], mode='walk')
isolines_layer(isochrones_df2, palette='purpor')
```

![Screen Shot 2019-12-17 at 2 17 01 PM](https://user-images.githubusercontent.com/1779444/71035049-e88f8a00-20d7-11ea-8398-062929fcd99a.png)

There are no error messages in CARTOframes.

**Comment by Jesus89** [comment]
Hi @ztephm. I am able to reproduce the bug :)

It seems that it occurs when 1 or 2  range values are used, but not with 3 or more.

![](https://user-images.githubusercontent.com/2227572/71112093-16093000-21cb-11ea-958e-63116dbfd204.png)

![](https://user-images.githubusercontent.com/2227572/71112105-1acde400-21cb-11ea-83a3-2fb832b914de.png)

This is the VL output:

```
VM407 carto-vl.min.js:6 Uncaught TypeError: Invalid attempt to spread non-iterable instance
    at _nonIterableSpread (carto-vl.min.js:6)
    at _toConsumableArray (carto-vl.min.js:6)
    at Palette._getBestSubPalette (carto-vl.min.js:6)
    at Palette.getColors (carto-vl.min.js:6)
    at Ramp._getColorPalette (carto-vl.min.js:6)
    at Ramp._getPalette (carto-vl.min.js:6)
    at Ramp._applyToShaderSource (carto-vl.min.js:6)
    at carto-vl.min.js:6
    at Array.map (<anonymous>)
    at Opacity._applyToShaderSource (carto-vl.min.js:6)
```

I'll take a look tomorrow.

**Comment by Jesus89** [comment]
Hi @ztephm. I found and fixed two bugs:
- CartoColors: https://github.com/CartoDB/CartoColor/pull/43
- CARTO VL: https://github.com/CartoDB/carto-vl/pull/1419

This happens using 2 or fewer categories with PurpOr and CB_* palettes. The immediate solution is to use another palette different than PurpOr. In less than 1 week, CARTO VL will be released so this will be automatically fixed in CARTOframes.
