### ISSUE TITLE
Missing space in VariableFilter where clause construction

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#1390]
https://github.com/CartoDB/cartoframes/blob/e61ead03ee45af8651e5462ba95946e2cd0b0809/cartoframes/data/observatory/enrichment/enrichment_service.py#L329

If we add a space before the `AND` it _might_ take care of an error I get when trying to apply two VariableFilters:
```
[{'reason': 'invalidQuery', 'location': 'query', 'message': 'Syntax error: Missing whitespace between literal and alias at [32:65]'}]
```

Here's my code:

```python
enriched_data = enrich.enrich_polygons(
    polys,
    variables=dataset_vars,
    filters=[
        VariableFilter(
            Variable.get("date_range_star_d1bbce15"), "= 1567296000 "
        ),
        VariableFilter(dataset_vars[-1], " is not null "),
    ],
    aggregation={dataset_vars[-1].id: "ARRAY_AGG"},
)
```

If I add spaces around the filter condition in the VariableFilter it works just fine but when I remove the spaces that error shows up.

For example:

```python
# this works
    filters=[
        VariableFilter(
            Variable.get("date_range_star_d1bbce15"), "= 1567296000 "
        ),
        VariableFilter(dataset_vars[-1], " is not null "),
    ],
# this doesn't work
    filters=[
        VariableFilter(
            Variable.get("date_range_star_d1bbce15"), "= 1567296000"
        ),
        VariableFilter(dataset_vars[-1], "is not null"),
    ],
```

**Comment by Jesus89** [comment]
This could be solved with https://github.com/CartoDB/cartoframes/pull/1397.

cc @oleurud.

**Comment by oleurud** [comment]
:rocket: It should be solved. Take into account https://github.com/CartoDB/cartoframes/issues/1406

**Comment by cmongut** [comment]
@andy-esch could you check this issue has been solved?

**Comment by Jesus89** [comment]
Already solved
