### ISSUE TITLE
Developer Center missing reference and/or examples sections for versions 0.10, b01 and b02

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/cartoframes#1392]
The documentation of the Developer Center allows you to select the documentation of CARTOframes  version that you want to see.

However, for versions 0.10, 1.0b1 and 1.0b2 the documentation doesn't have the Reference or the Examples sections that are located at the [Readthedocs](https://cartoframes.readthedocs.io/en/v0.10.1/overview.html) (which was the old documentation):

![Screenshot 2019-12-19 at 09 31 00](https://user-images.githubusercontent.com/11177693/71157772-f7df1680-2242-11ea-9957-fb660e3b18df.png)

![Screenshot 2019-12-19 at 09 31 20](https://user-images.githubusercontent.com/11177693/71157779-fa417080-2242-11ea-825d-e820f7f1d169.png)

![Screenshot 2019-12-19 at 09 32 15](https://user-images.githubusercontent.com/11177693/71157793-fca3ca80-2242-11ea-9230-f014c25816cf.png)

Users that use the alpha or early beta versions can't see the the documentation on the Developer Center or the link to the old documentation.

On the other hand, the beta 3 documentation has the reference section that points to the readthedocs, but it doesn't have the examples section.

![Screenshot 2019-12-19 at 09 41 04](https://user-images.githubusercontent.com/11177693/71158151-b864fa00-2243-11ea-9769-06c12d513678.png)

**Comment by Jesus89** [comment]
This is expected because those sections were added after the 1.0b3. Closing this.
