### ISSUE TITLE
SUM aggregation using Points/Lines polygons

### ISSUE THREAD

**Issue by oleurud** [CartoDB/cartoframes#1393]
This issue comes from this one https://github.com/CartoDB/data-observatory/issues/558#issuecomment-567152462 where the full problem with enrichment and different geographies types is described. the problem will be tackled in the future.

But we have something to solve now. Right now, the polygons enrichment query with SUM aggregation looks like: 
```
SUM(
    enrichment_table.{column} * (
        ST_AREA(ST_Intersection(enrichment_geo_table.geom, data_table.{geo_column}))
        /
        ST_AREA(data_table.{geo_column})
    )
) AS SUM_{column}
```
With that, the problem happens when the DO geography is different from `Polygon` or `MultiPolygon`, the result of the enriched variables would zero.

I see 3 solutions:
- we could only make enrichment against polygons DO geographies (we should return and error with different geographies)
- for each variable, we could get the geography type, and when it is different from Polygon use:
```
SUM(enrichment_table.{column}) AS SUM_{column}
```
- we could eliminate the normalization by area in SUM aggregation

cc @arredond @alasarr

**Comment by alasarr** [comment]
I'd set the area normalization as a parameter. By default, I think it should be enabled, but users could decide if they want to remove it. 

When the area is 0 (points) we should just return the exception.

Thoughts @arredond @cmongut?

**Comment by arredond** [comment]
I agree @alasarr

**Comment by Jesus89** [comment]
This will be done in the Enrichment API, so this ticket is superseded. Closing it.

**Comment by andy-esch** [comment]
Hey all, not sure where to leave my comments but I have the following use case:

I have polygons and I want to enrich them with attributes for point geometries. For example, POIs that have number of visits and I want to get the sum of all visits for the polygons. What happens now is that I get null values, which is not my expectation.

Looking at the constructed query, I can understand why it happens that I get null values. My expectation is that I get a SUM for any type of enrichment, regardless of the geometry type of the enrichment table.

**Comment by andy-esch** [comment]
> When the area is 0 (points) we should just return the exception.

I agree this should return an exception, but only if the area normalization is set. I believe the default behavior for points should be 

```python
        return """
            SUM(
                enrichment_table.{column}
            ) AS {aggregation}_{column}
            """.format(
                column=variable.column_name,
                geo_column=_GEOM_COLUMN,
                aggregation=variable_agg)
```

**Comment by alasarr** [comment]
@cmongut that's important. If a user wants to enrich against a POIs datasets, something quite common they will get the exception.  For me it's a bug right now
