### ISSUE TITLE
Add "subscribed but not ready" message

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/cartoframes#1401]
From https://github.com/CartoDB/cartodb/pull/15315#issuecomment-567922122.

We need to add a message to show in the Download and Enrichment when the dataset/geography has been purchased, but it's not ready yet. We need to check the `instant-licensing` in the lib and another attribute (status:pending?) to detect that.

@cmongut could you help us with the content of the message?

**Comment by cmongut** [comment]
I understand this shouldn't happen but let's a message just in case:
"We are sorry, the data is not available yet. Try again later or send us an email to support@carto.com to know the status."

**Comment by Jesus89** [comment]
AFAIK the activation process is manually done. How long does it take on average?

This is an example of that situation:
```
dataset.subscribe() # -> Yes
dataset.download() # -> You are not subscribed :S
```

**Comment by Jesus89** [comment]
As we talked with @cmongut this is not a priority now.
