### ISSUE TITLE
Time-series widget filter doesn't apply selection

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/cartoframes#1412]
* It might be related to this issue: https://github.com/CartoDB/cartoframes/issues/1359
* Tested in beta7 and develop version.
* Reproduces in [this example](https://carto.com/developers/cartoframes/examples/#example-visualize-temperatures) 

When running the animation the map has the next geometries for the first buckets of the time-series widget:

<img width="963" alt="Screenshot 2019-12-24 at 16 18 24" src="https://user-images.githubusercontent.com/11177693/71418151-4ccac480-2669-11ea-915d-ca7db9ab64d0.png">

However, if I let the animation run and then select a range for the first bucket of the time-series widget, the animation doesn't change and keeps running:

<img width="991" alt="Screenshot 2019-12-24 at 16 17 55" src="https://user-images.githubusercontent.com/11177693/71418179-797edc00-2669-11ea-9f7f-eec950079b22.png">

The selection of the time-series widget is never applied, it doesn't matter if the animation is stopped or not.

**Comment by Jesus89** [comment]
@elenatorro could you check if this issue is solved?

**Comment by elenatorro** [comment]
This is fixed, but the example in the developer center is not updated. We're re-running all the examples in the developer center here https://github.com/CartoDB/cartoframes/issues/1473
