### ISSUE TITLE
Handle dataset price in subscription flow

### ISSUE THREAD

**Issue by cmongut** [CartoDB/cartoframes#1413]
There are going to be situations where we are not sure about the final price of a dataset.
For that reason, we need to show another subscription message in that case:

**Subscription message**
<h3>Data request</h3>
You are about to request the {type} <b>{id}</b>.
<br>Do you want to proceed?

**Confirmation message**
Thanks! We will contact you shortly to complete the subscription details.

**Comment by Jesus89** [comment]
Cool. Which is the condition to render this message? price == null?

**Comment by cmongut** [comment]
Yeap!
