### ISSUE TITLE
Contribute link on the dev center page is broken

### ISSUE THREAD

**Issue by cmongut** [CartoDB/cartoframes#1427]
![image](https://user-images.githubusercontent.com/711025/71592663-5ce31800-2b31-11ea-8e56-e095498046c8.png)

This link goes to https://carto.com/developers/cartoframes/support/contribute/ when it should go to https://github.com/CartoDB/cartoframes

**Comment by Jesus89** [comment]
The URL is fixed to /support/contribute for every project, so the solution is to add a `/support/contribute` section in our docs, like https://carto.com/developers/carto-js/support/contribute/ or https://carto.com/developers/carto-vl/support/contribute/.
