### ISSUE TITLE
Dataset does not exist when importing `tables` from `cartoframes.utils.table`

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#1437]
It looks like `Dataset` wasn't removed/renamed in:
https://github.com/CartoDB/cartoframes/blob/v1.0b7/cartoframes/utils/table.py

This causes an import error:

```
ImportError: cannot import name 'Dataset'
```

When doing this:
```
from cartoframes.utils.table import tables
```

cc @djfan

**Comment by Jesus89** [comment]
This file is not used anymore so we can remove it.

**Comment by andy-esch** [comment]
Is there similar functionality elsewhere?

**Comment by Jesus89** [comment]
I don't think so. We can add a new function in io/ to list all tables in an account. Could you add a ticket for the feature request? Thanks!
