### ISSUE TITLE
Add info about EPSG=4326 to the documentation

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartoframes#1440]
Related issue https://github.com/CartoDB/cartoframes/issues/1274

Context
======
This issue has been opened for a while: [Visualizing dataframe with non-EPSG:4326 CRS is failing silently](https://github.com/CartoDB/cartoframes/issues/1274) and for the current release we'll need to add this information in the documentation to let the users know, at least while it's not solved.

**Comment by Jesus89** [comment]
Closed in https://github.com/CartoDB/cartoframes/pull/1656
