### ISSUE TITLE
Change 'ranges' back to 'size'

### ISSUE THREAD

**Issue by makella** [CartoDB/cartoframes#1446]
@elenatorro as discussed, let's definitely change `ranges` back to `size` to keep consistency between styles and from previous versions for:
- [x] size_continuous_style
- [x] size_category_style
- [x] size_bins_style

thanks!!

**Comment by Jesus89** [comment]
For me, this is a bit confusing, because:
- We are using size as width in the color helpers
- Size is singular and people expect a number, not a list of number

**Comment by elenatorro** [comment]
* About `size` vs `width`:

    We've discussed this many times in the past. `width` is what we were using in VL, but we're using `size` cause it's common in other libraries and technologies and what users expect. It's not the same than `stroke_width` (which is `stroke_width` by convention). So `size` is the correct world 👍 

* About singular vs plural:

    Size doesn't need to be plural, IMO it's not confusing, but we could ask some users about it. The idea is to have the same parameter as in other helpers.

**Comment by Jesus89** [comment]
Yeap, my only concern is that we are using `size` for two different things depending on the helpers, and this could be confusing:
- color_bins_style(..., size=10, ...), color_category_style(..., size=10, ...),  color_continuous_style(..., size=10, ...)
- size_bins_style(..., size=[2,4], ...), size_category_style(..., size=[2,4], ...),  size_continuous_style(..., size=[2,4], ...)

**Comment by elenatorro** [comment]
Yes, I agree it's a possibility, but it's also to have different names for the same concept (size). I don't have any strong opinion, maybe we should ask some users. What's important is to have it well documented and with clear examples 👍

**Comment by cmongut** [comment]
👍 

We will check it today. What were we using before? In `size_continuous_layer` we had `range_max` and `range_min`, isn't it?

**Comment by elenatorro** [comment]
Yes, and it was also a bit inconsistent 🤔 maybe we can talk about this in today's viz meeting and make a decision (it's very easy and fast to change), what do you think? :)

**Comment by cmongut** [comment]
Oki, let's do that. Comments from a data scientist:

- `size_range` could work
- `range` is not intuitive
- `size` doesn't seem a range. It may let you think you have to pass a variable that gives you the size
- between `range` and `size` I would prefer to use range

I'll try to get more inputs

**Comment by cmongut** [comment]
+1 for `size_range`

Another data scientist brought the same param name to the table.
