### ISSUE TITLE
DeadlineExceeded: 504 Deadline Exceeded

### ISSUE THREAD

**Issue by oleurud** [CartoDB/cartoframes#1449]
A user reported us an error in a dataset download:
```
DeadlineExceeded: 504 Deadline Exceeded
```

It seems an error from BigQuery which is returned when:
- using the BigQuery Storage API and 
- a timeout happens: query timeout? connection timeout? another timeout? not sure, they talk about query timeout but it makes no sense for me (I need to investigate it more)

The solution for it would be setting the `timeout` parameter of the `read_rows` function https://github.com/CartoDB/cartoframes/blob/2e2cd40bb269585df8133868e446b145c5a5d42c/cartoframes/data/clients/bigquery_client.py#L134 (in the cases I have seen, other developers are setting values like 100 or even 1000 in the timeout (seconds) which seems very high). 

Right now, my objective is the check the use case of the client (I have never seen the error before) to know if it is a reproducible error or if it is a punctual error

**Comment by oleurud** [comment]
I have been trying to reproduce the error, but it was impossible to me.

I think it is related to network connection, I can not ensure since Bigquery is not documenting this error, but it is documented in other services like pubsub where they say:

> The request did not complete in the time  allocated. This can be caused by network issues from the client to the  server, and it can also occur rarely on the server. On this error, the  server may or may not execute the operation requested. 

and 

> Typically the client would retry the operation

In the issue tracker from Google I found that thread, where I get the idea of BQ is waiting for something from the client but it does not happen in a specific time. https://issuetracker.google.com/issues/71808731

My last try will be to limit my network bandwidth and try several downloads...

**Comment by cmongut** [comment]
[It can also be related with Windows](https://github.com/googleapis/google-cloud-python/issues/9135)

**Comment by oleurud** [comment]
I have been doing a download for 1 hour (0.5 MB connection) and it does not fail

**Comment by cmongut** [comment]
Hey, I was able to reproduce this issue in Windows using the `.to_csv()` method.

I found the solution in the [previous link](https://github.com/googleapis/google-cloud-python/issues/9135) I posted. The solution is to add the timeout parameter to the `read_rows()` method of the bq storage client:

```
reader = self.bq_storage_client.read_rows(            
                          bigquery_storage.types.StreamPosition(stream=session.streams[0]),
                          timeout = 1000)
```

IDK which would be the right number for that param but it's working now. @oleurud could you make some tests and add the timeout you find best?

**Comment by oleurud** [comment]
I am looking for a windows computer. We have 2 options:
- use the timeout parameter: right now, the timeout is not set and we will add it one, so, for example, if we add a timeout of 1 hour, I suppose a proper request that needs more than that could fail (I am going to validate it)
- catch the exception and do the fallback to BigQuery lib: we need to ensure the `DeadlineExceeded` is a BQ Storage API error
- catch the exception and retry the request with the timeout

**Comment by cmongut** [comment]
After doing the acceptance with @oleurud, we found that the fallback to the BigQuery lib makes the download around 6x slower.

We are going to add a huge timeout (7200 = 2h) to the storage API instead and it will work in linux and windows.

**Comment by Jesus89** [comment]
Closed in https://github.com/CartoDB/cartoframes/pull/1507
