### ISSUE TITLE
Dataset subscription is not performed

### ISSUE THREAD

**Issue by alasarr** [CartoDB/cartoframes#1454]
I've tried to subscribe to a dataset, the workflow doesn't throw any error but the subscription is not actually done.

![image](https://user-images.githubusercontent.com/1161870/72011837-f2318b00-325a-11ea-9d02-8ef5d45b6c70.png)

**Comment by alasarr** [comment]
It happens with the account `alasarr` that belongs to `geographica` organization. With a team account it works fine.

cc: @gonzaloriestra

**Comment by gonzaloriestra** [comment]
Instant licensing was disabled for that user, so it's the expected behavior
(regular licensing + 3 delivery days). It's enabled now.

**Comment by alasarr** [comment]
Yeah! I've received the email.
