### ISSUE TITLE
Export a vector-based image from a notebook

### ISSUE THREAD

**Issue by connerpate** [CartoDB/cartoframes#1460]
I'm using cartoframes in a Google Colab notebook to plot geodata. What I would _like_ to be doing with these maps is exporting them as static, high-quality images (preferably .eps or .svg) to be used in design software like Adobe Illustrator. Is there a way to make this happen? 

Ideally, I'm looking for in-line export functionality, like Plotly's "_fig.write_image(file_name)_" that I can use to send a .svg image directly to a Google Drive folder.

I read through this thread, which seemed similar (but not exactly the same):
https://github.com/CartoDB/cartoframes/issues/499

If I understand correctly, carto-print seems to need a Carto API key. It also doesn't seem to allow you to specify the type of image. Similarly, the map.publish() functionality requires an API key, and I don't know what the export options are once it's been published.

Do either of those options (or any other options I've not considered) allow for what I'm trying to do? If so, do any of them allow for it without requiring an API key and/or going through Carto published maps?

**Comment by cmongut** [comment]
Hi @connerpate, thanks for using CARTOframes.

You can export a static image thanks to the browser. Let me show you how:

![download_image](https://user-images.githubusercontent.com/711025/72270613-b9603000-3625-11ea-9eb5-507e1494deaf.gif)

Does it work for you?

**Comment by connerpate** [comment]
Hi @cmongut,
Your image is cut off on the top and is in Spanish, so I'm not _sure_ what I'm seeing, but I'm guessing you're using the option that in English would be "Save Image As...".
This does not work for me. The only image type option in this workflow is "PNG image", and I specifically need either a) a very high resolution image, or b) ideally a _**vector-based image**_ to work with. A .PNG is neither of those things - that's why I was exploring solutions like map.publish() native to Cartoframes, in the hope that Carto had developed a means of exporting a vector-based image.
Thank you,
Conner

**Comment by cmongut** [comment]
Hi @connerpate,

I have updated the image so it appears in english, sorry about that.

Unfortunately, we don't have an option to export it in a high resolution format right now and it's not planned to be added it soon.

Thank you

**Comment by Jesus89** [comment]
This is not possible with the current implementation (using VL). But we will save the proposal for a possible future implementation using WebSDK. cc @VictorVelarde
