### ISSUE TITLE
Add notification message in readthedocs to bring users to the developer center

### ISSUE THREAD

**Issue by cmongut** [CartoDB/cartoframes#1470]
The developer center is where the documentation will be updated. We need to show a warning message to readthedocs users to let them know about this.

Warning message suggestion: “To get the latest documentation, check CARTO’s developer center. You will be able to check guides, the reference and examples.”

Where to place it: at the top of every page if possible

**Comment by elenatorro** [comment]
Hi! I've added this `version` to test the warning message: https://cartoframes.readthedocs.io/en/readthedocs/

It's not possible to modify the current versions cause they come from the tags. It's not possible either to create a new branch from these tags with the same name, cause readthedocs add a suffix to the name of the new branch when loaded.

This means it's not possible to overwrite the content or add the warning to every version. What I think the best is to set the main page to https://cartoframes.readthedocs.io/en/readthedocs/ (maybe with a better name, like: `deprecated-documentation`) and keep v0.10.0 and lower versions.

What do you think? I'm pinging @andy-esch to see if he can help us with that :)

Thanks!

**Comment by Jesus89** [comment]
It should be nice if we redirect /stable/ to that page.

**Comment by andy-esch** [comment]
@elenatorro, you are proposing that all v1.0bx pages redirect to https://cartoframes.readthedocs.io/en/readthedocs/ ? I also like @Jesus89's idea of just doing a redirect.

For helping users, we should change the nav: `stable` and `latest` should point to developer center (either the page Elena made or redirect as Jesus suggests), and the v0.x links should stay as they are.
<img width="292" alt="Screen Shot 2020-01-15 at 11 15 39 AM" src="https://user-images.githubusercontent.com/1041056/72450618-ab76f000-3788-11ea-8957-cf6db6214380.png">

(I'll also remove the docs for prototype-table-objects)

For redirects, looks like that's an option within readthedocs:

<img width="642" alt="Screen Shot 2020-01-15 at 11 09 27 AM" src="https://user-images.githubusercontent.com/1041056/72449950-846bee80-3787-11ea-9646-208ec866793b.png">

**Comment by elenatorro** [comment]
> you are proposing that all v1.0bx pages redirect to `/readthedocs`?

No :) These versions shouldn't leave in `readthedocs` anymore, mainly cause as they're beta versions, they'll be removed at some point and now, they should only be available in the developer center. My proposal is to keep v0.* versions in readthedocs as they are, as you also suggest.

> for helping users, we should change the nav: stable and latest should point to developer center

I like this idea! The only issue with that is: if a user enters in readthedocs looking for an older version, it'd be impossible to him/her cause will be redirected automatically to the developer center. But maybe that's what we want!

Let's list the options we have:

**Option 1**:
_(Set `https://cartoframes.readthedocs.io/en/readthedocs/` to `https://cartoframes.readthedocs.io/en/deprecated-documentation/`)_

- Show the warning message in `https://cartoframes.readthedocs.io/en/deprecated-documentation/`
- Redirect stable and latest to `https://cartoframes.readthedocs.io/en/deprecated-documentation/`

**Option 2**:
- Redirect stable and latest to the developer center

Please let me know which option do you like the most, or make any suggestions :)

I have another question: should we do this step now, or at the same time as the release?

Thanks!

**Comment by Jesus89** [comment]
Build fixed: https://cartoframes.readthedocs.io/en/v0.10.1/

**Comment by Jesus89** [comment]
We can not redirect to the Dev Center, so the stable redirects to v0.10.1, which contains a warning message to go to the new doc in the Dev Center.

https://cartoframes.readthedocs.io/en/stable/
