### ISSUE TITLE
Manage kuviz quota in CARTOframes

### ISSUE THREAD

**Issue by cmongut** [CartoDB/cartoframes#1471]
There is a [PR](https://github.com/CartoDB/cartodb/pull/15367) to make kuviz maps count in the plan limits.

Right now, testing that PR, we are showing an error with an ‘Access denied’ message. We should show a message like this one instead: “You have reached the limit for the number of maps you can create with your account. Upgrade your account or delete some of your previous maps to be able to create new ones.”

**Comment by oleurud** [comment]
Can a user delete a Kuviz?

**Comment by oleurud** [comment]
For the record: we decided not to do anything in CF by now since the user can do it from the dashboard.

**Comment by Jesus89** [comment]
I'll create a ticket with more information about that, just to keep track of it.

**Comment by Jesus89** [comment]
:rocket:
