### ISSUE TITLE
Update copies in developer center

### ISSUE THREAD

**Issue by cmongut** [CartoDB/cartoframes#1472]
**Overview**

- [x] Replace Introduction text

> CARTOframes is a Python package for integrating CARTO maps, data observatory, data services and analyses into data science workflows. It also allows you to share your work from your work environment.
> 
> To understand the fundamentals of CARTOframes, read the guides. To go deeper, read the full reference API. To check snippets that go straight to the point, check the examples. To view the source code, browse the open-source repository in GitHub and contribute. Also, if you see something is not working or you have any doubt, check the different support options.

- [x] Replace reference example code

```
from cartoframes.auth import Credentials, set_default_credentials
from cartoframes.data.observatory import Enrichment

set_default_credentials('creds.json')
enrichment = Enrichment()

enriched_df = enrichment.enrich_points(
    df,
    variables=['total_pop_3cf008b3']
)
```

**Guides**

- [x] Replace introduction text --> Fixed in #1479 

> Use these guides to learn about integrating CARTOframes into your data science workflows. Working inside of a Jupyter Notebook, the guides walk through installation, visualization, authentication, data enrichment and location data services.
> 
> If you are looking for more detailed use cases, check our examples.

- [x] Replace `visualization layers` term with `visualization styles` --> Fixed in #1479 

**Examples**
--> Moved to https://github.com/CartoDB/cartoframes/issues/1473

- ~~[ ] In the `Load data from CARTO Table` example, add tip about visualizing it directly.~~
- ~~[ ] In the `Load data from CARTO SQL Query` example, add tip about visualizing it directly.~~

**Comment by elenatorro** [comment]
Merged 🚀
