### ISSUE TITLE
Feature request: list tables in user account

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#1482]
Listing tables in a user account is a perennial feature request. We used to have it (#1437) but it was removed when `Dataset` disappeared.

Listing datasets allows users to programmatically explore tables in their account instead of requiring them to know the names or copy and paste them from the dashboard.

Related
* https://github.com/CartoDB/cartoframes/issues/1437
* https://github.com/CartoDB/cartoframes/issues/353

cc @Jesus89 @djfan

**Comment by djfan** [comment]
something like this but more pythonic? 
```
# old version cf

ap_tables = ap.query("SELECT * FROM pg_catalog.pg_tables where tablename like '%appearhere%';")
```

**Comment by Jesus89** [comment]
We could add a new method `cartoframes.list_tables(credentials)`. Do you want a list of strings or something different like a DataFrame? @andy-esch @djfan

**Comment by andy-esch** [comment]
I think a simple table list is good. If I recall correctly, big query's python client does something like that and I've never craved more than that. I could see an argument for more information, like privacy, etc. just like is listed in the dataset dashboard. My guess is that would be of limited value for most users and that they could get that information other ways programmatically if they wanted it.

**Comment by Jesus89** [comment]
Closed by https://github.com/CartoDB/cartoframes/pull/1649
