### ISSUE TITLE
Basemap() label options in cc.map() not responding as expected

### ISSUE THREAD

**Issue by mehak-sachdeva** [CartoDB/cartoframes#149]
The cc.map() function does not respond to BaseMap(labels=None) option as expected.
It should display a basemap with no labels.
Current behavior:
![screen shot 2017-06-12 at 12 32 52 pm](https://user-images.githubusercontent.com/14189245/27044627-43257186-4f6c-11e7-90d5-a3eccf86c475.png)
@andy-esch

**Comment by andy-esch** [comment]
I think they are working correctly now based on my testing.
