### ISSUE TITLE
Add message about tracking metrics at installation time

### ISSUE THREAD

**Issue by cmongut** [CartoDB/cartoframes#1495]
As a user, I want to know that the library is going to track my usage in an anonymous way.

We need to add this message when the library has been installed:

```
We collect data on your usage of CARTOframes to understand how you use it and use this information to improve the product. Usage data includes information like "map_created," which tells us the date and time you created a map. The usage data we collect is anonymous, does not allow us to see the contents of what you're working on, and is handled in accordance with our Privacy Notice <https://carto.com/privacy/> .

You may choose to opt out by calling cartoframes.utils.setup_metrics(False)
```

**Comment by Jesus89** [comment]
I'm not sure if we can add this message to the pip install. Could we add it in the installation section instead?

**Comment by andy-esch** [comment]
I agree with @Jesus89 that this should be in the install section of the docs instead of being printed with `pip install ..`.
