### ISSUE TITLE
Add progress bar to carto_sync()

### ISSUE THREAD

**Issue by stuartlynn** [CartoDB/cartoframes#15]
Borrow whatever pymc3 does

**Comment by ljwolf** [comment]
pymc3 uses [tqdm] (https://pypi.python.org/pypi/tqdm), a good general-purpose library for this which swaps in timed versions of iterators like `range`.

**Comment by andy-esch** [comment]
Not in sync, but in the write method: https://github.com/CartoDB/cartoframes/blob/a2cd18dcb99abcd68ff082c8c45486eca72bf4c8/cartoframes/context.py#L226-L227

Once sync is finally written it will be included as well.
