### ISSUE TITLE
On larger datasets, make sure add Overviews after Cartoframes/Carto sync

### ISSUE THREAD

**Issue by nygeog** [CartoDB/cartoframes#150]
Unioning Overview'd tables and then Cartodbfying doesn't generate Overviews automatically. 

https://github.com/CartoDB/cartodb-postgresql/blob/master/doc/CDB_Overviews.md

**Comment by andy-esch** [comment]
Thanks for the tip @nygeog, I wasn't aware of that. Do you know if it's possible to disable overview generation via the Import API? I don't see it listed as an option in the documentation: https://carto.com/docs/carto-engine/import-api/standard-tables#standard-tables

**Comment by nygeog** [comment]
@andy-esch so I was just checking this page out (https://github.com/CartoDB/cartodb/blob/master/services/importer/lib/importer/overviews.rb)

And perhaps, thinking out loud a bit here, if you are importing files, and type-guessing is off and these are a-spatial tables (no defined geom) or non-point tables (https://github.com/CartoDB/cartodb/blob/master/services/importer/lib/importer/overviews.rb#L89), you should be not have Overviews triggered via the Importer. 

For more on overviews, I find this doc to be super useful; https://github.com/CartoDB/cartodb-postgresql/blob/master/doc/CDB_Overviews.md 

    SELECT CDB_CreateOverviews('table_name');
    SELECT CDB_DropOverviews('table_name');
    SELECT CDB_Overviews('table_name');

And @jgoizueta is very likely the most knowledgable person about Overviews.

**Comment by danicarrion** [comment]
_Also perhaps @danicarrion may know if we can override the Importer if data is/are points._

Sorry, I don't really understand the question

**Comment by nygeog** [comment]
@danicarrion can the Import API request be modified at all to actually *not* create overviews for a file (in Andy's case an intermediate chunk file)?

**Comment by danicarrion** [comment]
I'm afraid it can't :-(

**Comment by danicarrion** [comment]
I mean, other than keeping the chunk size below 500k records

**Comment by nygeog** [comment]
That's a good point about < 500k. Cc @andy-esch

**Comment by andy-esch** [comment]
Closing as overviews will be disappearing
