### ISSUE TITLE
List All Available Public Datasets

### ISSUE THREAD

**Issue by djfan** [CartoDB/cartoframes#1502]
`Catalog().subscriptions()` shows available private datasets for one specific account. Is there any function or variable to show all available datasets including public ones? Or how to list all public datasets (providers, etc) through cartoframes.

**Comment by cmongut** [comment]
Hi @djfan!

There isn't a method for that right now. There is a way to get them using the conversion to dataframes.

```
datasets_df = Catalog().country('usa').category('demographics').datasets.to_dataframe()
datasets_df[datasets_df['is_public_data'] == True]
```

Does this solve what you're looking for?

**Comment by djfan** [comment]
That works! Thanks!!
