### ISSUE TITLE
Download a geography returns a 500 error (a few times)

### ISSUE THREAD

**Issue by alasarr** [CartoDB/cartoframes#1503]
I've tried to download a Geography and the process hanged and I get this exception:

![image](https://user-images.githubusercontent.com/1161870/72705351-91a82500-3b5b-11ea-9a13-fd08c5089f26.png)

It has been at 95% around 3 minutes without downloading any data (I checked the file size)

cc: @cmongut @oleurud

**Comment by alasarr** [comment]
@josemazo did you find this issue during QA or did you forget to test download feature?

**Comment by alasarr** [comment]
If you call several times the progress bar brokes:

![image](https://user-images.githubusercontent.com/1161870/72705697-6f62d700-3b5c-11ea-94b4-14afe50d0638.png)

**Comment by alasarr** [comment]
Could be that progress bar doesn't work when storage API is used?

**Comment by alasarr** [comment]
I've run the download like 10 times and I've not been able to reproduce again the download fail, but the progress bar issue is always there.

**Comment by oleurud** [comment]
> Could be that progress bar doesn't work when storage API is used?

They were not returning the `total_rows` with BQ Storage API, this is the reason why the progress bar always looks full but it counts the rows downloaded.

About the error, I have not seen it before

**Comment by alasarr** [comment]
As an improvement we could take the number of rows of the dataset from the catalog at summary_json

**Comment by josemazo** [comment]
> @josemazo did you find this issue during QA or did you forget to test download feature?

I didn't get any 500 errors, but I encountered the fallback to the regular download from the Storage API.

> As an improvement we could take the number of rows of the dataset from the catalog at summary_json

If that summary is always updated it's the best idea, if not, some metadata can be accessed from the regular BQ API.

**Comment by Jesus89** [comment]
Solved by using DO API
