### ISSUE TITLE
Add example about how to load a shapefile

### ISSUE THREAD

**Issue by cmongut** [CartoDB/cartoframes#1518]
Shapefile is a common geospatial vector data format. Let's show how to load it with geopandas and visualize it with CARTOframes.

![Screen Shot 2020-01-29 at 16 30 26](https://user-images.githubusercontent.com/711025/73370547-aea7cb00-42b4-11ea-824a-0af1b761246e.png)

**Comment by Jesus89** [comment]
Done in https://github.com/CartoDB/cartoframes/pull/1547
