### ISSUE TITLE
Allow to show legends in Maps inside a Layout

### ISSUE THREAD

**Issue by cmongut** [CartoDB/cartoframes#1519]
As a data scientist, I want to be able to show legends inside a Layout to be able to understand the results.

![image](https://user-images.githubusercontent.com/711025/73372754-0431a700-42b8-11ea-839b-857fff21e8be.png)

**Comment by ztephm** [comment]
Enterprise user is asking about this feature in Zendesk Ticket 69736. I have more use-case details if we need @cmongut

**Comment by cmongut** [comment]
Hi @ztephm, we are already working on this. It should be ready in the next release :)
