### ISSUE TITLE
Allow to publish a Layout

### ISSUE THREAD

**Issue by cmongut** [CartoDB/cartoframes#1520]
As a data scientist, I want to be able to publish a Layout so I can share the comparison with anyone.

**Comment by ztephm** [comment]
Enterprise user is asking for this feature, in Zendesk Ticket 69736. I have more use-case details if you need @cmongut

**Comment by cmongut** [comment]
Hi @ztephm, thank you very much for reporting this. We are doing some tests to see if we can get it soon. I'll keep you update it.

**Comment by Jesus89** [comment]
It will be available in the next release 1.0.2
