### ISSUE TITLE
Footer doesn't work as expected in published map

### ISSUE THREAD

**Issue by djfan** [CartoDB/cartoframes#1523]
Footer (from legend) works well in my jupyter lab locally. 
<img width="246" alt="Screen Shot 2020-01-30 at 2 29 57 PM" src="https://user-images.githubusercontent.com/13675438/73483678-d5760800-436d-11ea-82dc-0b8c527ea75c.png">

But, after I publish it, it doesn't work. 
<img width="246" alt="Screen Shot 2020-01-30 at 2 30 05 PM" src="https://user-images.githubusercontent.com/13675438/73483679-d6a73500-436d-11ea-81f3-22bcce261081.png">

Map Link: https://team.carto.com/u/dfan/kuviz/31976fb1-0619-41c2-a4e8-d37dc98eb1c7

cc @andy-esch @Jesus89 @elenatorro  Thanks!

**Comment by djfan** [comment]
cc @StevePIsaac as well

**Comment by ztephm** [comment]
Adding this to Frontend RT Kanban b/c of @StevePIsaac comment here: https://github.com/CartoDB/research/issues/729#issuecomment-581553844

@elenatorro would you please let us know if this is for a different team than Response Team Frontend? Thank you.

**Comment by elenatorro** [comment]
Hi! yes, I'll pick that one 👍

**Comment by elenatorro** [comment]
Hi @djfan 👋 could you try publishing this visualization from the `fix/1523-text-scaping` branch? Thanks! :)

**Comment by djfan** [comment]
solved !! @elenatorro hope this could be merged in the next release. 
Here's the [Colab Notebook](https://colab.research.google.com/drive/1Rp2bUiLEnOTXPWXzfIqN2tugtIpzvhoN)
