### ISSUE TITLE
Add migration message to the developer center

### ISSUE THREAD

**Issue by cmongut** [CartoDB/cartoframes#1529]
As a former CARTOframes user, I want to know how to update my code to CARTOframes 1.0 so I can take advantage of the latest improvements.

Let's add the following warning message to the developer center for CARTOframes 1.0.

```
CARTOframes 1.0 includes breaking changes from betas and 0.10 version, [check the migration guide](https://github.com/CartoDB/cartoframes/blob/v1.0.0/docs/developers/migrations/1.0.0.md) to learn how to update your code.
```

**Comment by Jesus89** [comment]
Closed in https://github.com/CartoDB/developers/pull/694
