### ISSUE TITLE
Documentation edit

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartoframes#1564]
Can we edit this page to make it clear that maps can't be published with a `default_public` API key please?

https://carto.com/developers/cartoframes/examples/#example-publish-public-table-visualization

Asking because the current language is confusing to users:
https://github.com/CartoDB/support/issues/2418

Let me know if Support should do a pull request, I'm happy to if we need.

**Comment by elenatorro** [comment]
Hi @ztephm, what do you think about this?

> This example illustrate how to publish a visualization using a public table. Using public tables does not require to create Maps API keys to visualize them on a notebook. However, you need an API Key to publish any visualization, wheter the data used is public or private.
Read more about Maps API Keys: https://carto.com/developers/auth-api/guides/types-of-API-Keys/ 

Do you think we should add it somewhere else?

**Comment by ztephm** [comment]
Sounds good @elenatorro - I made small edits: 

>This example illustrates how to publish a visualization using a public table. You do not need a Maps API key to visualize a public table within a notebook. However you do need an API Key to publish any visualization, whether its data is public or private. Read more about API Keys here: https://carto.com/developers/auth-api/guides/types-of-API-Keys/

We do already say this in the Guides section, so I think we don't need to add it in a third place at this point:

![Screen Shot 2020-02-27 at 2 48 04 PM](https://user-images.githubusercontent.com/1779444/75489824-39d9b680-5970-11ea-802d-77fb6fc16b39.png)

**Comment by elenatorro** [comment]
In production! 🚀 thanks @ztephm!
