### ISSUE TITLE
Legend not rendered for maps in layout

### ISSUE THREAD

**Issue by maptastik** [CartoDB/cartoframes#1588]
I have a few maps that I would like to group together in an instance of `Layout()`. I want each map in the layout to have their own individual legends. When I render each map individually, the legend I defined for that instance of `Map()` renders as expected. However, when I add those same maps to an instance of `Layout()`, the legend does not render.

[Here is a Colab Notebook demonstrating this behavior.](https://colab.research.google.com/drive/1d0up8Qz5E-t1TxdBVsWyD1GuVwjhc5Uq) Note that I have also reproduced this behavior with Jupyter Lab.

## Maps rendered individually

![image](https://user-images.githubusercontent.com/3319507/76542932-247a8700-645c-11ea-8548-b6cc6f7d4f66.png)

## Maps rendered in a layout

These are the same exact maps rendered as part of a layout:

![image](https://user-images.githubusercontent.com/3319507/76542997-3e1bce80-645c-11ea-9156-a9831ae869c5.png)

**Comment by Jesus89** [comment]
Dup: https://github.com/CartoDB/cartoframes/issues/1519

**Comment by cmongut** [comment]
Hi @maptastik, thank you very much for reporting this. We are already working on it so It should be ready in the next release :)
