### ISSUE TITLE
Bug with more than one filter in enrichment

### ISSUE THREAD

**Issue by oleurud** [CartoDB/cartoframes#1590]
In versions 1.0.0 and 1.0.1, when a user adds more than one filter in enrichment, we are using only the last one. For example:

```
enriched_gdf = self.enrichment.enrich_polygons(
            gdf,
            variables=variables,
            aggregation=None,
            filters={
                variable1.id: '> 300',
                variable2.id: '< 800'
            }
        )
```

we are going to use only `variable2.id: '< 800'` and the first one `variable1.id: '> 300'` won't be used.

The problem is in https://github.com/CartoDB/cartoframes/blob/v1.0.1/cartoframes/data/observatory/enrichment/enrichment_service.py#L113 where we should use a list+append instead of doing an assignation.

It is not happening in the next version, but I am going to spent some time validating it and adding some e2e tests.

**Comment by Jesus89** [comment]
Is this still happening with the Enrichment API?

**Comment by Jesus89** [comment]
https://app.clubhouse.io/cartoteam/story/93717/using-1-enrichment-filters-fails-check

**Comment by josemazo** [comment]
With the current CF version, 1.0.4, you can use multiple filters! :tada:
