### ISSUE TITLE
Problem with cdb_service_quota_info() does not exist

### ISSUE THREAD

**Issue by alexrobl** [CartoDB/cartoframes#1599]
I am new user of cartoframes, I have my API Key and I tried start with Quickstart. But I have this problem. I thought that my conda had problem or my notebook, but I tried in colab and the same thing happens. Somebody may help me.

Code:

from cartoframes.data.services import Geocoding

stores_gdf, _ = Geocoding().geocode(stores_df, street='address')
stores_gdf.head()

Response:

CartoException: ['function cdb_service_quota_info() does not exist']

**Comment by cmongut** [comment]
Hi @alexrobl, thanks for trying CARTOframes :)

Could you tell us which version are you using? You can get it by doing:

```
import cartoframes

print(cartoframes.__version__)
```

Thanks!

**Comment by Jesus89** [comment]
Hi @NestorTejero, sorry for the inconvenience. We are working on it to solve it ASAP.

**Comment by Jesus89** [comment]
Hey @NestorTejero the bug seems to be fixed now. Could you try the geocoding again? Thanks
