### ISSUE TITLE
Broken links in dev center guides for v1.0b2

### ISSUE THREAD

**Issue by VictorVelarde** [CartoDB/cartoframes#1601]
As notified by @jaimegc, there are some broken links in dev center, in the Guides, for v1.0b2

Check links at
https://carto.com/developers/cartoframes/v1.0b2/guides/Introduction/

(also check some other betas, as it looks like an issue on 'version prefix')

**Comment by cmongut** [comment]
Thanks @VictorVelarde! Low priority as it was notified internally.

cc @CartoDB/rt-managers

**Comment by Jesus89** [comment]
We're going to remove 1.0beta docs, so we can close this issue.
