### ISSUE TITLE
When a map is published the link at the button does not open in a new window

### ISSUE THREAD

**Issue by jatorre** [CartoDB/cartoframes#1646]
The link at the button of the publsihed publication does not open in a new window, so when the map is piublished on a blog like in our case you get it weird. 

![image](https://user-images.githubusercontent.com/127803/84369840-be76da80-abd7-11ea-8b5c-7a55f1e6dadc.png)

Example in here: https://carto.com/blog/worldpop-global-demographic-insights/

**Comment by Jesus89** [comment]
Good catch. The link is opened inside the iframe. I think with `target="_blank"` solves the issue. I'll create a ticket in CH.

**Comment by Jesus89** [comment]
https://app.clubhouse.io/cartoteam/story/84666/open-learn-more-link-outside-iframe

**Comment by Jesus89** [comment]
Solved in https://github.com/CartoDB/cartoframes/pull/1647.

It will be ready to use in the next release (1.0.4), but only for new publications not for the old ones since it's a change in the HTML content.

**Comment by jatorre** [comment]
thanks!
