### ISSUE TITLE
Change Dataset.to_dataframe to return GeoDataFrame

### ISSUE THREAD

**Issue by arredond** [CartoDB/cartoframes#1679]
When downloading a DO Dataset to a dataframe, the current return type is a Pandas DataFrame. However, the function includes an option to download the geometry (`add_geom = True`), which is actually the default. IMO, the return type should be a GeoPandas GeoDataFrame, ready to perform further spatial operations.

**Comment by Jesus89** [comment]
Hi @arredond could you create this also in CH. For the next features we will use only CH, sorry :sweat_smile:

**Comment by Jesus89** [comment]
https://app.clubhouse.io/cartoteam/story/99926/change-dataset-to-dataframe-to-return-geodataframe-1679

**Comment by Jesus89** [comment]
Done. It will be available in the next stable release 1.0.5
