### ISSUE TITLE
add methods for reading example datasets

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#170]
We need a way to load resources (data) for code examples. We're in a unique position in that we're a cloud-hosted service, so we can rely on having datasets hosted in a special carto account and use the already-built cartoframes machinery (`cc.read`) to pull down the data.

I propose we use `cartoframes.carto.com` (which is currently used for testing) to store the data. We can move the testing account to `cartoframes-testing.carto.com` instead.

Here's a proposed API for accomplishing this (def. open for discussion):
```python
# list datasets - returns a dataframe of dataset names, descriptions, link 
#  to where it's used (notebooks in the cartoframes repo), etc.
#  we should define this better, but something 'data library'-like for metadata
cc.example.list()
# get a visual of data before downloading
cc.example.map('great_dataset', color='colname')
# download data to a dataframe
df = cc.example.read('great_dataset')
```

## Community practices

Here are some examples of how datasets are loaded from other packages.

* `bokeh` make this work by having a data download method:
    ```python
    import bokeh
    bokeh.sampledata.download()
    ```
* `nltk` like so: http://www.nltk.org/api/nltk.html#nltk.data.load
* `scikit-learn`: http://scikit-learn.org/stable/datasets/index.html

🐲 
related #183

**Comment by juanignaciosl** [comment]
After giving this a thought, I'd like to propose another approach.  As you can load several `CartoContext` within the same notebook, instead of creating a new API for example data, I'd consider having a example `CartoContext`. Example:

```python
cc1 = cartoframes.CartoContext(base_url='http://cdb.localhost.lan:8888/', api_key='wadus')
cc2 = cartoframes.Examples
df = cc2.read('my_cities')
cc1.write(df, 'example_cities')
```

This way there's no need for a new API. This is better for maintenance purposes and also for learning, as users don't need to learn an specific API and can take full advantage of `CartoContext` API (in my example, `cartoframes.Examples` is a `CartoContext`itself). Internally, `cartoframes.Examples` is just a hardcoded user.

What do you think. @andy-esch ?

PS: as `Examples` should be a read-only user, the `api_key` shouldn't be the normal one. CARTO Frames should support skipping the `api_key` parameter so write permission is not granted. In a few weeks it should use the new Auth API, because it adds support for a public API key.

**Comment by andy-esch** [comment]
@juanignaciosl, I love it :) Much simpler / easy to use.

**Comment by andy-esch** [comment]
Reflecting on this approach, I'm thinking that we might have been too expansive.

The purpose of this feature is for giving users access to datasets for use in examples. They don't need the full functionality of a CartoContext. I can actually see some negatives:

1. Preview of datasets is not very important as they will be doing that through the code examples, so giving access to `CartoContext.map` is not needed.
2. If a user has a `CartoContext`, they may think that they would have access to `CartoContext.data{,_discovery,_boundaries}`.
3. Users may be more likely to ping the database with `CartoContext.query`, which isn't necessarily a big deal but it's not necessarily productive. For people who want to poke around it's still there ;)

Therefore, `CartoContext.read` has all needed functionality for example loading (e.g., it has a `limit=N` kwarg if only a subset is needed).

So how about something more like the following (inspired by [scikit-learn](http://scikit-learn.org/stable/datasets/index.html#toy-datasets):

```python
from cartoframes.examples import load_taxi
# or
from cartoframes import examples

taxi_df = load_taxi()
# or
taxi_df = examples.load_taxi()
```

`load_taxi` uses the example user format you proposed before, but it's hidden for the user:

```python
example_context = CartoContext(
    base_url='...',
    api_key='default_public')

def load_taxi(limit=None):
    """load taxi dataset..."""
    return example_context.read('taxi_50k', limit=limit)
```
This takes care of the curation issue (we're only giving access functions for a handful of datasets) and doesn't provide direct access to all the methods of the `example_context` object.

**Comment by juanignaciosl** [comment]
Ok, let's try that approach. TBH I don't know what's the best approach. Returning a read-only `CartoContext` with ready examples felt more natural to me but you're the expert here 👍 . Support for Auth API keys listing (#13564) was released today, so I can resume the work on this. Let's try this approach and see :-)

**Comment by andy-esch** [comment]
Cool -- this has been a good exercise for me, thanks.

Giving access to the `example_context` could be really helpful for people previewing cartoframes if they don't have a carto account with api/auth, so I think we should have a section in the docs about how it's importable and that it's a `CartoContext` instance against a read-only account.

**Comment by juanignaciosl** [comment]
Blocked until CartoDB/carto-python/issues/69 is done (on it!).

**Comment by andy-esch** [comment]
Done in #170 🎉
