### ISSUE TITLE
CartoContext.map rejects valid zoom,lat,long if zero

### ISSUE THREAD

**Issue by ljwolf** [CartoDB/cartoframes#171]
Since the check for nullity at [l758](https://github.com/CartoDB/cartoframes/blob/master/cartoframes/context.py#L578) is 

```python
if any([zoom,lat,long]) != all([zoom,lat,long]):
    raise ValueError('zoom, lat, and lng must all or none be provided')
```
The use of a zoom/lat/long at an integer value of zero causes `.map` to hit the early bail condition when at least one of them is `None` but not all are `None`. 
```python
>>> any([10, 51, 0])
True
>>> all([10, 51, 0])
False
```
I found this while trying to make a map of London.

I think a fix is:
```python
nullity = [zoom is None, lat is None, long is None]
if any(nullity) and not all(nullity):
    raise ValueError('zoom, lat, and lng must all or none be provided')
```

**Comment by andy-esch** [comment]
Completed in #172. Thanks @ljwolf :)
