### ISSUE TITLE
how to use in in china map?

### ISSUE THREAD

**Issue by qq542871902** [CartoDB/cartoframes#1715]
Carto is very efficient, but I want to ask how to use the map of China? Is there a way to use it now? Or need a third-party data source

**Comment by Jesus89** [comment]
Yes, you can create maps with a basemap centered in China and render layers from data like CSV, GeoJSON, or Postgres tables (in case you have a CARTO account). We offer also public and premium data for China, you can check our Spatial Data Catalog: https://carto.com/spatial-data-catalog/browser/?country=chn.

You can create a free account in case you want to store and publish your maps: https://carto.com/signup.
