### ISSUE TITLE
params/options not populating 

### ISSUE THREAD

**Issue by ljwolf** [CartoDB/cartoframes#187]
around l639 in `context.py`, we update the `params` & `options` if the user passes a zoom in, but we only update the options dict if the user does not pass in a zoom level.

This means that, if `lat,lng,zoom` are all `None`,  the resulting query URL does not have a bounding box. 

@andy-esch and I get very different defaults in this case, so this may be an issue with something beyond cartoframes?

**Comment by andy-esch** [comment]
@ljwolf, looks like the origins of this come from https://github.com/CartoDB/Windshaft-cartodb/issues/734#issuecomment-324859476. We can wait for a fix on this, but I realized that there's another, better, way to set the view via URL params:

```
https://<static map call>.png?lat=<lat>&lon=<lon>&zoom=<zoom>
```

We just need to get the lon/lat/zoom from the bounding box.

**Comment by andy-esch** [comment]
Digging into Windshaft a little, it looks like there's a [URL param for bbox](https://github.com/CartoDB/Windshaft-cartodb/blob/c325df1414bb4e1e3fabf59e3d8627fd2a32fa0e/lib/cartodb/controllers/named_maps.js#L254-L266), but I haven't been able to get it to work:

https://ljw.carto.com/api/v1/map/static/named/cartoframes_ver20170406_layers1_time0_baseid1_labels0_zoom0/800/400.png?config=%7B%22sql_0%22%3A+%22SELECT+%2A+FROM+nat%22%7D&bbox=-85.605118,30.355757,-80.751434,35.000828

@rochoa does `bbox` work like this or am I missing something?

**Comment by rochoa** [comment]
That should work. However, we have a regression and it's broken since https://github.com/CartoDB/Windshaft-cartodb/commit/29a6658e3dbf622e5d4ea8a2e20fbc4ce08d533b. See https://github.com/CartoDB/Windshaft-cartodb/issues/735.

BTW, the `zoom`+`lon`+`lat` combo works, in case you need it.

**Comment by andy-esch** [comment]
Cool, thanks @rochoa. Now I need to dig up how to turn a bounding box into a lng/lat/zoom.
