### ISSUE TITLE
carto_map options

### ISSUE THREAD

**Issue by stuartlynn** [CartoDB/cartoframes#19]
arguments : 

Basic usage 

- stylecol 
- css (optional) 
- color_ramp (optional) 
- quantification_method (optional) 
- linear, log  (optional) 

Advanced 
- css (just whatever)

Static 

Multimap!!!!!

- stylecols = [ ] 
- synced = True

**Comment by andy-esch** [comment]
Closing this as the Basic and Advanced cases were handled in #34.
Separate tickets for #35 and #9
