### ISSUE TITLE
Functions in user schema for obs augmentation

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartoframes#204]
Hi @andy-esch @stuartlynn 

I came across the [following functions](https://github.com/CartoDB/cartoframes/blob/product-code-review/cartoframes/assets/data_obs_augment.sql) that are installed in the user schema for DO augmentation purposes.

First of all, why are we creating this functions? Couldn't just we write the SQL directly in the SQL API request? Also `obs_data_table` seems to be unused.

And another question. Could we use Batch API for this? SQL API has short timeouts, and will have problems augmenting large datasets. On the other hand, Batch API is harder to use (polling). I guess this depends a bit on the use case, maybe this idea doesn't make much sense for notebooks, since you don't expect to be waiting for minutes for your answer anyway.

**Comment by andy-esch** [comment]
When we first wrote the DO augmentation method for cartoframes, the `obs_augment_table` function was not in the user schema, so we installed it through cartoframes. Could you point me to the function? I don't see it in observatory-extension or dataservices-api.

Yes, we can definitely use Batch API for this. For large enough dataframe operations, we're moving towards forms like this:

```python
import time
job = cc.write(df, 'new_table',
               lnglat=('lng_col', 'lat_col'))
while job is not None:
    curr_status = job.status()['status']
    if curr_status in ('done', 'failed', 'canceled', 'unknown', ):
        print(curr_status)
        break
    time.sleep(5)
```

**Comment by javitonino** [comment]
Uhm, I don't think we will be adding `obs_augment_table` or friends to the DO API soon, it is not currently in our roadmap. I'd prefer if no functions were added to the user schema, but I can see the convenience in doing so. So maybe, we can at least prefix them with `_cartoframes` or something along these lines. At least, that way, we can easily identify where they come from.

**Comment by ethervoid** [comment]
+1 to what Javi said. 

We should move to use the Official DS API for DO functions. We're not planning to add other functions to the DS client side to support this one.

In case you have problems with the current ones or are not enough we should talk about it and find a solution :)

**Comment by andy-esch** [comment]
How would you feel about us running them as an anonymous function instead? I think that might be possible, but I'm not sure yet. The functionality here is pretty core to the operation of this.. e.g., the automatic column naming is pretty important. Besides installing the functions on the user schema, do you have any other concerns?

**Comment by stuartlynn** [comment]
Hey guys

Just had a quick call with @javitonino about this. So we came up with the following options in the order in which we should explore them

1. It sounds like there are some new functions in the DO API that might work as replacements for the functions that we are installing. Have asked @javitonino  to link to them in this ticket so we can take a look and see if we can use them instead. This is the preferred method as we should be leveraging the official API whenever possible.

2. If they arent going to be useful then we will explore using an anonymous function or just running the code inline somehow. The concern about adding the functions to the user accounts is that if the user gets moved to another server (which happens sometimes), the function wont come with them. I guess this is less of a problem if we check for the function existence when we instantiate the context as then we will always know its there.

3. If we cant make an anonymous function work then we will generate functions with carto_frames prefixes so they are easy to use.  

Does that sound like a plan?

**Comment by javitonino** [comment]
About augmenting data, we recently updated the catalog with `UPDATE` queries for tables, e.g: https://cartodb.github.io/bigmetadata/spain/age_gender/es.ine.t1_1/es.ine.pop_0_4.html. As a note, with some reshuffling, you can do a create table in one go (similar to what the builder analysis does internally). I guess this isn't too useful for cartoframes, since it augments existing tables, instead of creating new ones with the augmented data.

```sql
CREATE TABLE augmented_do_test_points AS (
WITH data AS (
  SELECT cartodb_id AS id, the_geom FROM do_test_points
),
meta AS (
  SELECT OBS_GetMeta(ST_SetSRID(ST_Extent(the_geom), 4326),
  '[{"numer_id": "es.ine.pop_0_4",
    "denom_id": "es.ine.t1_1",
    "normalization": "denominated"}]'
  , 1, 1) meta
FROM data),
augmentation AS (
  SELECT id AS cartodb_id, (data->0->>'value')::Numeric AS pop_0_4_2015
  FROM OBS_GetData(
      (SELECT ARRAY_AGG((the_geom, id)::geomval) FROM data),
      (SELECT meta FROM meta))
)
SELECT orig.*, augmentation.pop_0_4_2015
FROM do_test_points AS orig
LEFT JOIN augmentation USING (cartodb_id)
)


SELECT cdb_cartodbfytable('javitonino', 'augmented_do_test_points')
```

Anyway, there is still a lot of templating going on, to get column names, etc. So, some options to do this:
1. Do it in python. It involves two roundtrips to the database (GetMeta to get column names, and then GetData)
2. Do it in SQL with functions, which is the current approach. You do two SQL roundtrips, one to create the function and one to execute it.
3. Do it in SQL with a [do block](https://www.postgresql.org/docs/9.5/static/sql-do.html). Just avoid creating the function, and send everything in a single `do` block. You just need minimal templating (to pass in the table name and meta). 

I guess option 3 is the one that fits both sides the best, right now. I was thinking about using the analysis API's instead, but they are not ready for prime time yet. For example, they need to be used in conjunction with a map. It could be cool to use with this, as a more generic piece, but not likely to happen soon.

Bonus: for searching for columns we have three functions:
1. [`OBS_Search`](https://carto.com/docs/carto-engine/data/discovery-functions/#obssearchsearchterm). Search by name and return a summary of the columns. Quite restrictive in what it can do, and likely to be deprecated tin the future.
2. [`OBS_GetAvailableNumerators`](https://carto.com/docs/carto-engine/data/discovery-functions/#obsgetavailablenumeratorsbounds-filtertags-denomid-geomid-timespan). The current best way to do it. It doesn't have `name` filters, but you can achieve the same result with some filtering like `SELECT * FROM OBS_GetAvailableNumerators() WHERE numer_name ILIKE '%income%'`.
3. [`_OBS_GetNumerators`](https://github.com/CartoDB/observatory-extension/blob/develop/src/pg/sql/42_observatory_exploration.sql#L184). Currently is a private API for builder use only, please, don't use it for cartoframes. However, I write it here, because it has search built-in as a function parameter and some extra builder-specific features. Just mentioning it in case you see something you like in this API, maybe we can improve it and make it public.

I would recommend you to go with 2, at the moment, but we can discuss improvements for the future, if you are not launching with the discovery functions.

**Comment by andy-esch** [comment]
@javitonino, thanks for the long, thoughtful responses! I finally got some time to tackle this and will try out what you suggest.

**Comment by andy-esch** [comment]
Ok, I completely removed those two user-defined functions :) And now it's way more dynamic!

The problem with OBS_GetAvailableNumerators is that it does not return any date information other than if a single string matches. Instead, I'm using it to get the all available numerators just by geography, and then OBS_GetMetadata to give the fuller picture of what's available.

You can see it in action in `data_discovery`: https://github.com/CartoDB/cartoframes/blob/746bc18a9533937de797d530996a133fec464952/cartoframes/context.py#L999-L1107

Similar functionality is happening in `data` (redundant, yeah, so I should probably refactor it to have them share some of their core parts): https://github.com/CartoDB/cartoframes/blob/746bc18a9533937de797d530996a133fec464952/cartoframes/context.py#L1109-L1230

Please feel free to comment away on https://github.com/CartoDB/cartoframes/pull/273.

**Comment by ethervoid** [comment]
Great, thank you, @andy-esch I know is a bit cumbersome to do this kind of changes.

I haven't talked in this issue to avoid noise :)

**Comment by andy-esch** [comment]
Finished in #273
