### ISSUE TITLE
Styling functions

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartoframes#206]
This is more of a question than anything. Why do we create a function for each color ramp? e.g: `styling.burg()`. My first approach would have been to make public the `_scheme` function and just validate that the passed ramp is in a list of supported ramps.

cc @andy-esch @stuartlynn

**Comment by andy-esch** [comment]
Good question, and I agree with your approach. In fact, we're moving that direction already on the branch `add-legends-v1` where we rely on the package [`palettable`](https://github.com/jiffyclub/palettable) which accepted our PR to add CartoColors.
