### ISSUE TITLE
User directory for configuration

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartoframes#207]
Right now, the configuration file for saving credentials is located in the same place as the cartoframes library https://github.com/CartoDB/cartoframes/blob/master/cartoframes/credentials.py#L8-L9.

This will cause permission issues with global installs (`pip install` without virtual env). My suggestion would be to use the os-dependent configuration directory. A good way to do this is to use the [appdirs module](https://pypi.python.org/pypi/appdirs/1.4.3) function, `user_config_dir`. It also has the nice thing that this is per-user instead of per-system. The bad part is yet another dependency.

cc @andy-esch @stuartlynn

**Comment by andy-esch** [comment]
Great idea. We don't want to re-invent the wheel, so we'll do this.
