### ISSUE TITLE
Class for credentials

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartoframes#208]
This is just a suggestion. I feel that the credentials handling code is a bit cumbersome to use, with a lot of little functions for saving each setting. Although this works, it will become a mess if we add more settings.

My suggestion:
- Credentials class
- Pass the configuration file in the constructor (if not set, have some default configuration path)
- One attribute per setting (`api_key`, `base_url`)
- One method to `load` and a second one to `save` configuration. Probably calling `load` in the constructor, and `save` in the attribute setters.
- Allow passing a `Credentials` instance to the CF context. This way, all settings are encapsulated with a single parameter.

This is my very rough idea. I think it's worth it for future extensibility as more settings may very well be needed. What do you think? @andy-esch @stuartlynn

**Comment by andy-esch** [comment]
💯 agree :)

**Comment by andy-esch** [comment]
My first sketch of the interface looks like this:
```python
>>> from cartoframes import Credentials
>>> creds = Credentials(api_key='abcdefg',
                        username='marlin')


>>> creds.key()
abcdefg
>>> creds.base_url()
https://marlin.carto.com/
>>> creds.key('hijklmnop', update=True)
>>> creds.key()
hijklmnop
>>> creds.key(clear=True)
>>> creds.key()
None
>>> creds.user(erase=True)
>>> creds.base_url()
None
```

**Comment by andy-esch** [comment]
First pass here -> https://github.com/CartoDB/cartoframes/pull/213/files
Nice part is that it removes more than 100 lines :)
