### ISSUE TITLE
add chunksize param to `cc.read` that turns cc.read into a generator

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#212]
for large tables/dataframes, it is oftentimes easier to be able to iterate over chunks of it instead of having the entire object in memory. Python generators seem perfect for this use-case.

**Comment by andy-esch** [comment]
This can be accomplished with something like this:
```python
dfs = []

# template query
q = '''
SELECT * FROM my_big_table
WHERE cartodb_id >= {lower} and cartodb_id < {upper}
'''

num_rows = cc.sql_client.send('select count(*) from my_big_table')['rows'][0]['count']

# read in 100,000 chunks
for r in range(0, num_rows, 100000):
    dfs.append(cc.query(q.format(lower=r, upper=r+100000)))
```

And then advise the user to combine into one with:
```python
# combine 'em all
all_together = pd.concat(dfs)
```

**Comment by oleurud** [comment]
Solved using COPY TO in https://github.com/CartoDB/cartoframes/pull/570
