### ISSUE TITLE
define strategy around dataframe index when writing to carto

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#221]
A couple of options as I see it:

1. Renaming index if it's not named, and including it as a named column in the output
2. Not including the index in the output if the DataFrame has the default index from 0..n
3. Include index(es) as columns in the output

@michellemho, interested in mapping out and coding the possibilities? I'm definitely open to different options/variations than above.

It looks like pandas has [some good options](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_csv.html) for handling this:

> **index** : _boolean, default True_
> Write row names (index)
> **index_label** : _string or sequence, or False, default None_
> Column label for index column(s) if desired. If None is given, and header and index are True, then the index names are used. A sequence should be given if the DataFrame uses MultiIndex. If False do not print fields for index names. Use index_label=False for easier importing in R

**Comment by michellemho** [comment]
I agree with the options. If the index of the Dataframe is simple 0..n default index, I think we can remove it before writing. If there is anything else more complicated, we should include the index (or indices for MultiIndex) as an added column when writing of the dataframe.

**Comment by michellemho** [comment]
New strategy:

Index of DataFrame is _not_ included when writing to CARTO.

For cases where the DataFrame has a named index, MultiIndex, or non-sequential (any index that is not the default `np.arange(n)`), give a warning that the index has been dropped when writing to a CARTO dataset. Suggest resetting the index with `.reset_index()` before writing.
