### ISSUE TITLE
'taxi_sample.csv' not in jupyterserver

### ISSUE THREAD

**Issue by iamwfx** [CartoDB/cartoframes#224]
Hey guys, I think the 'taxi_sample.csv' file that's the "basic_usage" notebook is referencing is missing!

**Comment by andy-esch** [comment]
cc @stuartlynn, could this be added to the bootstrapping?

**Comment by andy-esch** [comment]
Scratch that. I rewrote the notebook last week to not pull from a local csv. Checkout the latest version here: https://github.com/CartoDB/cartoframes/blob/master/examples/Basic%20Usage.ipynb

It pulls roughly from that URL I posted in the last comment. @iamwfx, we'll have those notebooks updated on the server eventually.
