### ISSUE TITLE
Small typo:

### ISSUE THREAD

**Issue by iamwfx** [CartoDB/cartoframes#225]

**Comment by iamwfx** [comment]
Missing the `/` after `.com`. :)

**Comment by michellemho** [comment]
I think this was resolved with `os.path.join`... maybe try updating cartoframes and see what happens?
https://github.com/CartoDB/cartoframes/commit/82962e8ad34ad8e35b18f08baf9368a73160282d
 and 
https://github.com/CartoDB/cartoframes/blob/7d4d48cf01daa5a12c69b71a239517c7c1b10b26/cartoframes/context.py#L226

**Comment by andy-esch** [comment]
Yep, this was fixed in that commit!
