### ISSUE TITLE
Error when exporting to builder - has to do with caps in file name

### ISSUE THREAD

**Issue by iamwfx** [CartoDB/cartoframes#229]
Finally doing the batch export of all the parks files to builder.  My i'm exporting a dataframe to the builder.  My files are named `data_parks_XX_output`, where `XX` is the park ID.  The IDs are capitalized.  

When I run: 
`conn.write(P, 'data_parks_{}_output'.format(park_id),lnglat=('lng', 'lat'),overwrite=True)`

I somehow get :
`pyrestcli.exceptions.BadRequestException: ['relation "data_parks_B342_output" does not exist']`

It seems to work when I call the table name `data_parks_b342_output` though!

**Comment by andy-esch** [comment]
Good find! Should be an easy fix, too :)
