### ISSUE TITLE
Methods for Table Operations

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#254]
These include traditional GIS operations and common database operations like JOINs. [Geopandas](http://geopandas.org/geometric_manipulations.html) has some nice functionality for operations like this, as does pandas and pyspark. Here we want to take advantage of CARTO's cloud-based database to perform these methods, while being careful to stay in a Pythonic syntax like you see in pandas.

## Functions

- [ ] JOIN (spatial or attribute)
  - **Use case:** Combine data from different data sources which have some data in common (e.g., points intersecting polygons, JOIN by common column values)
  - References
    - [GeoPandas](http://geopandas.org/mergingdata.html)
    - [PostgreSQL full list of JOIN types](https://www.postgresql.org/docs/9.6/static/queries-table-expressions.html)
    - [PySpark](http://spark.apache.org/docs/2.1.0/api/python/pyspark.sql.html#pyspark.sql.DataFrame.join)
  - Params
    - `on` (_str_ or _list of str_): column name or list of column names | 'the_geom' for spatial
    - `op` (_str_): one of `intersects`, `within`, `overlap`
    - `how` (_str_, optional, only use with `on='the_geom'`): `inner` (default), `left`, `right`, `outer`, `cross`
    - `expr` (_str_, optional): Custom expression (e.g., `col1 == col2`)
    - `agg` (TBD, optional): implicit group by / aggregation ?
- [ ] Intersects/Within/Contains (give back geometries that contain or are within other geometries)
  - **Use case:** give back all geometries that intersect geometries in a separate table -- or not
- [ ] Centroid
- [ ] Area of geometry
- [ ] Nearest (give back the n-nearest geometries to another geometry)
- [ ] Non-spatial JOIN
- [ ] Convex Hull, Envelope / Extent / Bounding Box, Union
  - categorize by = column or list of columns
- [ ] Difference
- [ ] Aggregations / GROUP BY / Etc.
- [ ] Sample
  - **Use case:** Sample from a data source
  - References:
    - [`TABLESAMPLE` in PostgreSQL](https://blog.2ndquadrant.com/tablesample-in-postgresql-9-5-2/)
- [ ] Limit
  - **Use case:** limit to `n_rows` entries
  - **Params**:
    - `n_rows` (_int_): Number of rows to return

## Location-data Services

- [ ] Geocoding
- [ ] Routing
- [ ] Isochrones
- [ ] Address normalizing (#377)

See #253 for a prototype of these operations in action.

~@michellemho, could you help add to this list of popular and feasible operations that we could do in cartoframes?~

cc @stuartlynn

**Comment by andy-esch** [comment]
Bulk of work done in: https://github.com/CartoDB/cartoframes/pull/253
Refer to that instead of the list above.

**Comment by alrocar** [comment]
This could be quite nice, I'm adding it to 1.1 in case we want to consider it

**Comment by Jesus89** [comment]
Since CARTOframes is integrated with Geopandas, we cover that feature.
