### ISSUE TITLE
null column values in styling not handled correctly

### ISSUE THREAD

**Issue by michellemho** [CartoDB/cartoframes#276]
Dataset is earthquakes and styling for both color and size is ramp of magnitude (5 bins, equal interval). Null values in the column used for styling are being colored as though they are in the highest color bin using CARTOframes.

![image](https://user-images.githubusercontent.com/12551177/32517488-9956e03a-c3d4-11e7-9786-9e4b60c096e1.png)

Equivalent styling in CARTO Builder shows that the null values default to the lowest color in the ramp.

![image](https://user-images.githubusercontent.com/12551177/32517628-0152530e-c3d5-11e7-91ea-d70f1340be9f.png)

We should change this so the null values correspond to the lowest value of ramp, the same as in Builder.

**Comment by andy-esch** [comment]
Or show 'em as grey!

**Comment by michellemho** [comment]
@makella, do you have any insights on how to best handle null values when styling a map? It appears the Builder ends up putting null values in the lowest color bin. Andy and I were thinking we should have a different color to show they don't fit in the color scheme (like gray unless the color scheme has gray).

**Comment by makella** [comment]
@michellemho yep! gray is always a good choice for no data values

**Comment by andy-esch** [comment]
@michellemho, the grey-out line could be added to the end of the cartocss generated in the function `_get_cartocss`: https://github.com/CartoDB/cartoframes/blob/master/cartoframes/layer.py#L446-L520

Something like this:
```python
cssify("#layer[{}=null]".format(self.color): {
    "marker-fill": "grey"
})
```
