### ISSUE TITLE
Explore the idea of a Data Obs Metadata Class

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#278]
# Creating a Data Obs Metadata class

This would be useful for validating metadata, completing metadata, describing in a more human-readable way the metadata, as well as other helper functions around narrowing down the metadata that a user wishes to use for obtaining. Right now this is exposed through `cc.data_discovery`, but the catalog is so large that the API calls can be slow for common requests like:

For example, I expect that this would be very common:
```python
df = cc.data_discovery('usa_counties')
```
The way the DO is structured, this will give back all measures and their permutations with denominators, years, geographic levels (sometimes), and quantiles. The search is pretty overwhelming. Since the user can be presented with an overwhelming amount of metadata, we should build some tooling around making searches more human-centered and not so tied-in with the metadata syntax.

This could take many forms, so this is just an early sketch:

```bash
>> from cartoframes import DataObsMeta
>> # have a representation of the complete catalog of the US for 2013, 2014
>> dom = DataObsMeta('United States', years=(2013, 2014))
>> dom.length
5051
>> dom.head(2).describe()
1. Median Income from the US Census (block group level) for the years 2010 - 2014.... 
2. Median Age from ...
...
```

An advantage of having something like this is that an abstract representation of the metadata could be contained in this class and only needs to be downloaded locally when relevant. It also has the advantage that we could add functionality around the class that gives, for example:

1. human-readable descriptions,
2. chainable filters. Here, we could filter by a curated grouping, different geographies, years, and a rank them according to a popularity / usefulness metric:
    ```
    DataObsMeta('United States')\
          .group('economic')\
          .geography(levels=('Block Group', 'PUMA'))\
          .timespan(years=(2013, 2014))\
          .top(20)
    ```
3. Overview maps of all the metadata entries. This could be presented as a matrix of overview maps, or could be a carousel of interactive maps.
4. If users are ever able to add their own entries to the DO, we could write an interface/wrapper for doing it programmatically through cartoframes.

Ref #273 

cc @michellemho @hannahblue @stuartlynn

**Comment by alrocar** [comment]
Stale issue. Closing 👋
