### ISSUE TITLE
add obs_data_table and obs_meta_table to user accounts

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#28]
For the data observatory augmentation to work, users will need `obs_data_table` and `obs_meta_table` PL/pgSQL functions in their accounts.

cc @talos

**Comment by talos** [comment]
I think we definitely should make these available more broadly.

@andy-esch could we spend some time next sprint collaborating on an API spec?  This code will need to live in dataservices-api and we will want to be able to make it very clear what the design & justifications are.

I'm also honestly not a huge fan of the names I came up for those functions either, if you have better ideas I'm all 👂👂.

**Comment by andy-esch** [comment]
Handled installation of these functions in #99, but happy to scope some of this out more. Most of it is hidden to the user. Users only need to worry about the metadata / discovery pieces like we discussed already. I'll have more on that soon.

**Comment by andy-esch** [comment]
This functionality is being replaced by some queries directly in the cartoframes functions since `OBS_GetData` and `OBS_GetMeta` have things like suggested names, etc.: https://github.com/CartoDB/cartoframes/pull/273/files#diff-9c45bf459be12218d26e264077e1f4f3R1219

So closing. Miss you @talos :)
