### ISSUE TITLE
create catalog-aware data obs utility functions

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#290]
These are currently hard-coded in `cartoframes/dataobs.py`:
https://github.com/CartoDB/cartoframes/pull/273/files#diff-0fccff070a210374981d7d37d77f73ed

**Comment by andy-esch** [comment]
This could be a session-dependent object that's updated when one of the `data_x` methods are called

**Comment by alrocar** [comment]
Stale issue. Closing 👋
