### ISSUE TITLE
CartoContext.query TypeError: send() got an unexpected keyword argument 'skipfields'

### ISSUE THREAD

**Issue by Eh2406** [CartoDB/cartoframes#299]
I tried to run
```python
cc = cartoframes.CartoContext(base_url=base_url, api_key=api_key)
df = cc.query("SELECT * FROM information_schema.tables")
```
and got
```
df = cc.query("SELECT * FROM information_schema.tables")
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-09d1bb4bc035> in <module>()
----> 1 df = cc.query("SELECT * FROM FROM information_schema.tables")

C:\Anaconda2\lib\site-packages\cartoframes\context.pyc in query(self, query, table_name, decode_geom)
    568             skipfields = ('the_geom_webmercator'
    569                           if 'the_geom_webmercator' not in query else None)
--> 570             select_res = self.sql_client.send(query, skipfields=skipfields)
    571
    572         self._debug_print(select_res=select_res)

TypeError: send() got an unexpected keyword argument 'skipfields'
```

**Comment by andy-esch** [comment]
Thanks for reporting. That's an interesting error, but double check your query too. `FROM` is in it twice. Do you get the same error if you only use one `FROM`?

**Comment by Eh2406** [comment]
Sorry for the copy and paste error, I do and I have edited the report.

**Comment by andy-esch** [comment]
I'm not able to reproduce on my side. Could you check which version of the `carto` Python package you have?

My guess is that you have version 1.0.1, while cartoframes needs at least 1.1.0: https://github.com/CartoDB/cartoframes/blob/eabd22dd2ad4de4444955af5273d776fd8b9b79f/setup.py#L18

That package was updated in v1.1.0 to allow kwargs like `skipfields` that allow avoiding the duplicate `the_geom_webmercator` column.

**Comment by Eh2406** [comment]
carto does not have a `__version__` atribute. but `pip freeze` confirms your theory. `carto==1.0.1` and `cartoframes==0.2.4b4` and retesting. That worked! Thanks!

**Comment by andy-esch** [comment]
👍 :)

**Comment by andy-esch** [comment]
We're on a more recent version of cartoframes too: 0.4.0b6 now too. More stable and more features.
