### ISSUE TITLE
Some Binder Examples Don't Work

### ISSUE THREAD

**Issue by hydrosquall** [CartoDB/cartoframes#303]
The following example notebooks don't run on `binder` due to missing dependencies.

- `cartoframes-and-dask.ipynb`
- `Shapely, Geopandas, and Cartoframes.ipynb`

This will be fixed in #302.

**Comment by stuartlynn** [comment]
Thanks for the heads up. We will add these to the requirements.txt that binder pulls from and that should resolve the issue

**Comment by stuartlynn** [comment]
Oh sorry didnt see your PR. Reviewing now
