### ISSUE TITLE
explore the idea of the minimum number of metadata cols for lookup

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#321]
DO creation fails because there are too many queries in the request. There must be a minimum number of entries that still give the same measures. E.g., `numer_description` and `demon_description` are probably not required. Same with so many others. 

I'm guessing this is nearly the complete set:
* `numer_id`
* `numer_timespan`
* `geom_id`
* `geom_timespan`
* `denom_id`
* `denom_timespan`

**Comment by Jesus89** [comment]
Related to DO v1 (deprecated)
