### ISSUE TITLE
Sync table chunks denominator needs 1 added

### ISSUE THREAD

**Issue by nygeog** [CartoDB/cartoframes#33]
Guessing this starts at zero and the counter isn't applied to all. 

<img width="259" alt="screen shot 2017-03-08 at 11 03 09 am" src="https://cloud.githubusercontent.com/assets/2790599/23711854/1492d624-03ef-11e7-942d-220b1938bcb3.png">

**Comment by nygeog** [comment]
@andy-esch do you think I can find this in core.py?  

https://github.com/CartoDB/cartoframes/blob/master/cartoframes/core.py

**Comment by andy-esch** [comment]
That's reported here:
https://github.com/CartoDB/cartoframes/blob/ea461c402eae5c9b4c4875b027863540e8de6a3e/cartoframes/utils.py#L273-L287

We're going to be building a progress bar soon, that's just a temp solution that's apparently buggy.

**Comment by andy-esch** [comment]
no longer a problem!
