### ISSUE TITLE
add option to add margin of error for any measure added

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#333]
Margins of error are an important part of any analysis. Adding the ability to easily add them is therefore an important feature for a data scientist.

We should be able to pull this off in `cc.data` by adding a `include_moe=True|False` flag.

Some barriers I see:
+ Is there a clear mapping between a measure and it's margin of error? E.g., `numer_id` + `_moe`?
+ We'd need to do derivative calculations on MOEs for DO measures that are derived. E.g., if a measure is returned as the rate of poverty (Census Total Population / Number Poverty last 12 months), then we'd need to do the appropriate calculating to get the new error. It might be something like the square root of the sum of squares.

cc @hannahblue @michellemho

**Comment by hannahblue** [comment]
1. Do you know if we're storing margins of error at all at the moment? It doesn't look like it. 

2. For a measure that has a denominator would it be enough to just have columns for the numer_moe and denominator_moe and let the user decide how to calculate the error? (I'm assuming we wouldn't have MOE in Builder, but feel free to challenge that assumption)

**Comment by andy-esch** [comment]
I thought margins of error had maybe been added, but I guess I was wrong. @michellemho said that the ETL work for bringing them might be pretty straight forward, and seems there are some open tickets:
* https://github.com/CartoDB/bigmetadata/issues/71
* https://github.com/CartoDB/bigmetadata/issues/308

**Comment by stuartlynn** [comment]
Yeah I don't think these are in the ETL right now but we should get them in ASAP. I think its really important especially in the CARTOFrames context to have them available.

**Comment by alrocar** [comment]
Stale issue. Closing 👋
