### ISSUE TITLE
create table with sql api first, then import api with tablename and sql params

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#335]
Data Observatory enrichment queries that rely on `persist_as` rely on `cc.query`'s functionality to create tables. `cc.query` in turn uses the Import API's `table_name` and `sql` arguments to create the table. It seems that `sql` shouldn't contain data observatory calls because it throws 500 errors.

# ToDo

- [ ] look at import api logs that fail from DO enrichment to see what's really happening
- [ ] potentially replace the single Import API call with a SQL API one to create the table (not cartodbfy'd), then import api with the same table name. this might cause errors or could work beautifully. Not sure.

**Comment by juanignaciosl** [comment]
@andy-esch could you add an example of the code that triggers a 500 error, please? I could take a look at this :-)

**Comment by andy-esch** [comment]
Well, I tried to reproduce and realized I never moved the query to the body of the POST like you suggested in #310 😅. I put up that code: https://github.com/CartoDB/cartoframes/pull/375

Looks like I can't reproduce, so the sql query to the body of the POST must've solved it.

**Comment by juanignaciosl** [comment]
💃
