### ISSUE TITLE
optionally include non-shoreline clipped geometries

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#348]
This can easily be done by adding a new flag `include_nonclipped` or some similar name.

cc @hannahblue

**Comment by andy-esch** [comment]
@hannahblue, thinking through this a little more, I'm not seeing an obvious way to know whether there is a shoreline-clipped alternative to a geometry. I was going to do a simple filter on whether a `geom_id` ended in `_clipped` or not, but that would exclude some boundaries that don't have a clipped alternative. Is there are a more direct way of knowing this information?

**Comment by hannahblue** [comment]
@andy-esch Could do a filter on whether the geom_id does not end in _clipped instead?

**Comment by andy-esch** [comment]
Nevermind, I don't think it's as hard as I thought.

If `geom_id` begins with `us.census.tiger.` then filter out `geom_ids` that don't end in `_clipped`
if `geom_id` does not begin with `us.census.tiger` keep it.

I forgot that it was only US census boundaries that were clipped.
