### ISSUE TITLE
Multimap!!!!!

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#35]
options:
```
stylecols = [ ]
synced = True
```

Ref #19

**Comment by andy-esch** [comment]
This can be done with the current implementation of `cc.map`, although it might be nice to have some helper functionality to pull this off more easily.

**Comment by andy-esch** [comment]
Here's an example:
http://bl.ocks.org/stuartlynn/raw/ad278674148e0cd38523eb661be044ed/

**Comment by Jesus89** [comment]
:top:

**Comment by alrocar** [comment]
Stale issue. Closing 👋

And we already have it!! 🎉
