### ISSUE TITLE
add more dataset management functionality

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#353]
## list datasets

Besides being a simple list, it could be a dataframe with other information:
* name
* geometry type(s)
* percent nulls
* column names
* data types (as json blob?)

**Comment by hannahblue** [comment]
@andy-esch Maybe this could be two different things. 
1. list data sets (dataframe of all table names, # rows, etc)
2. table metadata (column names, geometry type, data types, % nulls, etc)

**Comment by andy-esch** [comment]
Yeah, good idea. I could see implementing this a few ways. A basic way would be just add a flag `describe=True|False` that optionally gives these stats as additional columns to the dataframe. Another way is giving back a list of table objects (prototype [here](https://github.com/CartoDB/cartoframes/pull/253)), which could be iterated over internally and then have a describe method applied to each returned table (one of the bullet points in that ticket).
