### ISSUE TITLE
histogram legends!

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#358]
http://bl.ocks.org/ramiroaznar/e2e263c00e791e4057062be26d46a018

cc @ramiroaznar :)

**Comment by ramiroaznar** [comment]
Well, let's wait for @rochoa and @IagoLast because it is not working as expected. There should be a right way to implement this.

**Comment by andy-esch** [comment]
Yeah, no rush, I just want to record the idea for later.

**Comment by andy-esch** [comment]
Similar to @ljwolf's legendgrams: https://github.com/pysal/legendgram

**Comment by ramiroaznar** [comment]
@andy-esch have a look at https://github.com/CartoDB/cartodb.js/issues/1998
