### ISSUE TITLE
scope out functionality of carto-python for some refactoring

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#359]
cartoframes can offload some of the complexity to the carto-python client.

* Datasets
  * #57: checking if a table is a sync table (https://github.com/CartoDB/carto-python/blob/master/carto/datasets.py#L126)
  * #391: deleting a table (feature request https://github.com/CartoDB/carto-python/issues/71, but should probably be a feature), with the addition that it errors if the dataset is attached to a map it will fail (#357)
  * Import API functionality

**Comment by alrocar** [comment]
Hey Andy, feel free to add FRs to the `carto-python` repo.

IDK how much time I'll be able to spend to the project, but I'm open for guiding you/code reviewing if you want to try to implement anything.

Thanks!

**Comment by andy-esch** [comment]
Sounds good, thanks @alrocar :) I'm scoping out the work to do this quarter, so will let you know if any of that overlaps.

**Comment by andy-esch** [comment]
It's pretty much happened
