### ISSUE TITLE
add an optional query that uses Batch SQL API if it goes over limits

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#361]
`cc.query` should add a flag that enables for getting the results of longer running queries. We could catch the errors that mention account limit and warn/advise that there exists a flag for doing this with longer running queries.

A couple of ideas on how to structure it:
* It permanently persists the dataset only if `table_name` is specified.
* Generate the table with batch sql api, return it as a dataframe, delete it from carto

Open questions:
* How will this work with `layer.QueryLayer`?

cc @zingbot

**Comment by stuartlynn** [comment]
I like this idea even if we just implement it for data queries at this point in time. We can add support for map layers in the future. 

Having it be a flag and giving feedback that users should use it when their regular queries time out makes a lot of sense to me.

**Comment by andy-esch** [comment]
Yeah, this is becoming increasingly necessary because methods that used to work (e.g., augmenting arbitrary polygons--i.e., spatial interpolation--in data observatory) are now hitting the limits and failing.

**Comment by andy-esch** [comment]
related: https://github.com/CartoDB/cartoframes/pull/364 and https://github.com/CartoDB/cartoframes/issues/362
