### ISSUE TITLE
[meta] map outputs

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#374]
The map methods can be greatly improved and extended. Here are some ideas:

1. class `cartoframes.Map(layers=[...], vector=True|False)`
    - essentially a wrapper around carto.js v4?
    - attributes such as the HTML document
    - `.as_image()` and `.as_html()` each of which takes in `size` args etc.
    - `__repr__` is just the HTML displayed in an IPython.display.IFrame
    - output method (save to HTML)
    - possible methods:
        + add layer, remove layer
        + getter and setter methods for things like basemaps
        + update properties
        + widget properties
    - callbacks
        + e.g., plotting library filter -> change query -> change map
2. More robust: --> https://github.com/CartoDB/cartoframes/pull/586 and https://github.com/CartoDB/cartoframes/pull/595
    - Templating with Jinja
3. Replace IPython with branca `Figure` outputs. This greatly reduces the sub-dependencies as branch only relies on jinja2 --> https://github.com/CartoDB/cartoframes/pull/586

**Comment by andy-esch** [comment]
@michellemho I was thinking something like ^^ would be a good contender for replacing `cc.map()`, and also give the output functionality you were looking for in #483

**Comment by andy-esch** [comment]
@elenatorro Looks like you took care of a lot of these things!

**Comment by elenatorro** [comment]
Yes! good catch, it'd be great to have at least an example where you can use both raster & vector in a notebook.

I haven't seen this issue before :) what we can do next week, after we merge the namespace + api branch, is to go to this issue and see what've already done and add the suggestions / ToDo's to the rest of the tasks we've.

What do you think? :)

**Comment by andy-esch** [comment]
Yes, let's add :)

In a related side note, I've been thinking about making `Map` more declarative, similar to how Altair is structured (https://altair-viz.github.io/gallery/scatter_tooltips.html):

```python
import altair as alt
from vega_datasets import data

source = data.cars()

alt.Chart(source).mark_circle(size=60).encode(
    x='Horsepower',
    y='Miles_per_Gallon',
    color='Origin',
    tooltip=['Name', 'Origin', 'Horsepower', 'Miles_per_Gallon']
).interactive()
```
