### ISSUE TITLE
Update basemap URLs

### ISSUE THREAD

**Issue by jaakla** [CartoDB/cartoframes#378]
Basemap URL domains have fastly.net (e.g. here: https://github.com/CartoDB/cartoframes/blob/master/cartoframes/layer.py#L63), this should be replaced by basemaps.cartocdn.com in whole code and tests:
* Old: https://cartodb-basemaps-{s}.global.ssl.fastly.net/
* New: https://{s}.basemaps.cartocdn.com/

Other URL parts remain same. Needed for https://github.com/CartoDB/lbs-services/issues/16

**Comment by jaakla** [comment]
@stuartlynn could you manage it or should I do PR? Should be quite straightforward search/replace type of fix

**Comment by andy-esch** [comment]
I'll take care of it @jaakla, I've been off a few days so didn't see this till now.
