### ISSUE TITLE
Explore jupyterlab extension for cartoframes

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#386]
Extension developer guide:
http://jupyterlab.readthedocs.io/en/stable/developer/extension_dev.html

Jupyter Lab beta announcement: https://blog.jupyter.org/jupyterlab-is-ready-for-users-5a6f039b8906

Extension tutorial: http://jupyterlab.readthedocs.io/en/stable/developer/xkcd_extension_tutorial.html

**Comment by andy-esch** [comment]
cc @jorgesancha

**Comment by Jesus89** [comment]
Done
