### ISSUE TITLE
move cc.delete to carto-python sdk dataset management

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#391]
`CartoContext.delete` should rely on the carto-python sdk to delete datasets instead of running the `DELETE` against the `api/v3/viz` endpoint to eliminate duplicate code and increase maintainability of the code base.

`CartoContext.delete`: https://github.com/CartoDB/cartoframes/blob/375d593e33e7e7094c71108c99984af8a45556d4/cartoframes/context.py#L340-L360

In carto python sdk it will look something like this:
```python
dsm = DatasetManager(self.auth_client)
ds = dsm.get(table_to_delete)
ds.delete()
```

Related:
+ a delete should fail if a table has a dependent visualization https://github.com/CartoDB/cartoframes/issues/357
+ delete should raise error if operation fails https://github.com/CartoDB/cartoframes/issues/269

**Comment by alrocar** [comment]
Related product issue -> https://github.com/CartoDB/product/issues/336
