### ISSUE TITLE
Argumentation of data frame by DO 

### ISSUE THREAD

**Issue by stuartlynn** [CartoDB/cartoframes#4]

**Comment by talos** [comment]
I think the underlying API should work the same way as it does with DO -- you specify numer, denom, geom, and timespan separately (or have them determined implicitly) for every single measure.  So something more like this:

```
df.carto_do_augment(cols=[
  {'numer_id': 'col_id1'},
  {'numer_id': 'col_id2', 'normalization': 'denominator', 'timespan': '2010'}
]) 
```

At the same time, I think there is a strong argument to be made for some Pythonic sugar on top of this.

I'm not sure what the best sugar would be though!
