### ISSUE TITLE
Add Carto Documentation for Spatial Analysis

### ISSUE THREAD

**Issue by stuartlynn** [CartoDB/cartoframes#408]

**Comment by djfan** [comment]
committed. Todo: 
- data sources in the example codes
- write `sql` codes in a proper way (like pep8 for python)

**Comment by djfan** [comment]
Can we customize *Layer CSS* style in CARTOframes, like we did in Builder?  
<img width="1343" alt="screen shot 2018-04-13 at 10 48 38 am" src="https://user-images.githubusercontent.com/13675438/38741663-65a52224-3f08-11e8-8108-9c90890e6ae6.png">

**Comment by djfan** [comment]
For **category** columns, can we customize schema to fix {**category: color**} pairs ?
e.g. In this case, want to show **'LL'** as **'darkblue'** and **'HH'** as **'darkred'**
```python
cc.map(layers=[
    BaseMap('dark'),
    QueryLayer("""
            select * from tmp
            where significance < 0.05 and (quads = 'LL' or quads ='HH')
            """,
            color={'column': 'quads',
                   'scheme': styling.custom(colors=["darkblue", "darkred"], 
                                            bin_method='category' )})],
    interactive = False)
```
One solution is to add **lengend**, but it would be better if we can customize styling like  
```python
'scheme': styling.custom(colors={"LL": "darkblue", "HH": "darkred"}, 
                         bin_method='category' )})],
```

**Comment by djfan** [comment]
@andy-esch I shared the Mcdonalds data `dfan.nyc_mcdonalds` I used in `03-Spatial-Analysis` example code. And I assume users can load it using `mcd = cc.example.load_nycMcdonalds()`

**Comment by andy-esch** [comment]
Thanks @djfan :) Nice guide! I made some changes in that PR. We won't have the example datasets yet so I modified the line to just read the data from carto using the SQL API and pd.read_csv. I made some other changes too, added some more images, etc.

I also like your suggestions on styling, etc. so opened that ticket #426 to remind us when we overhaul the map creation pieces of carto.

**Comment by andy-esch** [comment]
Done in https://github.com/CartoDB/cartoframes/pull/414
