### ISSUE TITLE
Add better logging functionality with multiple levels

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#422]
First ideas on levels of reporting / logging:

0. Warnings
1. Info (default) -- results of uploading events (table created, schema being set, updating geometry based on lnglat, etc. or with DO printing the query, announcing the quota estimate, etc.)
2. Verbose Info -- information about more backend-y things like API call for static images, etc.

Other things not changed
* Errors

There may be some basic frameworks for doing this already in place on system packages. There's currently some debugging functionality.

**Comment by oleurud** [comment]
Related https://github.com/CartoDB/carto-python/issues/113

**Comment by oleurud** [comment]
In addition to this one, we are currently showing warnings on "valid methods" and it makes no sense for users

**Comment by oleurud** [comment]
I have been checking some libraries and also doing some code starting from [loggin module](https://docs.python.org/3/library/logging.html#module-logging). 

I think we can use https://pypi.org/project/colored/ to show messages to the user, with different levels (info, warning, error) with some font colors, formatting, ...

**Comment by oleurud** [comment]
I can not take this issue right now, I have created a PR with the idea https://github.com/CartoDB/cartoframes/pull/901/files

**Comment by oleurud** [comment]
After finish this task, we will need to add some messages in some places like in the map publication (for example `the tables X and Y have been created. Also a new API key has been created.`)
