### ISSUE TITLE
Explore basic viz details like graticules, tick marks, etc.

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#424]
Some users want graticules and other value displays on their maps. It'd be nice to support some basic versions of 'pretty' graticules or even custom ones. One way to accomplish this could be through a custom layer class like `Graticules` that adds them and accompanying labels, etc.

**Comment by cmongut** [comment]
@andy-esch do you still find this useful in your day-to-day? Re-open if so 🙂
