### ISSUE TITLE
legends and styling ideas

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#426]
Some ideas on legends and styling
----

For **category** columns, can we customize schema to fix {**category: color**} pairs ?
e.g. In this case, want to show **'LL'** as **'darkblue'** and **'HH'** as **'darkred'**
```python
cc.map(layers=[
    BaseMap('dark'),
    QueryLayer("""
            select * from tmp
            where significance < 0.05 and (quads = 'LL' or quads ='HH')
            """,
            color={'column': 'quads',
                   'scheme': styling.custom(colors=["darkblue", "darkred"], 
                                            bin_method='category' )})],
    interactive = False)
```
One solution is to add **lengend**, but it would be better if we can customize styling like  
```python
'scheme': styling.custom(colors={"LL": "darkblue", "HH": "darkred"}, 
                         bin_method='category' )})],
```

cc @djfan 
Ref #408

**Comment by Jesus89** [comment]
This is already covered with the new API, right? @andy-esch

**Comment by andy-esch** [comment]
Yep, I believe so :)
