### ISSUE TITLE
Add schema option for `Layer` for shared datasets

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#428]
Just like #394, sometimes you want to reference a table that's shared but in a different user schema. 

We could use a 'magic' approach and first find the table in the user schema, and then look at other available schemas (if possible) and iterate through them until one is a valid query. This doesn't seem like a great solution, though. Not sure what is the best approach here.. Definitely don't want to complicate the API.

One future enhancement that we can rely on is the `Table` class, which should have some properties like schema that are more naturally handled. `Layer` should work with `Table`.

**Comment by andy-esch** [comment]
Another option is just to suggest using QueryLayer and specifying the user schema there.

**Comment by andy-esch** [comment]
Yep, let's just add a note/tip about this in the `Layer` docs, making sure to write the word 'shared', 'schema' and other terms people may search for

**Comment by Jesus89** [comment]
Old API. We already use the schema in the new API
