### ISSUE TITLE
Plan for COPY TO and COPY FROM upgrades

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#437]
SQL API is adding new end points that allow data to stream to or from a table. This could be advantageous in multiple ways: no more batch uploading (breaking up table, setting schema, re-combining temp tables, etc.) and potentially not writing files but streaming the data directly using a multi-part HTTP handler. These endpoints also accept gzipped files so pandas to_csv's compression gzip option can be used here.

This would be a nice win for cartoframes as it could potentially reduce a lot of the code base related to writing.

**Comment by andy-esch** [comment]
Nice tip from requests: send text as a file

```python
>>> url = 'http://httpbin.org/post'
>>> files = {'file': ('report.csv', 'some,data,to,send\nanother,row,to,send\n')}

>>> r = requests.post(url, files=files)
>>> r.text
{
  ...
  "files": {
    "file": "some,data,to,send\\nanother,row,to,send\\n"
  },
  ...
}
```

**Comment by andy-esch** [comment]
Also note ([link](http://docs.python-requests.org/en/master/user/quickstart/#post-a-multipart-encoded-file)):
> In the event you are posting a very large file as a multipart/form-data request, you may want to stream the request. By default, requests does not support this, but there is a separate package which does - requests-toolbelt. You should read the toolbelt’s documentation for more details about how to use it.

> For sending multiple files in one request refer to the advanced section.

**Comment by andy-esch** [comment]
Early prototype:

```python
from io import StringIO
s = StringIO()
df.to_csv(s, index=False)

cc._auth_send(
    'api/v2/sql/copyfrom',
    'POST',
    params=dict(q=query),
    data=s.getvalue(),
    stream=True)
```

**Comment by alrocar** [comment]
Closing in favour of #561 and #563
