### ISSUE TITLE
remove data_augment from the code base

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#444]
It's currently printing a DeprecationWarning

**Comment by alrocar** [comment]
We are about to start implementing this [issue](https://github.com/CartoDB/cartoframes/issues/565)

@andy-esch Is the _remove data_augment from the code base_ still valid?

**Comment by andy-esch** [comment]
It just wraps `CartoContext.data` in a way to be backwards compatible. But it's time to remove it.
https://github.com/CartoDB/cartoframes/blob/f43b1f14685ed7e4a3423e24df46e7465d47b25c/cartoframes/context.py#L1534-L1539
