### ISSUE TITLE
feature request: 'autocomplete' table names

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#450]
It'd be a pretty nice feature to tab-completion (via the `def __dir__` function or something like it) when using `cc.read`.

The process I see:
```python
cc.read('<tab>
```
And a list of tables in the popup appears.

cc @michellemho

**Comment by andy-esch** [comment]
@cmongut Nice to haves like this make the library much easier to use. There's something similar for `pd.read_csv('<tab>` that shows local files.

**Comment by cmongut** [comment]
True! I closed it because I saw the use of CartoContext :)

Let's add it to the milestone 1.1 for noq.
