### ISSUE TITLE
Better color error for scheme

### ISSUE THREAD

**Issue by michellemho** [CartoDB/cartoframes#461]
When making color scheme, if you ask for more than 10 colors using CARTO color, nothing is returned. We should have an error message.

**Comment by andy-esch** [comment]
Yeah, a lot more should be done for validating inputs of map styles.

We can add a validation step in the [scheme function](https://github.com/CartoDB/cartoframes/blob/master/cartoframes/styling.py#L75) that's something like this:

```python
if bin_method in ('quantiles', 'equal', 'headtails', 'jenks'):
    assert bins <= 7, 'Number of bins must be seven or smaller to work with CartoColors'
elif bin_method == 'category':
    assert bins <= 10, 'Number of category bins must be 10 or fewer'
```

**Comment by Jesus89** [comment]
This is no longer required since the `scheme function` has been deprecated in the new API.
