### ISSUE TITLE
[provisional] Plan inclusion of Auth API in cartoframes

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#463]
The Auth API allows for some nice flexibility for cartoframes users who want to share their work and provide some level of access without fear of exposing their API key.

To move cartoframes to the Auth API, the following is a provisional list of TODOs to get everything working as expected for cartoframes users:

- A better reporting system for the authentication around method calls (e.g., DO calls should print error messages that Auth key does not have access to this service)

The following APIs are effected:
  * Import API (`CartoContext.write`)
  * Data Observatory (`CartoContext.data`, `CartoContext.data_discovery`, and `CartoContext.data_boundaries`)
  * api/v3/viz DELETEs (`CartoContext.delete`)
  * SQL API if user does not have it selected when creating the auth key
  * Maps API if user does not have it selected when creating the auth key

**Comment by alrocar** [comment]
It looks this is quite related to the oncoming [OAuth integration](https://github.com/CartoDB/cartoframes/issues/567). Basically the user will authorize CARTOframes to get an API key based on some scopes to access APIs, datasets, etc.

I'd close this one in favour of #567

**Comment by andy-esch** [comment]
👍 closing, agree that seems like the more appropriate path
