### ISSUE TITLE
Save HTML files of maps

### ISSUE THREAD

**Issue by michellemho** [CartoDB/cartoframes#464]
Request from NFPA to be able to have `save_html` method, which would output the html file used to create the embedded map. Similar to method in Plotly: https://plot.ly/python/offline/.

This could be done by saving the formatted `cartoframes.html` file found in `assets` to the working directory.

**Comment by andy-esch** [comment]
Some planning for this is here:
https://github.com/CartoDB/cartoframes/issues/374

**Comment by Jesus89** [comment]
Related to #668
