### ISSUE TITLE
tooltip

### ISSUE THREAD

**Issue by rutgerhofste** [CartoDB/cartoframes#467]
this module looks very promising. any idea of when the tooltip functionality will be implemented?

**Comment by rutgerhofste** [comment]
thank you for your answer. I cant import the contrib module:

https://colab.research.google.com/drive/1abcTlTg2xue8aQXxMI_y7fFRtDyB8vsO

3.6.3 (default, Oct  3 2017, 21:45:48) 
[GCC 7.2.0]

cartoframes==0.7.0

ModuleNotFoundError: No module named 'cartoframes.contrib'

Am I doing something wrong?

**Comment by andy-esch** [comment]
Contrive is not a module so it’s not importable. ‘vector’ is importable though so the following will work:

from cartoframes.contrib import vector

By the way, the documentation for the vector module is here: http://cartoframes.readthedocs.io/en/latest/#cartoframes.contrib.vector.QueryLayer

Note that ‘interactivity’ is set at the Layer/QueryLayer level.

**Comment by rutgerhofste** [comment]
the command:
`from cartoframes.contrib import vector`

gives the following error:
`ImportError: No module named contrib`

please see the script in the original question.

**Comment by rutgerhofste** [comment]
please let me know if I need to update my code but I literally copied your code and ran it. Still doesn't work.

**Comment by andy-esch** [comment]
I'm able to reproduce on colab. Interesting that the tests pass that use that syntax: https://github.com/CartoDB/cartoframes/blob/master/test/test_contrib_vector.py

Looking into it

**Comment by andy-esch** [comment]
It's a packaging issue. If you installs from the wheel distribution it all works as expected, but the contrib directory was accidentally left out of the source distribution. I'll do a new release to make sure it's not left out of the source too.

**Comment by rutgerhofste** [comment]
ok great. Thank you for looking into this.

**Comment by andy-esch** [comment]
I'll get to this early this week. Sorry for the delay -- I've been on vacation. 
By the way, if you install cartoframes like this you should be able to use tool tips like describe above and in the documentation:
```bash
pip install git+https://github.com/cartodb/cartoframes.git#egg=cartoframes
```

**Comment by michellemho** [comment]
It doesn't seem to be working. @djfan and I discovered that you need to install the `cartoframes` package from the local directory for this to work. So it would be something like:

`git clone git@github.com:CartoDB/cartoframes.git`
`pip install -e  /Users/mho/proj/cartoframes` or ``pip install -e path/to/your/cartoframes`

https://pip.pypa.io/en/stable/reference/pip_install/?highlight=-e

**Comment by andy-esch** [comment]
v0.7.1 of cartoframes has the contrib correctly included. The code snippets from the docs and above should work now if you upgrade:

```bash
$ pip install --upgrade cartoframes
```

**Comment by rutgerhofste** [comment]
It works, thanks for fixing the issue.

**Comment by rutgerhofste** [comment]
The tooltips seem to default to hover instead of click though.

**Comment by andy-esch** [comment]
Yep, you can specify click by passing in an interactivity argument like this:
`interactivity=dict(event='click', cols=['col1', 'col2'])`

**Comment by rutgerhofste** [comment]
really cool. I'm going to fiddle with it this week. thanks

**Comment by andy-esch** [comment]
Cool, please feel free to open tickets for more feature requests / bug reports / etc. The contrib module is meant to be 'experimental' so we can get user feedback before bringing it into the core of cartoframes code.
