### ISSUE TITLE
add proportional symbol styles

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#47]
cc @makella

**Comment by andy-esch** [comment]
This shouldn't be too hard to pull off given the format for the [torque custom queries](https://github.com/CartoDB/cartoframes/blob/6856363be291c5353c35cf749dee6657d84a70ae/cartoframes/layer.py#L391-L406) currently in place.

```python
with stats AS (
SELECT max({style_col}) as maxval, min({style_col}) as minval
  FROM {table}
)
SELECT *, 10 * sqrt(({style_col} - minval) / (maxval - minval)) As prop_quantity
  FROM {table}, stats
```

**Comment by makella** [comment]
sweeeet

**Comment by andy-esch** [comment]
This happens through `size_continuous_layer` now :)
