### ISSUE TITLE
dev center: cartoframes reference left menu links are not working

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/cartoframes#488]
In the [reference page of CartoFrames](https://carto.com/developers/cartoframes/reference), when clicking on the links from Batch Job and below, the page doesn't change.

For example, when clicking on `Batch Job` option of the left, the URL is the one of the image: `https://carto.com/developers/cartoframes/reference/#batch-job`

![screenshot 2018-10-09 at 13 58 31](https://user-images.githubusercontent.com/11177693/46668635-4ddf1580-cbcd-11e8-9c11-a1b95851f074.png)

But, the URL of the Batch Job section is: `https://carto.com/developers/cartoframes/reference/#batchjobstatus`

![screenshot 2018-10-09 at 13 58 57](https://user-images.githubusercontent.com/11177693/46668644-56375080-cbcd-11e8-8450-3c40bdd9060b.png)

**Comment by andy-esch** [comment]
Fixed now :)
