### ISSUE TITLE
build carto vl vector legend

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#491]
Build legends for cartoframes vector (interactive) maps.

1. Color based styling (e.g., choropleths)
2. Size based styling

Use this as a starting place for color based styling:
https://github.com/CartoDB/carto-vl/blob/e0b0badd74c6ba6016073d527a46a5163cf6c175/examples/misc/legends/legend-stroke.html

**Comment by andy-esch** [comment]
See https://bl.ocks.org/andy-esch/4bf730c6d0a326433af343006f6ec865

**Comment by jorgesancha** [comment]
Superseded by #610. Can we close @andy-esch ?

**Comment by andy-esch** [comment]
Oh yes
