### ISSUE TITLE
Add more utils functions in cartoframes.contrib

### ISSUE THREAD

**Issue by djfan** [CartoDB/cartoframes#498]
**Scenario 1**: 
Users want to quickly plot a Point(e.g. lng=-68.3823549, lat=44.3036906) or a Polygon through cartoframes. But currently, there's no easy way for python users to achieve this by running functions like PlotPoint(lng=-68.3823549, lat=44.3036906). My current solution is either searching the Point in Google map or wrapping it in a `geopandas.GeoDataFrame` and plotting it by `vector.LocalLayer()` which is not straightforward. 

**Scenario 2**:
Some users apply their own *cartoframes-related* customized utils functions very often. For me, for example, 
```python
def quad_to_poly(quad):
    '''
    Convert quadtree index to shapely.Polygon
    '''
    from shapely.geometry import Polygon
    from pygeotile.tile import Tile
    bbox = Tile.from_quad_tree(quad).bounds
    # min_lng, min_lat, max_lng, max_lat
    poly = Polygon.from_bounds(bbox[0][1], bbox[0][0], bbox[1][1], bbox[1][0]) 
    return poly
```
But it's annoying to copy & paste these functions from one notebook to the other, or copy from utils.py in other projects, especially if the function is much more complicated. If there's a way to save these functions in carto (through carto auth/account api), it would be much convenient for users to re-use and even share with their carto-mate accounts.

For **Scenario 1**, we need a public utils function warehouse. For **Scenario 2**, a personal one which is associated with personal carto account would be helpful. 

Current idea is to serialize python functions and save them in a carto dataframe like we save a geometry in wkt/wkb format. and users are allowed to add / delete / print / update / share / group/ list their own functions. 

- [x] **Step 1**: test whether or not function serialization is doable. e.g. `PlotPoint()` 
- [x] **Step 2**: save serialized/hashed functions through carto auth API
- [ ] **Step 3**: think about how to solve python library management / dependency issue. 
- [ ] **Step 4**: road map for detailed functionalities in this submodule.

**Comment by djfan** [comment]
notebook: [Step1/Step2](https://gist.github.com/djfan/906b2cda3899076801b5022b1ad53463)
next step: 
- [ ] add a new submodule `function` in `contrib`, and add three default built-in functions `add_function`, `delete_function` and `load_function`; 
- [ ] `CartoException`
- [ ] Step 3: library management / dependency issue

**Comment by andy-esch** [comment]
Do you know of any other services like this?
