### ISSUE TITLE
custom basemap layer in vmap still doesn't work ?

### ISSUE THREAD

**Issue by djfan** [CartoDB/cartoframes#502]
#490 
<img width="659" alt="screen shot 2018-11-08 at 4 55 00 pm" src="https://user-images.githubusercontent.com/13675438/48229813-223f7e80-e377-11e8-86bc-b6ac13cca8cd.png">

**Comment by andy-esch** [comment]
This hasn't been released yet. You can install from master and get the functionality though.

**Comment by andy-esch** [comment]
Try it out in v0.8.0. `pip install --upgrade cartoframes`
