### ISSUE TITLE
add `region=tablename` cover information

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#536]
e.g., update the documentation to better specify if it's convexhull or what, like so from the code:
https://github.com/CartoDB/cartoframes/blob/0bdd0e9185a487c1cf613c1d955dc8d4e0d68b05/cartoframes/context.py#L1310-L1342

Currently it doesn't give too much information.

cc @andrewbt

**Comment by cmongut** [comment]
@andy-esch I am going to close it as I don't think we are going to dedicate time to the previous data observatory integration.
