### ISSUE TITLE
large tables fail to combine because of too-large payload in batch sql api request

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#538]
Specifically, this code can lead to a payload that's too large:
https://github.com/CartoDB/cartoframes/blob/0bdd0e9185a487c1cf613c1d955dc8d4e0d68b05/cartoframes/context.py#L525-L558

**Comment by andy-esch** [comment]
If/when we move to the COPYFROM streaming, most of this _send_dataframe and _send_batches will be removed, so this issue is not a priority.

**Comment by alrocar** [comment]
Closing after having merged #561
