### ISSUE TITLE
provide api key creation helper methods

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#542]
It would live in the `Credentials` class as a `.new_key(<list of tables>, access='read')` method
https://github.com/CartoDB/cartoframes/blob/master/cartoframes/credentials.py

This would help creation and sharing of vector maps, etc. so that user is not exposing full API key.

cc @djfan

**Comment by alrocar** [comment]
We had a request to [support Auth API in the Python SDK](https://github.com/CartoDB/carto-python/issues/94). Let's tackle both issues together:

- Python SDK implements Auth API
- CARTOframes uses Python SDK

**Comment by alrocar** [comment]
We are now supporting Auth API in the Python SDK. See [related PR](https://github.com/CartoDB/carto-python/pull/125)

**Comment by Jesus89** [comment]
The creation of Maps API keys for private tables in a map is already done in the `publish` method. It's an automatic process, so there no need for the user to create API keys from CF.
