### ISSUE TITLE
subset dataframe for locallayer to only used columns and util cols

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#551]
~~Besides `the_geom`, `the_geom_webmercator`(?), `cartodb_id`, the set should include any involved in interactivity, and any involved in styling.~~
I think the only column needed is the geodataframe `geometry` column.

To get styling variables, something of the form could be useful:
```python
import re

s1 = 'ramp($colname, sunset)'
s2 = 'ramp(globalQuantiles($colname, 7), sunset)'

m = re.search('\$([a-z_]+)', s1)
assert m.group(1) == 'colname'

m = re.search('\$([a-z_]+)', s2)
assert m.group(1) == 'colname'
```

**Comment by Jesus89** [comment]
Could you clarify this a bit @andy-esch ?

**Comment by andy-esch** [comment]
When the geodataframe is sent to the JS environment, we do `gdf.to_json()` to get the full geojson. What happens most of the time is that the user only needs a subset of the data: geometry, columns used in styling/widgets/popups.

What could probably be a performance gain is that if we could figure out how to select only the columns needed for sending to the JS environment:

```python
gdf[['geometry', 'stylecol1', 'widgetcol']].to_json()
```

**Comment by Jesus89** [comment]
OK. Thanks for the clarification.

This is the behavior when VL loads data from a CARTO dataset, but this can only be applied when there is a Maps API instantiation. So I like your proposal of filtering the geodataframe before passing it to the visualization. We could potentially save a lot of memory size!

I'm not sure about the implementation, but I'll definitely check this for the 1.0.
