### ISSUE TITLE
'interactivity' can not show the column called 'length'

### ISSUE THREAD

**Issue by djfan** [CartoDB/cartoframes#553]
<img width="1058" alt="Screen Shot 2019-03-13 at 2 37 31 PM" src="https://user-images.githubusercontent.com/13675438/54305497-ce9ba680-459d-11e9-9cd8-87dc7d90d916.png">

<img width="1052" alt="Screen Shot 2019-03-13 at 2 38 31 PM" src="https://user-images.githubusercontent.com/13675438/54305496-ccd1e300-459d-11e9-9dd6-8ae1ccdc3d37.png">

**Comment by andy-esch** [comment]
This might be related to the following CARTO VL issue: https://github.com/CartoDB/carto-vl/issues/1247

**Comment by Jesus89** [comment]
Fixed in https://github.com/CartoDB/carto-vl/pull/1410. It will be available in the next patch release of VL.
