### ISSUE TITLE
carto vl basic to advanced styling functions

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#554]
In addition to having text inputs, we could provide styling helper functions that will unravel into the full-blown examples so user don't have to use the carto vl syntax if they don't want. These functions can also serve as guidance in learning the CARTO VL syntax.

I can see a function like this (all of them very overloaded with additional args):
- animate('colname', 10, fade_in=0.1, fade_out=0.5) -> `'animation($colname, 10)'`
- prop_symbol('colname', min_size, max_size)
- color('colname', ramp='mint', bins=7) -> `'ramp(globalQuantiles($colname, 7), mint)'`
- color('colname', ramp='mint', bins=None) -> `'ramp(linear($colname), mint)'`

In addition to these, we should have some easter egg functions to do fun effects (e.g., `rainbow`, ...)

It would be handy if these were composable `f(g(x))` if a user wants to build a style that's more complex than the basic units of styling.

**Comment by elenatorro** [comment]
I think we should close it since we're working on this in the [helpers](https://docs.google.com/document/d/1aoaAcUTZnonfZEhhnSRqLXPbELiA4mTQ2FWesSLFpMo/edit#) document, and we're going to create a specific issue for each helper we decide to create. Feel free to reopen it! :)
