### ISSUE TITLE
rethink the ordering of layers in cartoframes vl

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#555]
currently layers are listed like this:
```python
vector.vmap([
    Layer(t1),
    Layer(t2),
    Layer(t3)
])
```

But they are rendered in this order on the map:
Bottom: t1
Middle: t2
Top: t3

This is counterintuitive -- it feels like the order should be reversed.

cc @makella

**Comment by elenatorro** [comment]
We're discussing this here https://github.com/CartoDB/cartoframes/issues/629
