### ISSUE TITLE
`CartoContext.write(df, <tablename>)` does not work if carto dataset is syncing with an external source

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#57]

**Comment by andy-esch** [comment]
```python
import requests
apiendpoint = 'https://{username}.carto.com/api/v1/synchronizations/?api_key={apikey}'

resp = requests.get(apiendpoint.format(username=creds['username'],
                                       apikey=creds['api_key']))
resp.text
```

**Comment by andy-esch** [comment]
Another option is to hit the `information_schema` table and see if that table is false for `is_insertable`.

```SQL
select * 
from information_schema.tables 
where table_schema='eschbacher' 
  and table_type='BASE TABLE'
  and table_name not in ('spatial_ref_sys', 'cdb_tablemetadata')
```

**Comment by andy-esch** [comment]
Another option is using the python sdk which has a method for getting that answer: https://github.com/CartoDB/carto-python/blob/59f6604d4414eea7984892237a2983977fffe2b1/carto/datasets.py#L126

**Comment by alrocar** [comment]
An update about this: That info is available via de [synchronization field](https://github.com/CartoDB/carto-python/blob/master/carto/datasets.py#L70).

Adding this issues to the "long running queries" project in case we have time to take a look.

**Comment by alrocar** [comment]
Related issue: #293

**Comment by alrocar** [comment]
It works in the current master branch
