### ISSUE TITLE
Change dataset privacy after write

### ISSUE THREAD

**Issue by alrocar** [CartoDB/cartoframes#579]
Since we are using COPY for writing, in most cases we cannot change privacy of created datasets for two reasons:

- There's a delay in the GHOST TABLES trigger that does not allow to use the `viz` API
- The `viz` API is not public

Updating a dataset it's possible with the Python SDK, but we should define what we want to do:

- Wrap the Python SDK dataset capabilities in the CARTOframes `dataset`?
- Disallow doing anything with datasets? (other than read, write, etc.)
- Rethink the existing `viz` API?
- Just force the user to use the CARTO Python SDK?

**Comment by oleurud** [comment]
IMO, thinking like a user, I see the privacy change and dataset creation as 2 different things and due to it, I will use 2 methods.

And about your question, I prefer: `Wrap the Python SDK dataset capabilities in the CARTOframes dataset`, but for now, only the privacy-related stuff

**Comment by alrocar** [comment]
Thanks @oleurud 

I've created a product issue as well, since we'll have to solve the source of the problem at some point.

**Comment by alrocar** [comment]
I'm closing this issue since we are already supporting privacy changes and there's a product issue in place to solve the problem in the right place.
