### ISSUE TITLE
Support INSERT statements

### ISSUE THREAD

**Issue by alrocar** [CartoDB/cartoframes#581]
This was originally included in https://github.com/CartoDB/cartoframes/issues/561 but since that PR is quite long, I'm splitting the issue.

Apart from this, we'd need to clarify what an INSERT is. If it's just a query that starts with an INSERT, then I guess we should go with a batch API implementation.

cc. @oleurud

**Comment by oleurud** [comment]
Same applies for SELECT queries and COPY TO
