### ISSUE TITLE
Check account disk quotas before writing

### ISSUE THREAD

**Issue by alrocar** [CartoDB/cartoframes#582]
- Raise error if dataframe size is bigger than account disk qouta
- Optionally allow to upload until disk quota is full, unless the dataframe is not fully uploaded

**Comment by Jesus89** [comment]
https://app.clubhouse.io/cartoteam/story/93719/check-account-disk-quotas-before-writing

**Comment by Jesus89** [comment]
Done. It will be available in the next stable release 1.0.5
