### ISSUE TITLE
update readthedocs builds

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#590]
in readthedocs, `latest` is failing to build due to the `carto` dependency in the [requirements-docs.txt](https://github.com/CartoDB/cartoframes/blob/master/requirements-docs.txt) not being inline with what's in the main [requirements.txt](https://github.com/CartoDB/cartoframes/blob/master/requirements.txt), which is a carto python sdk version that's unreleased.

Besides this, I got a failure with a message I hadn't seen before -- looks like we can do more to update the config:
> Configure your documentation builds! Adding a [.readthedocs.yml](https://docs.readthedocs.io/page/config-file/v2.html) file to your project is the recommended way to configure your documentation builds. You can declare dependencies, set up submodules, and many other great features.

**Comment by Jesus89** [comment]
Can we close this one @andy-esch ?

**Comment by andy-esch** [comment]
Yes
