### ISSUE TITLE
Include description columns in `data` requests

### ISSUE THREAD

**Issue by alrocar** [CartoDB/cartoframes#593]
Description columns are removed from the request because the copyto query was failing.

The problem may be due to copyto does not support `POST` requests.

To test this:

- Remove the `FIXME` in `cc.data` method
- Run the `test_data` test

**Comment by javitonino** [comment]
Why is this related with POST? Query length?

**Comment by alrocar** [comment]
Yes I was assuming it was because the query length. We were including the whole columns descriptions in the DO query, but as per [this comment](https://github.com/CartoDB/cartoframes/pull/592#discussion_r272806022) it may be not necessary.

SO I guess we can remove the FIXME and close this issue. 

Eventually the `POST` issue may be a problem, but I guess this is not something we have to fix in CARTOframes.
