### ISSUE TITLE
Make integration part of main library (No Contrib)

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartoframes#597]
**Blocked**

Context
===

Once we've defined the new API
- [x] Remove the `contrib` directory
- [x] Remove references to `contrib` from the documentation
    - [x] [contrib](https://cartoframes.readthedocs.io/en/stable/contrib.html) 
    - [x] [index](https://cartoframes.readthedocs.io/en/stable/index.htm)
    - [x] [vector module](https://cartoframes.readthedocs.io/en/stable/cartoframes.contrib.vector.html)
- [x] Remove references to `contrib` from [experimental features](https://github.com/CartoDB/cartoframes/blob/master/README.rst#experimental-features)

**Comment by andy-esch** [comment]
We'll need to remove all references to `contrib` from the documentation, including the section on experimental features: https://github.com/CartoDB/cartoframes/blob/master/README.rst#experimental-features

**Comment by Jesus89** [comment]
Closed in https://github.com/CartoDB/cartoframes/pull/662
