### ISSUE TITLE
Default zooming and bounds behaviour

### ISSUE THREAD

**Issue by jorgesancha** [CartoDB/cartoframes#598]
Every single map zooms to the bounds of the data and you get weird behaviour - for instance when you only have a point.

cc @rjimenezda @makella @andy-esch

**Comment by elenatorro** [comment]
Can we close this?

**Comment by andy-esch** [comment]
We haven't addressed the case where there's a single point and the zoom goes in way too far

**Comment by Jesus89** [comment]
We have maxZoom in fitBounds so we can close this.

https://github.com/CartoDB/cartoframes/blob/develop/cartoframes/assets/templates/viz/map.js.j2#L56
