### ISSUE TITLE
CARTOframes stats

### ISSUE THREAD

**Issue by oleurud** [CartoDB/cartoframes#601]
We have to allow searches in Kibana about the CARTOframes usage:
- CARTOframes version (right now we are adding a parameter in the URL (for example: `/api/v2/sql?q=SELECT...&api_key=xxx&client=cartoframes_0.5.5`) and forcing the requests using GET)
- TBD

**Comment by oleurud** [comment]
It seems `CARTOframes version` is solved by @alrocar using User-Agent HTTP Header:
- https://github.com/CartoDB/cartoframes/pull/592/commits/9c73e212e4aeec991ef830fc02d005d7dba0177d
- CartoDB/carto-python#111

So, if we don't need to save more things, this issue can be closed

**Comment by alrocar** [comment]
@oleurud can we close this?

**Comment by andy-esch** [comment]
I can pull stats in kibana with the header now fyi
