### ISSUE TITLE
iframe `frameborder="0"` style updates

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#602]
Setting the iframe attribute `frameborder="0"` looks much nicer in the notebook:
<img width="1289" alt="Screen Shot 2019-04-09 at 8 59 29 PM" src="https://user-images.githubusercontent.com/1041056/55844311-abb3d200-5b0a-11e9-84a6-2374ad5765c7.png">

Compared to the default:
<img width="1284" alt="Screen Shot 2019-04-09 at 8 59 54 PM" src="https://user-images.githubusercontent.com/1041056/55844317-b53d3a00-5b0a-11e9-8388-be61b102e14e.png">

Besides this, there is probably room for improvement of the iframe styles.

cc @rjimenezda @elenatorro

**Comment by elenatorro** [comment]
Totally 💖 Last Monday @makella mentioned this in the meeting, and @rjimenezda has started to try some things. +1 for this!
