### ISSUE TITLE
CartoContext.read not copying schema from pg

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#605]
When doing a `CartoContext.read`, the expectation is that the `statefips` and `countyfips` in [this table](https://team.carto.com/u/eschbacher/dataset/unemployment_bls_county_2017) will stay as strings (`object` in pandas), but they are converted to `int64` instead:
<img width="744" alt="Screen Shot 2019-04-10 at 2 58 41 PM" src="https://user-images.githubusercontent.com/1041056/55906066-62629180-5ba1-11e9-8bb1-ada62faf9048.png">

Selecting from that table with `CartoContext.query` gives the correct dataframe schema.

cc @oleurud

**Comment by oleurud** [comment]
We could change the `copy_to` to a `copy_from` similar fashion, casting each row, or maybe we could do it in the `_clean_dataframe_from_carto` function (I am not sure if it works as we expect or if we are going to lose data, in a fast check it seems ok)

**Comment by andy-esch** [comment]
It's also possible to pass in the types in the `pd.read_csv` function like so:
`pd.read_csv(response, dtypes={'col1': int, 'col2': str, 'col3': float, ...})`

**Comment by alrocar** [comment]
Looks like we can do the whole `postprocess_dataframe` in the `read_csv` method. As per the [docs](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html) we can specify:

- The `dtype` dict (as @andy-esch pointed out)
- The index column
- The true and false values (for booleans)
- A converters dict with functions to transform data

**Comment by andy-esch** [comment]
And it looks like the `parse_dates` flag will do attempt to do the date cols but return them unaltered (`object` type) if it fails on a column-by-column basis.

**Comment by alrocar** [comment]
Wait for my next PR 🔥😁

**Comment by alrocar** [comment]
We should use a query like this instead of the fields attribute in an SQL API response, otherwise we can't distinguish between int and float for example.

```
select column_name, data_type from information_schema.columns where table_name = '{tablename}';
```

**Comment by alrocar** [comment]
We have to re-implement the `get_columns` method used [here](https://github.com/CartoDB/cartoframes/blob/master/cartoframes/context.py#L448) which is currently doing an SQL API query.

**Comment by andy-esch** [comment]
Getting the real pg types instead of the simplified carto ones sounds good to me.

Kinda related: There's an open issue about that in the carto-python sdk for use with SQLClient: https://github.com/CartoDB/carto-python/issues/84

**Comment by andy-esch** [comment]
BTW, there are quirks about pandas dtypes. One I know is that an int column cannot have null/None/np.nan values, so it needs to be converted to float/np.float64/etc.
