### ISSUE TITLE
Implement Airship Legends

### ISSUE THREAD

**Issue by jorgesancha** [CartoDB/cartoframes#610]
Part of cartodb/product#313

**Comment by Jesus89** [comment]
Related to https://github.com/CartoDB/cartoframes/issues/693, https://github.com/CartoDB/cartoframes/issues/695 and https://github.com/CartoDB/cartoframes/issues/694.

**Comment by Jesus89** [comment]
Closed:
- https://github.com/CartoDB/cartoframes/pull/712
- https://github.com/CartoDB/cartoframes/pull/721
