### ISSUE TITLE
Style missing values in Legends and on map

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#613]
Missing values are an important thing to highlight in data science. To help with this, we should offer a missing value style (usually grey) like so:
<img width="415" alt="Screen Shot 2019-04-14 at 11 23 09 AM" src="https://user-images.githubusercontent.com/1041056/56095138-c1791c80-5ea7-11e9-9e8d-41bab76f47af.png">

It'd be ideal if all ramps automatically took care of this, and then this value should be added to legends as the bottom-most value, where it has a grey swatch next to the text 'missing values'

cc @elenatorro @rjimenezda

**Comment by elenatorro** [comment]
In CARTO VL we've a way to define the style of these missing values, which we call `others`. There's a default `others` value for each type (default color, default icon, default label...) And these default values can be also overwritten.

**Comment by andy-esch** [comment]
Great :) By default does it go to the first/lowest value of the color scheme?
<img width="318" alt="Screen Shot 2019-04-15 at 8 08 42 AM" src="https://user-images.githubusercontent.com/1041056/56131565-cb595900-5f55-11e9-8a31-100f25c1d51d.png">

**Comment by elenatorro** [comment]
In the case of a CartoColors Palette, yes :) . It's explained in detail in the [ramp expression reference](https://carto.com/developers/carto-vl/reference/#cartoexpressionsramp)

> The "others" value is setted by default, depending on the output type:
If it is "Number", the "others" value is 1.
If it is "Color" from a color array (i.e: [ red, yellow, green ] ), the "others" value is the gray color.
If it is "Color" from a cartocolor palette (i.e: Prism), the "others" value is the last color of the palette.
If it is "Image", the "others" value is a circle.
If we add a third parameter, the "others" default value will be overridden by this one

**Comment by elenatorro** [comment]
@makella solved this by filtering (through the `filter` property) null values. I think we could add it as a helper. What do you think?

**Comment by makella** [comment]
First, sorry... didn't realize there was an issue open for this here :/ cross posted in the VL repo as well.  @elenatorro the one issue I see is if we have a helper that filters nulls, is that those values will be filtered out of the view vs. symbolized as "others" but maybe there is something we can do inside the color classed/unclassed helper methods themselves. We can talk through some ideas next week! Once we have a sense for that, we can ping the legend ticket to account for the no data values as Andy points out above.

**Comment by Jesus89** [comment]
Related to https://github.com/CartoDB/carto-vl/issues/1337

**Comment by makella** [comment]
also related to: https://github.com/CartoDB/cartoframes/issues/1131

**Comment by Jesus89** [comment]
https://app.clubhouse.io/cartoteam/story/93694/render-null-values

**Comment by Jesus89** [comment]
This is fixed in the new CF version using WebSDK. It will be available on the next 1.1 release.
