### ISSUE TITLE
Default add legend for maps with > 1 layers, even if not ramped

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#614]
It's important to have legends to tell the user the meaning of different layers, even if those layers do not have ramps applied to them.
<img width="793" alt="Screen Shot 2019-04-14 at 12 05 13 PM" src="https://user-images.githubusercontent.com/1041056/56095732-c04aee00-5ead-11e9-8c7d-b9b7b83b8826.png">

cc @rjimenezda @elenatorro

**Comment by Jesus89** [comment]
This is already implemented with the `default_legend`param
