### ISSUE TITLE
globalQuantiles specified but viewportQuantiles is used

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartoframes#616]
I'm trying to use globalQuantiles to classify polygons with sequential color ramp, but the classification looks like it's changing when the map view changes.

It looks like global vs viewport classification was being worked on in VL repo, maybe CARTOFrames issue is related?

https://github.com/CartoDB/carto-vl/issues/1275#issuecomment-466586846
https://github.com/CartoDB/carto-vl/pull/1281#issuecomment-470048194

### Code snippet that produced the error

```
qSFR = '''
      SELECT * FROM la_join
      WHERE specificusetype = 'Single Family Residence'
      '''

vector.vmap(
    [vector.QueryLayer(
        qSFR,
        color='ramp(globalQuantiles($saleprice, 7), sunset)',
        strokeWidth='ramp(zoomrange([12,14]),[0,0.7])',
        strokeColor=colorRamp,
        interactivity={
            'cols': ['formatted_saleprice','formatted_size'],
            'header': ['<h2>Single Family Residence<h2>', ],
            'event': 'hover'
        }
    ),
    ],
    context=cc,
    basemap=vector.BaseMaps.voyager
)
```

### Relevant error messages

No error messages, but a polygon's classification should not change on zoom if Global Classification is used. 

Here's an example showing that a polygon's classification is changing as what's included in the viewport changes on zoom:

![globalQuantilesCF](https://user-images.githubusercontent.com/1779444/56155865-e47bfd00-5f89-11e9-82de-ff1a1b15b84c.gif)

### cartoframes version (find it with print(cartoframes.__version__))

'0.9.2'

### Python version (e.g., 3.5, 2.7, etc.)

3.7.1

### Operation system (Windows, Linux, etc.)

Using Docker environment on a Mac:
~~https://github.com/mbforr/docker-cartoframes~~
from private end-to-end-demo repo

**Comment by ztephm** [comment]
For comparison here's what viewportQuantiles looks like with same data:

`color='ramp(viewportQuantiles($saleprice, 7), sunset)';`

![viewportQuantilesCF](https://user-images.githubusercontent.com/1779444/56157566-d4661c80-5f8d-11e9-820e-082f9da8b762.gif)

**Comment by makella** [comment]
heyyy @ztephm interesting! 

The two issues you referenced were related to aggregations and global/viewport operations so I don't think that is what is happening here. 

Two questions:
what version of VL is this version of cartoframes using?
have you tried this outside of cartoframes to see if it is cartoframes specific?

The reason I ask is because looking at a similar example of global classification methods from the dev center (https://carto.com/developers/carto-vl/examples/#example-style-by-number) I'm seeing the expected global behavior.

**Comment by makella** [comment]
also, is that area mulit-polygon? seeing the polygons turn into different shapes makes me think maybe there are multiple geometries there?

**Comment by andy-esch** [comment]
@makella v1.1.1
https://github.com/CartoDB/cartoframes/blob/v0.9.2/cartoframes/assets/vector.html#L7-L8

**Comment by elenatorro** [comment]
Hi @ztephm, I think it's happening what @makella says.  Could you please test it as CARTO VL code? I'm sure that if it's an issue, then it has to be resolved from the CARTO VL side.

This an index.html file with the query & viz you've sent but translated into CARTO VL code, you'd only need to change the credentials:

```js
    carto.setDefaultAuth({
      username: '',
      apiKey: ''
    });
```
https://gist.github.com/elenatorro/ff01223b03c02baf2ca4dad64c0e2dba

**Comment by ztephm** [comment]
Ah OK thanks, there are many duplicate polygons. I'm seeing the proper behavior in VL.

In CARTOFrames (version 0.9.2) I am getting better results when I use a globalQuantiles on a smaller dataset made from the results of the original query: `la_sfr` = 123,702 records. 

However, the far left polygon's bin still changes on zoom, I guess because of aggregation?

![cftestsimple](https://user-images.githubusercontent.com/1779444/56230430-37b58480-604a-11e9-9b7a-cc725d801912.gif)

When I use the original query with WHERE clause applied to a larger dataset (`la_join` = 142,592 records) though, and I set opacity to 1 so that we are only seeing the top polygon, I don't understand why its color is changing on zoom with globalQuantiles:

![matts](https://user-images.githubusercontent.com/1779444/56230911-3cc70380-604b-11e9-8900-e494077c6dec.gif)

Shouldn't globalQuantiles take all of the overlapping polygons into account, so that the top visible polygon's class wouldn't change on zoom anyway?


### Tests

#### Duplicate polygons

Total of 30 separate MultiPolygons, for what looks like 6 (the MultiPolygons do not have components outside of the area shown below):

![overlap](https://user-images.githubusercontent.com/1779444/56226686-c4a81000-6041-11e9-9184-d271f3762b1a.gif)

#### VL Test 1

In CARTO VL with opacity=1, I'm not seeing the polygon's color/classification bin change on zoom:

![classtest1](https://user-images.githubusercontent.com/1779444/56227078-a42c8580-6042-11e9-9711-2b13f1cee0a7.gif)

#### VL Test 2

Also I'm not seeing it change classes when testing the CARTO VL equivalent of the CARTOFrames code I used:

![classtest2](https://user-images.githubusercontent.com/1779444/56227706-181b5d80-6044-11e9-8a22-3d8ffa43b176.gif)

#### CARTOFrames Test with simple SELECT:

![cftestsimple](https://user-images.githubusercontent.com/1779444/56230248-e2797300-6049-11e9-9c8f-e24c75b6cb09.gif)


### Code

#### VL Test 1 Code
*la_sfr dataset is the result of*
*`SELECT * FROM la_join WHERE specificusetype = 'Single Family Residence'`*

```
<!DOCTYPE html>
<html>

<head>
  <title>Test Polygon | CARTO</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta charset="UTF-8">
  <!-- Include CARTO VL JS -->
  <script src="https://libs.cartocdn.com/carto-vl/v1.2.4/carto-vl.min.js"></script>
  <script src="https://api.tiles.mapbox.com/mapbox-gl-js/v0.52.0/mapbox-gl.js"></script>
  <link href="https://api.tiles.mapbox.com/mapbox-gl-js/v0.52.0/mapbox-gl.css" rel="stylesheet" />
  <style>
      body {
        margin: 0;
        padding: 0;
      }
      #map {
        position: absolute;
        height: 100%;
        width: 100%;
      }
    </style>
</head>

<body>
  <div id="map"></div>
  <script>
    const map = new mapboxgl.Map({
      container: 'map',
      style: carto.basemaps.voyager,
      center: [-118.36137184873225, 34.01970789894275],
      zoom: 16,
      scrollZoom: true
    });
    const nav = new mapboxgl.NavigationControl({
      showCompass: false
    });
    map.addControl(nav, 'top-left');

    carto.setDefaultAuth({
      username: 'stephaniemongon',
      apiKey: '7VUg41LvSKfEGe4AfW92Ng'
    });
    const source = new carto.source.SQL(`SELECT * FROM la_sfr`);
    const viz = new carto.Viz(`
      color: opacity(ramp(globalQuantiles($saleprice, 7), sunset), 1)
      strokeWidth: 1
      strokeColor: #B3ABA1
    `);
    const layer = new carto.Layer('layer', source, viz);
    layer.addTo(map, 'watername_ocean');
  </script>
</body>

</html>
```

#### VL Test 2 Code

```
<!DOCTYPE html>
<html>

<head>
  <title>Test Polygon | CARTO</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta charset="UTF-8">
  <!-- Include CARTO VL JS -->
  <script src="https://libs.cartocdn.com/carto-vl/v1.2.4/carto-vl.min.js"></script>
  <script src="https://api.tiles.mapbox.com/mapbox-gl-js/v0.52.0/mapbox-gl.js"></script>
  <link href="https://api.tiles.mapbox.com/mapbox-gl-js/v0.52.0/mapbox-gl.css" rel="stylesheet" />
  <style>
      body {
        margin: 0;
        padding: 0;
      }
      #map {
        position: absolute;
        height: 100%;
        width: 100%;
      }
    </style>
</head>

<body>
  <div id="map"></div>
  <script>
    const map = new mapboxgl.Map({
      container: 'map',
      style: carto.basemaps.voyager,
      center: [-118.36137184873225, 34.01970789894275],
      zoom: 16,
      scrollZoom: true
    });
    const nav = new mapboxgl.NavigationControl({
      showCompass: false
    });
    map.addControl(nav, 'top-left');

    carto.setDefaultAuth({
      username: 'stephaniemongon',
      apiKey: '7VUg41LvSKfEGe4AfW92Ng'
    });
    const source = new carto.source.SQL(`SELECT * FROM la_sfr`);
    const viz = new carto.Viz(`
      @colorRamp: ramp(globalQuantiles($saleprice, 7), sunset);

      color: ramp(zoomrange([0,16]),[opacity(@colorRamp,1),opacity(@colorRamp,0.7)])
      strokeWidth: ramp(zoomrange([12,14]),[0,0.7])
      strokeColor: @colorRamp
    `);
    const layer = new carto.Layer('layer', source, viz);
    layer.addTo(map, 'watername_ocean');
  </script>
</body>

</html>
```

#### CARTOFrames Test with simple SELECT code:

```
qSFR = '''
      SELECT * FROM la_sfr
      '''
colorRamp='ramp(globalQuantiles($saleprice, 7), sunset)';

vector.vmap(
    [vector.QueryLayer(
        qSFR,
        color='opacity('+colorRamp+',1)',
        strokeWidth='ramp(zoomrange([12,14]),[0,0.7])',
        strokeColor=colorRamp,
        interactivity={
            'cols': ['formatted_saleprice','formatted_size'],
            'header': ['<h2>Single Family Residence<h2>', ],
            'event': 'hover'
        }
    ),],
    context=cc,
    basemap=vector.BaseMaps.voyager
)
```

**Comment by makella** [comment]
@ztephm thanks for the detailed look!

Just to make sure, sounds like you aren't seeing this problem with standalone CARTO VL (v1.2.4) but are seeing it inside of CARTOframes v9.0.2 that uses CARTO VL (v1.1.1)

**Comment by ztephm** [comment]
^ Yep. I'm also not seeing the issue in standalone VL v1.1.1 when I use `SELECT * FROM la_sfr` source. However when I use the same standalone VL v1.1.1 code with Matt's dataset/query I see the issue happen (examples below).

It's strange because the smaller `la_sfr` dataset is just the result from the `la_join` query. They should have the same polygons+saleprice, so the classification should be the same as long as I'm using the same globalQuantiles expression, no?

`SELECT count(*) FROM la_join WHERE specificusetype = 'Single Family Residence'`
= 123,702 polygons

`SELECT count(*) FROM la_sfr` 
= 123,702 polygons


#### SELECT * FROM la_sfr source

![vl111](https://user-images.githubusercontent.com/1779444/56244191-4ca21000-606a-11e9-80e4-1fa85f228693.gif)

```
<!DOCTYPE html>
<html>

<head>
  <title>Test Polygon | CARTO</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta charset="UTF-8">
  <!-- Include CARTO VL JS 
  <script src="https://libs.cartocdn.com/carto-vl/v1.2.4/carto-vl.min.js"></script>-->
  <script src="https://libs.cartocdn.com/carto-vl/v1.1.1/carto-vl.min.js"></script>
  <script src="https://api.tiles.mapbox.com/mapbox-gl-js/v0.52.0/mapbox-gl.js"></script>
  <link href="https://api.tiles.mapbox.com/mapbox-gl-js/v0.52.0/mapbox-gl.css" rel="stylesheet" />
  <style>
      body {
        margin: 0;
        padding: 0;
      }
      #map {
        position: absolute;
        height: 100%;
        width: 100%;
      }
    </style>
</head>

<body>
  <div id="map"></div>
  <script>
    const map = new mapboxgl.Map({
      container: 'map',
      style: carto.basemaps.voyager,
      center: [-118.36137184873225, 34.01970789894275],
      zoom: 16,
      scrollZoom: true
    });
    const nav = new mapboxgl.NavigationControl({
      showCompass: false
    });
    map.addControl(nav, 'top-left');

    carto.setDefaultAuth({
      username: 'stephaniemongon',
      apiKey: '7VUg41LvSKfEGe4AfW92Ng'
    });
    const source = new carto.source.SQL(`SELECT * FROM la_sfr`);
    const viz = new carto.Viz(`
      @colorRamp: ramp(globalQuantiles($saleprice, 7), sunset);

      // color: ramp(zoomrange([0,16]),[opacity(@colorRamp,1),opacity(@colorRamp,0.7)])
      color: opacity(@colorRamp,1)
      strokeWidth: ramp(zoomrange([12,14]),[0,0.7])
      strokeColor: @colorRamp
    `);
    const layer = new carto.Layer('layer', source, viz);
    layer.addTo(map, 'watername_ocean');
  </script>
</body>

</html>
```

#### SELECT * FROM la_join WHERE specificusetype = 'Single Family Residence' source

![mattsv111](https://user-images.githubusercontent.com/1779444/56244680-73ad1180-606b-11e9-942f-cebbf0a3767b.gif)

```
<!DOCTYPE html>
<html>

<head>
  <title>Test Polygon | CARTO</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta charset="UTF-8">
  <!-- Include CARTO VL JS 
  <script src="https://libs.cartocdn.com/carto-vl/v1.2.4/carto-vl.min.js"></script>-->
  <script src="https://libs.cartocdn.com/carto-vl/v1.1.1/carto-vl.min.js"></script>
  <script src="https://api.tiles.mapbox.com/mapbox-gl-js/v0.52.0/mapbox-gl.js"></script>
  <link href="https://api.tiles.mapbox.com/mapbox-gl-js/v0.52.0/mapbox-gl.css" rel="stylesheet" />
  <style>
      body {
        margin: 0;
        padding: 0;
      }
      #map {
        position: absolute;
        height: 100%;
        width: 100%;
      }
    </style>
</head>

<body>
  <div id="map"></div>
  <script>
    const map = new mapboxgl.Map({
      container: 'map',
      style: carto.basemaps.voyager,
      center: [-118.36137184873225, 34.01970789894275],
      zoom: 16,
      scrollZoom: true
    });
    const nav = new mapboxgl.NavigationControl({
      showCompass: false
    });
    map.addControl(nav, 'top-left');

    carto.setDefaultAuth({
      username: 'mforrest-isolines',
      apiKey: 'mattsapikey'
    });
    const source = new carto.source.SQL(`SELECT * FROM la_join WHERE specificusetype = 'Single Family Residence'`);
    const viz = new carto.Viz(`
      @colorRamp: ramp(globalQuantiles($saleprice, 7), sunset);

      // color: ramp(zoomrange([0,16]),[opacity(@colorRamp,1),opacity(@colorRamp,0.7)])
      color: opacity(@colorRamp,1)
      strokeWidth: ramp(zoomrange([12,14]),[0,0.7])
      strokeColor: @colorRamp
    `);
    const layer = new carto.Layer('layer', source, viz);
    layer.addTo(map, 'watername_ocean');
  </script>
</body>

</html>
```

**Comment by ztephm** [comment]
FYI I updated the comment above re: Docker environment, it's in Private end-to-end-demo repo—still uses CARTOFrames 0.9.2 though.

**Comment by ztephm** [comment]
For comparison here's what happens when I use the exact same standalone VL v1.1.1 code with `SELECT * FROM la_join`

![mattsv111-wholedataset](https://user-images.githubusercontent.com/1779444/56247455-c807bf80-6072-11e9-9eb1-8786244ad244.gif)

**Comment by elenatorro** [comment]
Hi! 👋 what's the status of this issue? Is it still happening?

**Comment by ztephm** [comment]
Yes, classification still changes on zoom when using globalQuantiles in CARTOFrames v0.9.2:

![cfzoom](https://user-images.githubusercontent.com/1779444/56740748-88f6ff80-673f-11e9-9114-ef7c2be9f4ec.gif)

If there's another version of CARTOFrames I should use that integrates an updated version of VL though just let me know.

**Comment by andy-esch** [comment]
@ztephm, there are a lot of updates in the `develop` branch, where you could test this more. Unfortunately it takes a bit of time to get setup.

In a virtualenv, install these things:
```
$ pip install git+https://github.com/cartodb/carto-python.git#egg=carto
$ pip install unidecode jinja2 jupyter
$ pip install git+https://github.com/cartodb/cartoframes.git@develop#egg=cartoframes
```

**Comment by elenatorro** [comment]
I'm going to add it as a CARTO VL issue because it should be tackled from this project. Once solved, then we'd update the version in CARTOFrames. Thank you very much for the update!

**Comment by ztephm** [comment]
OK thank you both, closing in favor of https://github.com/CartoDB/carto-vl/issues/1335
