### ISSUE TITLE
Give warning if using master api key when creating a map?

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#617]
We need to help users understand that using a master api key can have some bad consequences, especially if the notebook is publicly shared.

Ideally, we should have a mechanism where a user can create a map and optionally get a new read-only api key generated that's included in the credentials instead of the master key.

Maybe there's a workflow with the CartoContext that can educate the user about this. Either way, we should offer some functionality to create new project keys easily to help protect master api keys 

Related #542 

cc @jorgesancha

**Comment by Jesus89** [comment]
This is not possible since the api key for publication is generated internally.
