### ISSUE TITLE
schema not updated for org accounts

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#618]
The `schema` is not updated in `Dataset` class:
https://github.com/CartoDB/cartoframes/blob/7c039a3bf43472cda03c5c522e33805702d52ab8/cartoframes/datasets.py#L29-L36

This leads to problems doing Data Observatory operations among others.

cc @alrocar

**Comment by andy-esch** [comment]
@oleurud, I think you tackled this already?

**Comment by oleurud** [comment]
Yes, we have done https://github.com/CartoDB/cartoframes/issues/707 & https://github.com/CartoDB/cartoframes/issues/690 I hope is fine now with the `schema`
