### ISSUE TITLE
Unify `Style` API

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartoframes#619]
Context
===

We currently provide the possibility of using a list, a dictionary or a string to define the style of a layer.

After several comments and discussions, we want to unify these options and be consistent with the rest of the parameters, but also with CARTO VL.

Some of the ideas that came up in previous issues, meetings and PRs:

- [x] Use always a dict / viz string
- [x] Use always camelCase
- [x] Use a Style class --> in order to provide style helpers in the future

* Simple layer setup

```python
 Layer( 'world_population_2015', Style({ 'color': 'turquoise'}))
```

* Map setup using a style dict

```python
Map([
   Layer(
        'world_population_2015',
        Style({
             'color': 'turquoise',
             'strokeColor': 'white'
        })
    )],
    context=context
)
```

* Map setup using a style string

```python
Map([
   Layer(
        'world_population_2015',
        Style("""
            color: turquoise
            strokeColor: white
        """)
    )],
    context=context
)
```

**Comment by makella** [comment]
hiii @elenatorro the option that feels most comfortable to understand/work with is the dict + camel case.

**Comment by makella** [comment]
Will wait to comment on the style class until we see how the helper methods will be integrated. :)

**Comment by elenatorro** [comment]
It seems we have a winner format! :)

**Comment by andy-esch** [comment]
Yep, looks good to me! I like

```python
Layer('world_population_2015', {'color': 'turquoise'})
Layer(Dataset('world_population_2015'), {'color': 'turquoise'})
Layer(Dataset('world_population_2015'), Style({'color': 'turquoise'}))
Layer('world_population_2015', "color: torquoise")
```
