### ISSUE TITLE
deprecate _auth_send

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#624]
The [_auth_send](https://github.com/CartoDB/cartoframes/blob/382adee62510bbac273c26c199d05832930e85cf/cartoframes/context.py#L1568-L1578) method was created to make it easier to do API calls to CARTO. As more functionality is in the Python SDK, `_auth_send` has largely been replaced, and now only exists in `CartoContext.map`-related functions. It'd probably be a good idea to totally deprecate/remove this method as it's probably not as reliable as SDK clients. 

One quirk of that method is that it looks at the JSON responses to see if there's an error key. Sometimes responses are partially successful, but if a bad geom (for example) is found along the way, the partial response is returned without throwing an error.

**Comment by oleurud** [comment]
It will be resolved by https://github.com/CartoDB/cartoframes/issues/807
