### ISSUE TITLE
Let `CartoContext.execute` take in 1+ queries

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#628]
Just like the SQL Batch API takes in chains of queries, it'd be great if we could list an arbitrary number of queries in `CartoContext.execute`. For example, the signature could be changed to:
```python
def execute(*query):
```

And used like:
```python
table_creation = 'create table ct as ...'
cdb_q = 'select cdb_cartodbfytable(...)'
cc.execute(table_creation_query, cdb_q)
```

And we could either iterate over all the queries listed or put them all into the same batch call as a chain. It also brings up the question of how easily we enable users to cartodbfy tables, which is both not an obvious thing to do, and the syntax/query is tedious and annoying to write. Should we have a flag in `execute` for cartodbfying tables? Not sure but I'm leaning to yes.

cc @alrocar

**Comment by Jesus89** [comment]
There is no CartoContext anymore, so we can close this one.

Btw, you can run multiple SQL queries with `BEGIN; ... COMMIT;`. Maybe this fits your needs.
