### ISSUE TITLE
Allow "None" and color values for basemaps

### ISSUE THREAD

**Issue by makella** [CartoDB/cartoframes#635]
Context
===

There will be times where a user may not want a basemap and/or would want to add their own layer of contextual geography.

Since basemaps are Mapbox GL, should we have some sort of "helper" for no basemap? I'm assuming this would default to white or black with an option available to change the color. 

[ ] Empty basemap

Allows to display a map without basemap

```python
Map(
    [Layer(Dataset('populated_places')], 
    context=context,
    basemap=None
)
```

[ ] Color basemap

Use a single background color 

```python
Map(
    [Layer(Dataset('populated_places')], 
    context=context,
    basemap='#FABADA'
)
```

**Comment by andy-esch** [comment]
I added support beyond our basemaps in the original `vmap` function: https://cartoframes.readthedocs.io/en/stable/contrib.html#cartoframes.contrib.vector.vmap It takes a dictionary of a mvt source and an optional token (mostly for mapbox maps). 

I also opened this a while back but didn't write much: https://github.com/CartoDB/cartoframes/issues/509

**Comment by andy-esch** [comment]
I also want a mvt source for mars terrain

**Comment by makella** [comment]
oops sorry didn't realize there was already an open issue! if you prefer, we can close this or vice-versa. Regardless I really like the idea of the no basemap option and adding other basemaps (including Mars) :)

**Comment by andy-esch** [comment]
I'll close the other as this already has more content. But I agree 100% that no basemaps means users can be more creative on visualizations. It also means more art can happen, which is something I'd love to see in cartoframes :)

**Comment by elenatorro** [comment]
+1 🎉

**Comment by andy-esch** [comment]
I also wonder if just letting `basemap=False` or `basemap=None` is all we need instead of a helper.

**Comment by elenatorro** [comment]
I'd go for:
- `basemap=False` for no basemap
- `basemap='#FABADA'` to set the color

**Comment by makella** [comment]
like!!

**Comment by Jesus89** [comment]
Hi!

I have made research in the MGL API. These are the map styles we need to use in these cases:

**basemap=False**
```js
style: {
  'version': 8,
  'sources': {},
  'layers': []
}
```

**basemap='#0F0'**
```js
style: {
  'version': 8,
  'sources': {},
  'layers': [{
      'id': 'background',
      'type': 'background',
      'paint': {
        'background-color': '#0F0'
      }
  }]
}
```

**Comment by makella** [comment]
niiiiice!!

**Comment by Jesus89** [comment]
I have implemented basemap= None, True, False, 'string color'.

![](https://user-images.githubusercontent.com/2227572/58008862-90ff5080-7aed-11e9-97ab-ade068203866.png)

![](https://user-images.githubusercontent.com/2227572/58008842-88a71580-7aed-11e9-974e-52b0b7bb6214.png)
