### ISSUE TITLE
fix default cartocss rule avoid centroid drawing

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#64]
<img width="929" alt="screen shot 2017-04-12 at 14 07 44" src="https://cloud.githubusercontent.com/assets/1041056/24972474/7ed31c28-1f89-11e7-9bdd-32cd7d5f12b5.png">

Can be avoided by adding additional filter (`['mapnik::geometry_type'=1]`) in current cartocss for markers:

```
"#layer['mapnik::geometry_type'=1]": {
    'marker-width': size_style,
    'marker-fill': color_style,
    'marker-fill-opacity': '1',
    'marker-allow-overlap': 'true',
    'marker-line-width': '0.5',
    'marker-line-color': line_color,
    'marker-line-opacity': '1',
},
```

cc @dmed256

**Comment by dmed256** [comment]
Pushed in fd7db5980

**Comment by andy-esch** [comment]
I updated further to remove the default styling since this will draw centroids for lines/polygons (like in the screen cap above). We need to have distinct styles for each geometry type -- other geoms won't overwrite 'em, leading to undesirable artifacts. Handled in https://github.com/CartoDB/cartoframes/pull/59/commits/d07cbc221c4783d12fa2963a98aa8a98f3071e0c
