### ISSUE TITLE
Templates - Interactivity

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartoframes#641]
Related issue: https://github.com/CartoDB/cartoframes/issues/596

- [ ] Research: how could we improve the current popup
        - popup style
        - how to display content depending on the type of the columns or properties
- [ ] API: as discussed in [this PR comment](https://github.com/CartoDB/cartoframes/pull/586#discussion_r275461880): don't use 'cols' anymore:

```python
interactivity={
    'click': ['$prop0', '@var1'],
    'hover': ['$prop1', '@var0'],
}
```

Can be related / solved with this task: https://github.com/CartoDB/carto-vl/issues/1278

**Comment by VictorVelarde** [comment]
I guess this should be closed now. Feel free to reopen @elenatorro
