### ISSUE TITLE
Templates - labels

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartoframes#642]
Related issue: https://github.com/CartoDB/cartoframes/issues/596

We should discuss the best way to allow the user display labels. Right now, labels are displayed by using Mapbox GL API. Instead of allowing full style customization, I think we should try something simple that we can improve in future iterations.

Some questions:
- Should we have a number (for example, three: _light_, _dark_ and _primary_) of default labels the user can configure?
- Should we allow font family and font size customization?
- Should we allow full colors and stroke customization?

**Comment by VictorVelarde** [comment]
I would reserve this as an option (probably 'on' by default) just for visualizations created with cluster layer helpers

**Comment by andy-esch** [comment]
Just want to chime in that having auto labels (especially in the helpers) would be pretty killer.

An example is this map I just made, where I wanted even more explicit callouts for what the values are.

<img width="1168" alt="Screen Shot 2019-08-13 at 4 15 23 PM" src="https://user-images.githubusercontent.com/1041056/62974207-b39bbf80-bde5-11e9-9ebb-0e5ffc4912dd.png">

**Comment by VictorVelarde** [comment]
Pinging @cmongut for considering the approach here

**Comment by cmongut** [comment]
👋 Although these options can improve the customization of the final results, I am going to close it until we get enough feedback to consider it.
