### ISSUE TITLE
Templates - animation controls

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartoframes#643]
Related issue https://github.com/CartoDB/cartoframes/issues/596

Context
---

When the visualization contains something that can be animated, we should allow the user to add a simple animation controls widget to pause, stop and modify the animation. We could do something similar to this control widget from the [CARTO VL examples](https://carto.com/developers/carto-vl/examples/#example-add-animation-controls) but using Airship:

![Screenshot 2019-05-03 at 16 08 57](https://user-images.githubusercontent.com/3824953/57142897-ecc39d00-6dbd-11e9-9a3d-4803b7b56cc2.png)

**Comment by VictorVelarde** [comment]
I would go here after a component with: 1 toggle button (play / pause) + range slider, having a label for the time (and probably a format function as parameter).

It would be nice to see how this fits some previous thoughts from @rjimenezda about a simplified timeline

**Comment by andy-esch** [comment]
I think we're good on this one? Close it?

**Comment by VictorVelarde** [comment]
I would say so
