### ISSUE TITLE
Should CartoContext.execute report the status?

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#646]
E.g., should we have a tqdm-like progress bar that updates depending on the state of an execute (batch sql api) job? I could imagine just a progress thing being text ('pending', 'running', 'done', 'failed', etc.) that updates description depending on the status of the job.

cc @alrocar 

related to #639

**Comment by Jesus89** [comment]
There is no CartoContext anymore, so we can close this one.
