### ISSUE TITLE
Helper methods - Basic color/size (default symbology and basemap)

### ISSUE THREAD

**Issue by makella** [CartoDB/cartoframes#648]
- [x] default Basemap

default size/widths for
- [x] points
- [x] lines
- [x] polygons

default colors (see note below)
- [x] points
- [x] lines
- [x] polygons

**Comment by makella** [comment]
### Default basemap:
- dark matter

### Default colors:
- currently, VL uses the same default colors for points, lines, and polygons that Builder does. For right now, we can keep those. I would like to spend some time testing those defaults with the proposed default sizes and also inside of the notebook (aesthetically) and also with legends. 

### Default sizes:
- points:
```
style={
            'width': 'ramp(linear(zoom(),0,20),[2,12])',
            'stroke-width': 'ramp(linear(zoom(),0,18),[0,1])',
            'stroke-color' : 'opacity(#222,ramp(linear(zoom(),0,18),[0,1]))',
        }
```
- lines
TBD

- polygon stroke
TBD

cc @Jesus89 @VictorVelarde @rjimenezda

**Comment by makella** [comment]
- [x] Default width: lines
`'width': 'ramp(linear(zoom(),0,20),[0.25,5])',`

**Comment by makella** [comment]
ok, first set of defaults for points, lines, polys above.

**Comment by Jesus89** [comment]
Implemented in https://github.com/CartoDB/cartoframes/pull/675
