### ISSUE TITLE
Helper methods - Color bins

### ISSUE THREAD

**Issue by makella** [CartoDB/cartoframes#650]
For 
- [x] points
- [x] lines
- [x] polygons

**Comment by makella** [comment]
- **All geometries**
  - `globalQuantiles`
  - 5 bins
  - `bluyl` CARTOColor scheme
  - inherit basic symbology from [basic symbology ticket](https://github.com/CartoDB/cartoframes/issues/648)

- **Color bin ramps by geometry**
  - point
  `'color': 'ramp(globalQuantiles($number,5), reverse(purpor))'`
  - line
  `'color': 'ramp(globalQuantiles($number,5), reverse(purpor))'`
  - polygon
  `'color': 'opacity(ramp(globalQuantiles($number,5), reverse(bluyl)),0.9)'`

**Comment by Jesus89** [comment]
Closed via https://github.com/CartoDB/cartoframes/pull/692
