### ISSUE TITLE
Helper methods - Color continuous

### ISSUE THREAD

**Issue by makella** [CartoDB/cartoframes#651]
For 
- [x] points
- [x] lines
- [x] polygons

**Comment by makella** [comment]
@Jesus89 here are the defaults for color continuous helper:

- point
`'color': 'ramp(linear($number), reverse(sunset))'`
- line
`'color': 'ramp(linear($number), reverse(sunset))'`
- polygon
`'color': 'opacity(ramp(linear($number), reverse(sunset)),0.9)'`

I am using `linear` vs. explicitly casting the attribute because I am wondering if we want to think about giving users the ability to set a min and max. Let's discuss this part when we meet!

thanks!

**Comment by Jesus89** [comment]
Thanks @makella. What legends should we use here for each geometry type?

**Comment by makella** [comment]
hiii @Jesus89 so the legends here would be the "color unclassed" versions in the legends doc

<img width="154" alt="Screen Shot 2019-05-28 at 8 47 53 AM" src="https://user-images.githubusercontent.com/1566273/58487793-73516d00-8125-11e9-8904-b9b1760a7564.png">

**Comment by Jesus89** [comment]
Closed via https://github.com/CartoDB/cartoframes/pull/713
