### ISSUE TITLE
Helper methods - Size continuous

### ISSUE THREAD

**Issue by makella** [CartoDB/cartoframes#653]
For 
- [x] points
- [x] lines

**Comment by makella** [comment]
@Jesus89 as a first go, let's try this for size continuous:

### Points:
`width: ramp(linear(sqrt($number), sqrt(globalMin($number)), sqrt(globalMax($number))), [0.2*zoom(), 8*zoom()])`

### Lines
WIP!


To discuss tomorrow:
- Now that we are using Positron, there are some slight modifications that I want to make to the basic symbology to account for the lighter basemap. I tried to do one of them, but the test failed  so I reverted back
- related, I want to test out some different point colors which may likely result in a change for the "basic" point color from red to something else. What we'll want to make sure is that we pick a color that will work well on its own for basic points, together with the default color for lines and polygons as well as with all other helper method layers. Basically, I'll need to do some testing with all of this! I figure that once we get these size helpers in, I can modify the styles as I'm testing in CF.
- the ordering of symbols `width()` isn't the best option (will show you why) would be better to order by attribute, but since that functionality isn't there yet, I am not including it also even width isn't available to order by with lines. Will show you an example of how helpful this would be (for us to think about for the future).
- would like to add opacity once I figure out the color and I think for both

**Comment by makella** [comment]
As discussed, for now, we aren't going to use `zoom()` we will look at that for a future release where we can have the legends be dynamic as well. Also, we will give the users the ability with our implementation to modify the size ranges in addition to the color of features.

**Comment by Jesus89** [comment]
Done in https://github.com/CartoDB/cartoframes/pull/770
