### ISSUE TITLE
Helper methods - Cluster color bins

### ISSUE THREAD

**Issue by makella** [CartoDB/cartoframes#655]
For
- [x] Points

**Comment by makella** [comment]
@elenatorro @cmongut would like to close this and not implement for the reasons below.

Adding this originally was my mistake. As mentioned in the cluster size helper ticket, we don't want to do [bins](https://github.com/CartoDB/cartoframes/issues/654#issuecomment-517013182) on clusters. 

This is because the point of the clusters is to break apart as you are zooming in and eventually become 1 point. If we do bins, then there will always be a range (1-x) so we will never actually be able to "see" exactly where there is 1 point vs the range of values the 1 point can represent. 

If you look at the example from @elenatorro's notebook and zoom in, you will see what I mean
<img width="867" alt="Screenshot 2019-08-16 at 10 59 53" src="https://user-images.githubusercontent.com/3824953/63156696-8897b280-c015-11e9-8326-b53b196b0f72.png">

**Comment by makella** [comment]
I should also add that since we are doing this on the viewport, the colors reassign themselves once the viewport values have been calculated which is an additional layer of complexity for this map.

**Comment by elenatorro** [comment]
Closing this :)
