### ISSUE TITLE
Layer names

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/cartoframes#665]
From the conversation started in https://github.com/CartoDB/cartoframes/pull/662.

@andy-esch 

> One other thing... @rjimenezda mentioned that it's not nice to have the automatic Layer0, Layer1, etc. titles in the headings on the Legends. One way to get around this is to have an additional Dataset attribute (maybe name) that is optional. In the case of a tablename/dataset, we automatically set the name to be the same as the table name. For the other layers, I'm not sure what a good default would be.

> We could offer to set the name in the constructor, or overwriting the attribute directly (dataset.name = 'foo'). Or even a setter? Not sure.

@rjimenezda 

> I personally see the name more as a Layer property than a Dataset one. Some datasets don't really have an obvious way of getting name (like queries, or geojson?).

> Something like Layer(dataset=Dataset(...), name = 'Readable name')

> On the code generation, when we assign the names to each CARTO VL layer, we should probably use an autogenerated layer name (layer${index}), because the Layer name / id is used internally as far as I know. However, if the CARTOFrames Layer object now contains a name property, we can use that when creating the bridge to override the layer names (there's already a mechanism for this in the bridge)

**Comment by VictorVelarde** [comment]
👍 for name attribute at Layer level. 

If it exists, it can be used for things like the Legend (fallback to Layer0, Layer1... if not set)

**Comment by andy-esch** [comment]
100% agree name should exist at the Layer level (not Dataset)

If it's at all useful, my original legend work had a legend kwarg that simply acted as the layer name: https://github.com/CartoDB/cartoframes/blob/fb8304a93bb3e0eb0cb688c54e0012d015e9ea64/cartoframes/assets/vector.html#L114

**Comment by andy-esch** [comment]
@Jesus89 this seems like another easy win / Nice to Have given the current work we're doing

**Comment by Jesus89** [comment]
This is already covered with the `title` param
