### ISSUE TITLE
Finish Dataset API

### ISSUE THREAD

**Issue by alrocar** [CartoDB/cartoframes#670]
Issue to design / implement the Dataset API.

Based on:
- [first API doc](https://docs.google.com/document/d/1jZDJyx9ebNIPL5g-LVByQxeX1ujw_h-VNnlxnhQ0BKE/edit#bookmark=id.4b6juh43lmrr) 
- [the second version](https://docs.google.com/document/d/1DFNwciC1rCJvWz6EhB1lVzTPdTaF8afJWGL0naIeszk/edit#)

Main tasks:
- [x] optimize Dataset df/gdf https://github.com/CartoDB/cartoframes/issues/704
- [x] use a strategy pattern to delegate logic (LOCAL vs REMOTE, QUERY vs DATAFRAME, etc.) and avoid including diverging logic inside conditionals
- [x] one constructor / factory

**Comment by oleurud** [comment]
About the usage of the strategy pattern: the strategy classes are dynamic because the actions over the strategy interface can change the strategy.

**Comment by oleurud** [comment]
In addition to the factory and the strategy pattern, and taking advantage of them, we have added the possibility of adding new sources dynamically.

What does it mean?

Until now, we are supporting:
- a CARTO Table, 
- a query using CARTO stuff and 
- DataFrames/GeoDataFrames

Now, anyone can extend Dataset with other sources of data. For example:
- CSV files
- other databases
- other services (like bigquery)
