### ISSUE TITLE
add `set_default=True|False` flag to `Context`

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#689]
I'm trying to think through some ways to save people time and confusion on the use of a `Context` object.

For example, should we reduce this code:
```python
context = Context(
    base_url='https://cartovl.carto.com/', 
    api_key='default_public'
)
set_default_context(context)
```
to something like this:
```python
context = Context(
    base_url='https://cartovl.carto.com/', 
    api_key='default_public',
    set_default=True
)
```

Or even more so, should `set_default=True` be the default since this will be the most common use case?

cc @Jesus89

**Comment by Jesus89** [comment]
Hi @andy-esch.

I thought the same idea during the implementation. I think it is a good approach, in this case the context variable won't be needed:

```py
Context(
    base_url='https://cartovl.carto.com/', 
    api_key='default_public',
    set_default=True
)
```

We need to make clear in the documentation that this is an implicit action, so in case you declare two contexts with set_default=True, the valid is the last one:

```py
Context(
    base_url='url 1', 
    api_key='default_public',
    set_default=True
)

Context(
    base_url='url 2', 
    api_key='default_public',
    set_default=True
)
```

I think using set_default=True by default saves some chars but it is too implicit, at least for me. What about moving this to the `set_default_context` function instead?

```py
set_default_context(
    base_url='https://cartovl.carto.com/', 
    api_key='default_public'
)
```

This is compatible with the current api `set_default_context(context)`, it is more explicit and you don't need to create a Context.

**Comment by Jesus89** [comment]
What do you think about the `set_default_context` proposal @andy-esch?

**Comment by andy-esch** [comment]
Sorry for the slow response, back from vacation now (couldn't resist opening a few issues on vacation) :)

Great points thinking through the workflow. 100% agree that it's too implicit the way I suggested.

> What about moving this to the set_default_context function instead?

Sounds like a great idea. Doing this and having a `set_default=False` default in `Context` feels like a good parallel approach to me. Also agree that last one set is the default. I'm also curious how this could fit into the proposal for different contexts (#667)

**Comment by Jesus89** [comment]
Haha those on-vacation tickets are inevitable XD

In this case, I would be more comfortable with the `set_default_context` approach. But I'm not sure about the implementation, because of the Context and Dataset interdependency. Could you take a look at this PR, please? https://github.com/CartoDB/cartoframes/pull/697

Regarding different contexts, I'm not aware of the final approach. There are some things like OAuth and the AFW that will affect the context/s implementation. However, if we have different contexts in the future we can still use the same function.

**Comment by andy-esch** [comment]
👀

**Comment by andy-esch** [comment]
That approach looks clear/clean to me.

A few open questions, mostly around the context feeling like it disappears into a black hole:
1. should `set_default_context` return the default context so a user can explicitly use it later if they want (e.g., `cc = set_default_context(...)`)? The alternative is `cc = Context(...); set_default_context(cc)`, which isn't too hard
2. Should we print a `__repr__` of the context at least after calling `set_default_context`?
3. Or should we just have docs saying the context is in `default_context` which is imported like `from cartoframes.auth import default_context`? This opens the problem that users will directly manipulate it, which is something I don't think we want.

Re different contexts: Agree it should be tabled for now given all the unknowns at this point.

**Comment by Jesus89** [comment]
1. Yeah. I think it is free to return the context, but the proper way is with `c = Context(...)`
2. It depends on (1). But if we return something, a __repr__ is better than `<cartoframes.context.CartoContext at ...>`
3. This `from cartoframes.auth import default_context` is the solution I found to store the context without cylic-deps issues. But I'm not sure if we want to expose this to the user.

**Comment by Jesus89** [comment]
Closed here: https://github.com/CartoDB/cartoframes/pull/697.

We have finally added a `_` to our internal variable, just to follow the "private" convention.
