### ISSUE TITLE
Dataset(tablename) doesn't know the proper schema for a user

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#690]
@oleurud correct me this is already being fixed or if there's another way to do this, but IMO the default schema in `Dataset` should be:
- public if not in org acct
- user name if in org acct

Right now, I get an error that the table is not found:

```python
>>> d = Dataset('all_month_3')
>>> d.download()
CartoException: 400 Client Error: relation "public.all_month_3" does not exist
```

Which forces me to specify the schema, an implementation/platform detail that I don't think is obvious to most users of cartoframes. To me, the power of having schema is accessing datasets in org accounts that are not yours (e.g., if a colleague shares a dataset with you).

**Comment by oleurud** [comment]
You are totally right.

**Comment by oleurud** [comment]
Done
