### ISSUE TITLE
Legend API

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/cartoframes#693]
- [x] Create Legend class (+doc) / Review Legend API (naming)

```py
from cartoframes.viz import Legend

Legend({
    'title': '...',
    'description': '...'
})
```

Types:
```
color-category
color-bins
color-continuous
size-bins
size-continuous
```
Properties: 'color', 'strokeColor'

```py
from cartoframes.viz import Legend

Legend({
    'type': '...',
    'prop': '...',
    'title': '...',
    'description': '...',
    'footer': '...'
})
```

The type of the legend could be different for each geometry type:

```py
from cartoframes.viz import Legend

Legend({
    'type': {
        'point': '...',
        'line': '...',
        'polygon': '...',
    },
    'property': '...'
})
```

- [x] Review default legend (False)
- [x] Template naming refactor
- [x] Unify legend/popup format

**Comment by andy-esch** [comment]
About the Legend API, why not keyword args instead of a dict? That way we can still pass a dict as `Legend(**legend_dict)`

**Comment by Jesus89** [comment]
We are following the same structure in this class as in the rest of viz classes. For example, this is a layer using all the classes:

```py
Map(
    Layer(
        Source('populated_places'),
        style=Style('color: blue'),
        popup=Popup({
            'hover': '$name',
            'click': '$pop_max'
        }),
        legend=Legend({
            'type': 'color-category',
            'prop': 'color'
        })
    )
)
```

But the point is that the sugar API does not need the class instantiation so you can do:

```py
Map(
    Layer(
        'populated_places',
        style='color: blue',
        popup={
            'hover': '$name',
            'click': '$pop_max'
        },
        legend={
            'type': 'color-category',
            'prop': 'color'
        }
    )
)
```

Since this is the simplest API, it will be most used one, and in this case, it is not possible to use args as params.

**Comment by andy-esch** [comment]
👍 Makes sense

**Comment by Jesus89** [comment]
Closed via https://github.com/CartoDB/cartoframes/pull/712
