### ISSUE TITLE
Creation of carto-frame from csv,postges,hdfs,geojson etc

### ISSUE THREAD

**Issue by stuartlynn** [CartoDB/cartoframes#7]
Might want to be able to specify geom col / conversions

**Comment by ljwolf** [comment]
w/ #86, I think most of these ops can be offloaded to (geo)pandas. I can write a demo notebook once #86 merges on how to do that IO.

**Comment by andy-esch** [comment]
Works out out of the box now since `cc.write` and `cc.read` work with native pandas dataframes or geopandas geodataframes.
