### ISSUE TITLE
Dataset constructor questions

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#700]
For the dataset constructor, I know the goal is for people to not use it directly, but I have a strong feeling people will use it because it's less typing than using one of the class methods. The collateral damage is that users will be confused when attributes like `state` are not set automatically and `Map` throws an error that None is not a key in `_map_dataset_state`.

I know the current implementation is nice and clean in the constructor, but I'm concerned about the confusing errors like this. To get around these errors, could we add some more logic to the `__init__` to set `state`? An alternative is to add some strong error catching that looks at inputs (e.g., if state is set) and advises users to set all required flags or use the class methods.

cc @oleurud

**Comment by andy-esch** [comment]
A natural place to validate if `state` is properly set is in
https://github.com/CartoDB/cartoframes/blob/37155c3ed938ec16fb66aed961cfb350c0020a7f/cartoframes/dataset.py#L173

Where we could do something like

```python
if self.state not in (Dataset.STATE_LOCAL, Dataset.STATE_REMOTE):
    raise ValueError('Dataset `state` option not properly set. Use Dataset class methods instead.')

```

**Comment by oleurud** [comment]
Closing it since this is not happening after the current Dataset classes structure
