### ISSUE TITLE
HTML Template for kuviz and CARTO VL source

### ISSUE THREAD

**Issue by oleurud** [CartoDB/cartoframes#702]
In order to create a visualization (aka **Kuviz**), we need to create an HTML template based on the current one used to show the map in the notebook, to be shared with other users.

In the future, we are going to use Maps API (anonymous maps) and we will need to instantiate the map and use CARTO VL MVT source. But at this moment, I prefer to go with the same approach (as similar as possible) as frontend do showing the map in the notebook.

cc @elenatorro @Jesus89 @VictorVelarde

**Comment by Jesus89** [comment]
After the meeting we have decided to go for a unique HTML template for remote CARTO sources, for both, notebook and public visualizations.

It is not an issue to publish private Maps API keys in the public visualizations. Also, the parsing of metadata from the VL style, interactivity, aggregations, etc is a complex task that VL already does. So with VL sources SQL/Dataset we don't need to replicate this logic in CARTOframes.

We will use finally two templates: one for remote vizs (source SQL) and the other for local vizs (source GeoJSON). We need some logic here to decide which template based on the Dataset state.

There is one final thing missing, that is the visualization of pure Dataframes + metadata, which I'm not sure if it's in the roadmap for v0.11.

**Comment by oleurud** [comment]
The last point: the DataFrame data visualization in the notebook is defined (we need to support geoDataFrames in the Dataset class to: DataFrame ---> geoJSON ---> CARTO VL), but not we are going to implement it. But this is out of scope of the "sharing visualizations" project scope.

**Comment by oleurud** [comment]
The issue about getDataFrames https://github.com/CartoDB/cartoframes/issues/704

**Comment by oleurud** [comment]
I have a first version working of the publish method using the same template as the one used in the iframe. Some details:
- the size: right now the width is `100%` and the height `632px` if no size is provided. For a shared map both should be 100% and right it is not possible.
- we should add the CARTO look and feel: the menu, logo and so on

**Comment by oleurud** [comment]
:rocket:
