### ISSUE TITLE
Layer(tablename) schema always set to public

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#707]
It looks like there's another hardcoded (or at least default that's never resolved) to 'public':
https://github.com/CartoDB/cartoframes/blob/bc8dedbaa2fccc3288e44ab0bf975938fba30acd/cartoframes/viz/source.py#L133

I encounter the problem when running this code:
```python
from cartoframes.viz import Layer, Map

set_default_context(
    base_url='https://eschbacher.carto.com',
    api_key='default_public',
)
Map(Layer('all_month_3'))
```
<details>
<summary>Stack Trace</summary>
---------------------------------------------------------------------------
BadRequestException                       Traceback (most recent call last)
~/.local/share/virtualenvs/cartoframes-pRWzcuWT/src/carto/carto/sql.py in send(self, sql, parse_json, do_post, format, **request_args)
    109 
--> 110             return self.auth_client.get_response_data(resp, parse_json)
    111         except CartoRateLimitException as e:

~/.local/share/virtualenvs/cartoframes-pRWzcuWT/lib/python3.7/site-packages/pyrestcli/auth.py in get_response_data(self, response, parse_json)
     51             raise BadRequestException(response_json.get("error", False) or response_json.get("errors",
---> 52                                                                                              _("Bad Request: {text}").format(text=response.text)))
     53         elif response.status_code == requests.codes.not_found:

BadRequestException: ['relation "public.all_month_3" does not exist']

During handling of the above exception, another exception occurred:

CartoException                            Traceback (most recent call last)
<ipython-input-48-e054c80166f1> in <module>
      5     api_key='default_public',
      6 )
----> 7 Map(Layer('all_month_3'))

~/git/CartoDB/cartoframes/cartoframes/viz/layer.py in __init__(self, source, style, popup, legend, context)
     76         self.is_basemap = False
     77 
---> 78         self.source = _set_source(source, context)
     79         self.style = _set_style(style)
     80         self.popup = _set_popup(popup)

~/git/CartoDB/cartoframes/cartoframes/viz/layer.py in _set_source(source, context)
     93     """Set a Source class from the input"""
     94     if isinstance(source, (str, list, dict, Dataset)):
---> 95         return Source(source, context)
     96     elif isinstance(source, Source):
     97         return source

~/git/CartoDB/cartoframes/cartoframes/viz/source.py in __init__(self, data, context, bounds, schema)
    136         self.context = self.dataset.cc
    137         self.credentials = _get_credentials(self.context)
--> 138         self.geom_type = _get_geom_type(self.dataset)
    139 
    140     def _init_source(self, data, context, bounds, schema):

~/git/CartoDB/cartoframes/cartoframes/viz/source.py in _get_geom_type(dataset)
    224 
    225 def _get_geom_type(dataset):
--> 226     return dataset.compute_geom_type() or Dataset.GEOM_TYPE_POINT

~/git/CartoDB/cartoframes/cartoframes/dataset.py in compute_geom_type(self)
    315         if self.state == Dataset.STATE_REMOTE:
    316             if self.query:
--> 317                 return self._get_remote_geom_type(self.query)
    318             elif self.table_name and self.schema:
    319                 query = 'SELECT * FROM "{0}"."{1}"'.format(self.schema, self.table_name)

~/git/CartoDB/cartoframes/cartoframes/dataset.py in _get_remote_geom_type(self, query)
    331                 FROM ({}) q
    332                 LIMIT 5
--> 333             '''.format(query))
    334             if response and response.get('rows') and len(response.get('rows')) > 0:
    335                 st_geom_type = response.get('rows')[0].get('geom_type')

~/.local/share/virtualenvs/cartoframes-pRWzcuWT/src/carto/carto/sql.py in send(self, sql, parse_json, do_post, format, **request_args)
    112             raise e
    113         except Exception as e:
--> 114             raise CartoException(e)
    115 
    116 

CartoException: ['relation "public.all_month_3" does not exist']
</details>

cc @oleurud

**Comment by oleurud** [comment]
^ @Jesus89 I am going to check it asap. I have already resolved in the Dataset, I am going to extract the solution to context and use it where needed

**Comment by oleurud** [comment]
It should be resolved

**Comment by andy-esch** [comment]
It works! 💥
