### ISSUE TITLE
Bug using WHERE in a Layer source

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/cartoframes#711]
```py
Map(Layer('SELECT * FROM populated_places WHERE adm0name = "Spain"'))
```

`CartoException: ['column "Spain" does not exist']`

**Comment by Jesus89** [comment]
We may replace `"` by `'` automatically :thinking:

**Comment by andy-esch** [comment]
That's default postgresql behavior - double quotes signify column names, table names, etc.. String literals should be in single quotes. You can escape the single quotes like so:
```python
Map(Layer('SELECT * FROM populated_places WHERE adm0name = \'Spain\''))
```
Or do a multiline string
```python
Map(Layer('''
    SELECT * FROM populated_places WHERE adm0name = 'Spain'
'''))
```

**Comment by Jesus89** [comment]
Oh nice, so I had the bug :P

Thanks!
