### ISSUE TITLE
Dataset set_dataframe is not working as expected

### ISSUE THREAD

**Issue by oleurud** [CartoDB/cartoframes#723]
If you do something like that:
```
df = ds.get_dataframe()
df ... # modify the dataset
ds.set_dataframe(df)
```
You will expect the Dataset will be unsynchronized from CARTO, and it will be, but the `_is_saved_in_carto` will still be `True`.

So, when you are doing:
```
df = ds.get_dataframe()
```
`df` and `ds._df` are the same object (it is passed by reference)

**Comment by oleurud** [comment]
I see 2 options:
- If set_dataframe/set_geodataframe is called, avoid checking if the current and the new are equals and always call to unsync(). For the same reason, we could determine the Dataset is not synchronized if get_dataframe/get_geodataframe is called,
- Make a copy of the dataframe in get_dataframe/get_geodataframe and return it.

The second one needs more memory (2x). The first one could synchronize Datasets without changes. I think the first one is "less bad".

More ideas?

@alrocar @andy-esch

**Comment by oleurud** [comment]
I see another option:
- we can add a check: if `df is self._df` in set_dataframe/set_geodataframe methods, they are the same instance, so we can call the `unsync` method.

**Comment by alrocar** [comment]
why do we have `get/set_dataframe` methods?

I'm sure I reviewed that stuff... but I don't remember the reason.

I'm thinking that we could make Dataset to be immutable, that means:

- If you want to get a dataframe, call any of the factory methods (`from_table`, `from_query`, etc.).
- If you want to `set a dataframe`, then create `from_dataframe` + `write` or whatever.

Thoughts?

**Comment by oleurud** [comment]
The use case is: 
```
dataset = Dataset.from_table('xxx)
dataset.download()
df = dataset.get_dataframe() # or get it from the download method
df.update(...)
dataset.set_dataframe(df)
```

So, you want to download data from CARTO and them modify it. Following your approach of making Dataset immutable, we could remove the `set_dataset` and the process would be:
```
dataset1 = Dataset.from_table('xxx)
dataset1.download()
df = dataset1.get_dataframe() # or get it from the download method

df.update(...)

dataset2 = Dataset.from_dataframe(df)
```

**Comment by oleurud** [comment]
:rocket:
