### ISSUE TITLE
Invalid LngLat error with a dataset in CF but not in Builder or VL

### ISSUE THREAD

**Issue by makella** [CartoDB/cartoframes#725]
@Jesus89 as I was describing in our meeting this morning, I am getting the error below:

<img width="1101" alt="Screen Shot 2019-06-03 at 12 14 31 PM" src="https://user-images.githubusercontent.com/1566273/58824382-2d9b1580-85f9-11e9-9480-fd8a6bcc56ca.png">

On the other hand, I get no warnings/errors/issues when opening the same dataset in either Builder and/or VL Editor

Builder map:
https://cartovl.carto.com/builder/d6ec889e-298f-48eb-850e-70ba145af550/

VL:
http://bl.ocks.org/makella/1409e547925e6eb3bf2375d6a18ff502

cc @VictorVelarde

**Comment by Jesus89** [comment]
Hi. This seems a Mapbox GL issue in the fitBounds function. We may add functionality to convert the values before passing them to the function.

**Comment by Jesus89** [comment]
I have tested the table:
- Max latitude and longitude are 415750 and 1063233 for `Wulatehouqi Huogeqi First Stage`, which actually is in the coordinates 41.5750, 106.3233. This is a problem with the data.
- However, I have added a "clamp" function to avoid bound out of the limits, so the bug won't appear again (#725)

**Comment by makella** [comment]
THANKSSSS!!!
