### ISSUE TITLE
test alternatives to classification method used in color_bins_layer helper

### ISSUE THREAD

**Issue by makella** [CartoDB/cartoframes#726]
Related to this issue https://github.com/CartoDB/cartoframes/issues/724. Once we have a better sense for the cause of the values, the next step will be to test a couple of things related to classification:

- values returned with viewport vs. global
- other methods of classification that would provide 5 bins (for example, @VictorVelarde's idea of linear buckets)

First step is to see if this issue is related to legends. If not, next step will be to test the other points listed above.

**Comment by Jesus89** [comment]
Hi! The Infinity bug was solved.

Regarding viewport vs global, I'd go for global now, because viewport expressions make legends more complex because they should change dynamically.

We can change `globalQualtiles` by `linear` if it makes sense. Just spot the helpers to update and I'll change it :)

**Comment by makella** [comment]
i think now that we have this figured out, we are all good! closing!! 

thanks for looking into this!
