### ISSUE TITLE
_default_context

### ISSUE THREAD

**Issue by oleurud** [CartoDB/cartoframes#736]
Right now, we need to import _default_context each time we need to use it.

```
_default_context = None

def set_default_context(...)
    _default_context = ...
```

We need to use a proper solution to it. some ideas:
- converting set_default_context into a Singleton class 
- making _default_context global.

**Comment by djfan** [comment]
Is there any way to detach the default_context explicitly? or return (print) the current default_context?

**Comment by andy-esch** [comment]
@djfan, maybe open another issue for that. It's a good idea for a feature request / something that hasn't come up before.

**Comment by oleurud** [comment]
I am not sure about @djfan probably depending on the final solution we could do it (for example with the singleton case)

**Comment by oleurud** [comment]
Now, we can use the function `get_default_credentials` instead of the import
