### ISSUE TITLE
Reverse the layers order in the map

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/cartoframes#742]
```
Map([
  layer-bottom,
  layer-med,
  layer-top
])
```

**Comment by Jesus89** [comment]
I have reversed the order of the layers, so they are rendered from bottom to top. However, the legends are rendered from top to bottom. Does it make sense to you @andy-esch @makella?

![](https://user-images.githubusercontent.com/2227572/59101213-8e438e80-8928-11e9-94da-0a37a55722f3.png)

**Comment by makella** [comment]
hi @Jesus89 for me, it makes sense that the legends draw in the same "visual" order as the layers on the map by default. but i see your point about the difference in the layer order definition and the legend ordering. which brings me to the question of the ability to reorder the legend (not necessarily with the helpers but overall)... thoughts?

**Comment by makella** [comment]
also note: i'll need to adjust one of my example notebooks when this change happens. Helper methods - Part 2
