### ISSUE TITLE
feeback method in CARTOframes API?

### ISSUE THREAD

**Issue by jorgesancha** [CartoDB/cartoframes#747]
This is just an idea, but since we are always trying to find ways to get feedback from CARTOframes users, it would be nice to implement a "feedback" method so that users could provide it in the context of what they are trying to do. Something along the lines of:

In: `cc.feedback("It would be great to be able to share visualisations")`
Out: Thanks for your feedback! If you want us to reply, please provide us with your email address like so: cc.feedback("Your feedback", email='blah@blah.com')

That feedback could go to a specific email list or issues in private github repo. We'd have to implement, ideally, some kind of spam control (maybe only users with valid API keys, etc..)

Let me know your thoughts, @andy-esch @javitonino

**Comment by javitonino** [comment]
Uhm, I don't see it. How is the user going to discover that the API has the `feedback` method? Most likely through documentation. In that case, let's just link a feedback from in the docs. In any case, we can point to a feedback from wherever you would point to the feedback method.

Also, cartoframes is typically used inside a notebook, and it would be super-easy for a user to resend the same feedback multiple times, rerunning a cell, so I think we would end up with repeated feedback entries (no big problem, but still)

**Comment by andy-esch** [comment]
I think it's a unique feature that might draw more feedback, and since it'd still be in a Python environment, that means no context switching. People could easily abuse it, but since most users are paid I don't see this being a problem. Filtering out duplicates should be pretty straightforward, especially if we take in the username.

**Comment by jorgesancha** [comment]
One way to "draw people to it" would be to include it in the video
https://github.com/CartoDB/product/issues/385

The idea of that video is to post it in the blog and hopefully to include
it in the newsletter to our customers. Also, part of the idea here was to
reach out to existing CF users to tell them about new functionalities. We
could always say "hey, there's a new 'feedback' method you can use to send
us feedback as it happens"

It might or might not work, but if it does, it might turn out to be really
useful.
