### ISSUE TITLE
Proper exception handling

### ISSUE THREAD

**Issue by alrocar** [CartoDB/cartoframes#751]
We have improved [exception handling within pyrestcli](https://github.com/danicarrion/pyrestcli/pull/25) and now we need to update CARTOframes and carto-python to be consistent with those changes and [avoid this kind of checks](https://github.com/CartoDB/cartoframes/blob/develop/cartoframes/datasets/dataset.py#L347)

**Comment by Jesus89** [comment]
Dup #1029

**Comment by Jesus89** [comment]
Dup #1029
