### ISSUE TITLE
[Documentation: Reference] Updates related to v0.10 & v1.0b1

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#756]
ReadTheDocs needs to be updated for v0.10+ releases.

- [x] Update README to show map workflow
  * Only Map(Layer())?
  * Two workflows?
  * Remove experimental section
- [x] Sidebar (in `docs/index.rst`) highlights crucial introduction to using cartoframes
- [x] All classes are documented
  - [x] `Dataset`
  - [x] `Map`
  - [x] `Layer`
  - [x] helper methods
- [x] Modules documented?
  - [x] viz
  - [x] auth
  - [x] data
  - [x] viz.helpers
- [x] Ensure docs build in readthedocs

**Comment by Jesus89** [comment]
Closed in #777
