### ISSUE TITLE
Switch to Positron for default basemap

### ISSUE THREAD

**Issue by makella** [CartoDB/cartoframes#758]
- [x] Adjust style
  - PR: https://github.com/CartoDB/basemap-styles/pull/17
- [x] Work with @skgsergio to get new style published
  - [x] PR
  - [x] Preview
  - [x] Publish
- [x] For color helper methods remove `reverse()` for continuous and bins
- [x] Double check default cartography on this basemap
- [x] Adjust default basemap example notebook

**Comment by skgsergio** [comment]
Style changes for Positron are now live in prod https://github.com/CartoDB/basemap-styles/issues/16 🎉

**Comment by makella** [comment]
closing issue, PR with changes here: https://github.com/CartoDB/cartoframes/pull/764
