### ISSUE TITLE
Helper methods - Size category

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/cartoframes#765]
For

- [x] points
- [x] lines

**Comment by makella** [comment]
The implementation we will use here is two-fold. By default, if a user selects this helper layer, we will default to the `top,5` categories assigned to an array (2 by default) of size values. The user can modify the symbol size array and/or the `top` parameter. In addition, the user will also be able to take advantage of buckets if they want to define a custom array of category values with a custom array of symbol sizes. So cool!

**Comment by Jesus89** [comment]
Done in https://github.com/CartoDB/cartoframes/pull/770
