### ISSUE TITLE
`default_legend` doesn't display proper legend for a ramp

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#774]
If I create a map with a layer that has a CARTO VL ramp _and_ use the `default_legend=True` option, I'd expect to get the same legend we get when using the helper methods. Instead, it seems we get a value in the intermediate range of the palette.

<img width="900" alt="Screen Shot 2019-06-12 at 8 14 59 PM" src="https://user-images.githubusercontent.com/1041056/59394772-f6420c80-8d4e-11e9-8d2c-a7d7212acd1b.png">

Steps to reproduce:
```python
set_default_context(
    base_url='https://cartoframes.carto.com',
    api_key='default_public'
)

Map(
    Layer('brooklyn_poverty', 'color: ramp($poverty_per_pop, purpor)'),
    default_legend=True
)
```

**Comment by Jesus89** [comment]
This is the default behavior of the `default_legend` attribute
