### ISSUE TITLE
`default_legend` displays even when using a helper method

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#775]
The expectation is that the helper provides the default legend, so there should not be an additional one drawn.

<img width="879" alt="Screen Shot 2019-06-12 at 8 18 14 PM" src="https://user-images.githubusercontent.com/1041056/59394847-48832d80-8d4f-11e9-84e3-e61912686381.png">

**Comment by Jesus89** [comment]
This is the default behavior of the default_legend attribute
