### ISSUE TITLE
Current `if_exists=replace` implementation in `Dataset.upload` might block the user's dashboard

### ISSUE THREAD

**Issue by alrocar** [CartoDB/cartoframes#780]
See [this and next comments](https://github.com/CartoDB/support/issues/2045#issuecomment-500458536).

We are extensively using a "`DROP + CREATE TABLE AS SELECT heavy_query + cartodbfy` in a single transaction" strategy, which seems to be the culprit for table locks.

The result of this, could be users having their dashboards unusable doing a fair use of the `Dataset` API.

I see two options here:

- Fix the lock issue at the right place. We'd need to open a `PAIN` issue in product and plan how and when to solve it and how much time it will take.
- We can change the API to `replace` only data, and not content. That way we might avoid that transaction and use `TRUNCATE` to empty a table and replace with new data.

Take into account that with second option, users are still able to `cc.execute` an arbitrary query, so they might face the same problem described.

cc. @andy-esch @oleurud @Jesus89 

Let's open the discussion here and decide what to do.

**Comment by alrocar** [comment]
Linking this other [issue](https://github.com/CartoDB/cartoframes/issues/543).

If we decide to change the logic for `replace` and use `TRUNCATE` instead of DROP + CREATE TABLE, we might fix the bug in that ticket.

**Comment by rafatower** [comment]
As pointed by Tonino in some conversation, there's an alternative strategy to minimize the lock on DB catalog tables, the one followed by rails app for syncs:
- do the create table in a separate schema / with a temp name (you can even explore [unlogged tables](https://www.compose.com/articles/faster-performance-with-unlogged-tables-in-postgresql/) for performance).
- swap the old and new table in a separate transaction (DROP and ALTER...RENAME).

This has the advantage of working with changes in source table schema.

**Comment by Jesus89** [comment]
Already using TRUNCATE instead of DROP + CREATE
