### ISSUE TITLE
Export VL map to static image

### ISSUE THREAD

**Issue by VictorVelarde** [CartoDB/cartoframes#785]
Analyze the options to get a simple image from the VL map (currently just interactive), to get a feature equivalent to the previous raster version.

Consider if exporting the whole viz (including legend and so on) is feasible or not.

**Comment by andy-esch** [comment]
Related: https://github.com/CartoDB/cartoframes/issues/499

**Comment by Jesus89** [comment]
Since we are moving from VL to WebSDK (deck.gl) we can close this one and check static maps in deck.gl
