### ISSUE TITLE
Improve geometry decoding strategy

### ISSUE THREAD

**Issue by alrocar** [CartoDB/cartoframes#798]
We are now [calling to decode_geometry for each row](https://github.com/CartoDB/cartoframes/blob/develop/cartoframes/data/dataset.py#L581) and it tries to decode from different formats.

Worst case, for each row, we try to [decode the geometry 5 times](https://github.com/CartoDB/cartoframes/blob/develop/cartoframes/data/utils.py#L110-L134).

We could create a smarter method for this:

- Maybe store once the geometry encoding type, and use the proper decode method accordingly.
- Also, check if we need to send the decoded geometry as a WKT, because we might be incurring in performance penalties.

Related [issue](#773)

**Comment by Jesus89** [comment]
Closed via #821
