### ISSUE TITLE
Labels not showing on top of polygon layers

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#803]
When a `Map` is created with a polygon layer, the labels appear below the polygons, obscuring the labels which could be important for the user navigating the map.

Ideally, `Map` should be able to figure out where to put the labels.

```
Map(
  PolygonLayer,
  PointLayer,
)
```

Should produce:
Bottom: PolygonLayer
Middle: Labels
Top: PointLayer

**Comment by Jesus89** [comment]
Dup: https://github.com/CartoDB/cartoframes/issues/645
