### ISSUE TITLE
New SQLClient API

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/cartoframes#808]
Refactor `cc.query` feature. New class? new method?

**Update**

From the [doc](https://docs.google.com/document/d/1DFNwciC1rCJvWz6EhB1lVzTPdTaF8afJWGL0naIeszk/edit#):

```py
from cartoframes.client import SQLClient

sql_client = SQLClient(creds)
sql_client.query('select …') // Uses the SQL API
sql_client.execute('insert …')  // Uses the Batch SQL API

# Helpers (future)
sql_client.create_table(‘table_name’)
sql_client.distinct(‘table_name’, ‘column_name’)
sql_client.bounds(‘table_name’)
```

**Comment by oleurud** [comment]
I see 2 options:
- a function if it will only send queries to SQL API
- a new object if we add more features (custom queries) over the SQL API: 
  - create table
  - cartodbfy table
  - call to that data services functions
  - ...

I am not sure about the second one, so I would say a function is enough
