### ISSUE TITLE
Define Widget API

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/cartoframes#809]
Add `Widget` class. Add `widget` attribute to the `Layer` class.

**Proposal**

```py
widget: {
    type: 'formula',
    value: 'viewportSum($amount)',
    title: '...',
    description: '...',
    footer: '...'
}

widget: [{
    type: 'category',
    value: 'cat_column',
    title: '...',
    description: '...',
    footer: '...'
}, {
...
}]
```

**Comment by makella** [comment]
First, sorry if some of this has already been covered (other than in our meeting today!). I wasn't able to keep active with the API design discussions last week.

With that said, here are some comments/food for thought:

## Widgets
- For the category widget, 
  - will there be the option to order features? For example, the functionality in Builder, where you can order widget features based on aggregations of other variables (sum, count, min, max, etc.)
  - would we  be able to expose other aggregations for categorical data like mode? 
  - one of the things I'm missing here is the ability to add a prefix or suffix to `value` 
    - I think this would also apply to legend values ($, %, F, C, etc.)

- For the histogram widget:
  - will there be the ability to adjust the number of bins?

Will there be a way to set the widgets so they don't update with zoom/pan of the map?

## Widgets and helpers
- for discussion... will widgets be added by default with helpers?
  - if so, some things here to discuss.
  - for example, `top` doesn't match the "top count" that I think the category widget does
  
<img width="1002" alt="Screen Shot 2019-07-01 at 2 11 59 PM" src="https://user-images.githubusercontent.com/1566273/60463887-5e776600-9c0a-11e9-94b6-550e88de2953.png">
  
This is an example of the idea "what if I want my widgets to match what I see on my map?" there are a lot of other considerations we could get into, but before going there, wanted to follow-up with the initial discussion of whether or not we plan on doing this.

thanks!
mamata
