### ISSUE TITLE
geopandas Polygon / MultiPolygon display error

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#815]
Polygons in GeoDataFrames and GeoJSON don't seem to be rendering. If they are MultiPolygon they seem to work as expected.

<img width="1079" alt="Screen Shot 2019-06-25 at 3 30 40 PM" src="https://user-images.githubusercontent.com/1041056/60127484-4e6d0b80-975e-11e9-829f-223d6024fccf.png">

```python
url = "http://eric.clst.org/assets/wiki/uploads/Stuff/gz_2010_us_040_00_500k.json"
country_gdf = geopandas.read_file(url)

Map(Layer(country_gdf))
```

**Comment by Jesus89** [comment]
@giuliacarella and I found the same issue :smile: 

She discovered also that this works fine for 63 polygons, but not for >64  0_o

**Comment by Jesus89** [comment]
OK, it seems that the gdf contains merged geometry types (Polygons and MultiPolygons). We supported only one type per source in VL because of how CARTO datasets work.

However, For GeoJSON it's possible to support mixed Polygon+MultiPolygon, and also Line+Multiline and Point+Multipoint (Multipoint is not supported in VL GeoJSON btw https://github.com/CartoDB/carto-vl/issues/137).

What do you think @VictorVelarde @elenatorro?

**Comment by elenatorro** [comment]
good catch 👀 ! I'd go ahead and support those type combinations, we've seen it doesn't require a lot of changes.

**Comment by Jesus89** [comment]
This code fixes the bug: https://github.com/CartoDB/carto-vl/pull/1379

![](https://user-images.githubusercontent.com/2227572/60443101-c3d35300-9c1a-11e9-8dd5-b5eb76195486.png)

Should we tackle GeoJSON support for MultiPoints, then @VictorVelarde?

**Comment by VictorVelarde** [comment]
That might bring some other related changes, that we'll have to review (eg. getRenderedCentroid)

**Comment by Jesus89** [comment]
> That might bring some other related changes, that we'll have to review (eg. getRenderedCentroid)

https://github.com/CartoDB/carto-vl/pull/1379#issuecomment-507581700

Regarding the MultiPoint implementation, we can talk on the other ticket since it's out of the scope of this bugfix.

**Comment by Jesus89** [comment]
This is fixed in https://github.com/CartoDB/carto-vl/pull/1379.

It will be available in the next patch release of VL.
