### ISSUE TITLE
Published map not holding viewport settings

### ISSUE THREAD

**Issue by makella** [CartoDB/cartoframes#820]
Going through the publishing workflow today, I noticed that my viewport settings from the notebook were not transferring over to the published map.

We were hoping to show this step in the video we are making. If it isn't possible to fix in the next day or so, please let me know.

Thanks!

p.s. -- publishing is so awesome!!

To publish:
```
# Publish map
tmap = Map (
    [
    color_bins_layer(
        'county_measures',
        'median_income', 
        'Median Income', 
        palette='mint',
        bins= 7
    ),
    Layer(
        'state_bounds',
        'color: rgba(240,240,240,0.8)',
        'width: 2.5'
    ),
    size_continuous_layer(
        'county_measures_points',
        'pop_poverty',
        'Population in Poverty',
        size=[2,80],
    ),
    ],
    viewport={'zoom': 4.97, 'lat': 30.234902, 'lng': -90.044652}
)

tmap.publish('Poverty and Income')
```

url to published map:
https://cartovl.carto.com/kuviz/c7a584ec-6391-4cc9-9188-dff71663fac3

Also attaching the notebook (Very last Step 11):
[Helper Methods Script (1).ipynb.zip](https://github.com/CartoDB/cartoframes/files/3336929/Helper.Methods.Script.1.ipynb.zip)

**Comment by Jesus89** [comment]
Fixed https://github.com/CartoDB/cartoframes/pull/839

https://cartovl.carto.com/kuviz/61b14260-5cd9-4bc3-8560-bf70c7445a19
