### ISSUE TITLE
Error improvements

### ISSUE THREAD

**Issue by oleurud** [CartoDB/cartoframes#824]
- Better error reporting for auth: https://github.com/CartoDB/cartoframes/issues/503
- Better error reporting for context: https://github.com/CartoDB/cartoframes/issues/776
- Feature request: More accurate exception types https://github.com/CartoDB/carto-python/issues/85
- Feature request: more error types https://github.com/CartoDB/carto-python/issues/112

**Comment by Jesus89** [comment]
Dup #1029
