### ISSUE TITLE
feature request: helper methods palette expressions as python lists

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#825]
Right now the `palette` keyword takes a string expression, but it would be handy to have it take lists as well:
```python
Map(
    color_category_layer(
        'county_measures',
        'male_or_female', 
        'Predominant Gender', 
        palette=['#6486FD', '#FD8F64', 'yellow']   # in addition to '[#6486FD,#FD8F64,yellow]'
    )
)
```

**Comment by Jesus89** [comment]
OK. This is because we pass directly the param to VL, and `['#6486FD', '#FD8F64', 'yellow']` cannot be parsed as a palette because they are strings.

We can add a utility method in the color helpers to serialize the palette to `[#6486FD, #FD8F64, yellow]`.
