### ISSUE TITLE
Implement format attribute

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/cartoframes#826]
In:
- Legends
- Popups
- Widgets

https://github.com/d3/d3-format

**Comment by andy-esch** [comment]
Thinking through this a little, this would be something that's set at the `Layer` level and inherited by legends, popups, and widgets.

**Comment by Jesus89** [comment]
Aha, but what if you want a different format for different widgets or popups?

**Comment by andy-esch** [comment]
Good question 🤔 
Maybe each has a separate format that overrides the Layer-level one?

**Comment by Jesus89** [comment]
OK, so we can add the format attribute to the layer, but also to the legend, popups and widgets.

```js
Layer(
    legend={
        ....
        format='...'
    },
    popup={
        'hover': [{
            ....
            format='...'
        }, ...]
        'click': ....
    },
    widgets=[{
        ....
        format='...'
    }, ...]
    format='...'
)
```

**Comment by joshtemple** [comment]
It would be really great if you could customize the number format in legends, popups, etc. For example, sometimes the scientific notation introduced by #818 is not desired. Or perhaps you want to round a number or add a currency symbol in front of the number.

You should be able to provide some kind of string to indicate how you'd like the numbers to be formatted.

**Comment by Jesus89** [comment]
Fixed in https://github.com/CartoDB/cartoframes/pull/1626, https://github.com/CartoDB/airship/pull/689. Release 1.0.3
