### ISSUE TITLE
[Doc - Guides] Migration guide from 1.0b5 and 1.0b7 to v1.0 

### ISSUE THREAD

**Issue by oleurud** [CartoDB/cartoframes#828]
We should create a migration guide from the previous approach using Context to the new one with several entities. Why?

- First of all, the guide will help users from previous versions to move to the v1.0
- Also for us, because doing these "exercises" we could find some weird things in our new approach.

**Comment by elenatorro** [comment]
Note: rename this file https://github.com/CartoDB/cartoframes/tree/develop/docs/developers/migrations/rc1.md to `v1.0.0.md` and add things directly there.
