### ISSUE TITLE
uploading this dataframe returns `['extra data after last expected column']` error

### ISSUE THREAD

**Issue by mbforr** [CartoDB/cartoframes#847]
[df_hold.csv.zip](https://github.com/CartoDB/cartoframes/files/3398391/df_hold.csv.zip)

**Comment by alrocar** [comment]
summoning @Jesus89 @oleurud for priorization

**Comment by Jesus89** [comment]
Hi @mbforr, what version of CF are you using?

**Comment by andy-esch** [comment]
@mbforr could you try this again with the newest beta version v1.0b2?

**Comment by oleurud** [comment]
This one should be solved by https://github.com/CartoDB/cartoframes/pull/974

**Comment by Jesus89** [comment]
I confirm that this bug is solved in the version `1.0b3`.
