### ISSUE TITLE
Improve error messages in Datasets

### ISSUE THREAD

**Issue by oleurud** [CartoDB/cartoframes#856]
I have added some comments in the errors talking about `QueryDataset`, `TableDataset` and `DataFrameDataset` and I think we should avoid talking about these internal classes.

For example: in the delete method of QueryDataset we have:
```
def delete(self):
        raise ValueError('Method not allowed in QueryDataset. You should use a TableDataset: `Dataset(my_table)`')
```
But as @andy-esch proposed to me, it would clearer:
```
def delete(self):
        raise ValueError('The delete method is not allowed on Datasets built on queries. Use a table-based dataset instead: Dataset(my_table)')
```

**Comment by Jesus89** [comment]
Dup #1029
