### ISSUE TITLE
Interactive Iframe issues in Databricks

### ISSUE THREAD

**Issue by andrewbt** [CartoDB/cartoframes#862]
Databricks is a popular Python Notebook IDE (geared towards Spark) that one of our clients uses. In creating a training for them, I discovered Databricks has specific/peculiar ways of showing notebook cell outputs, both images from matplotlib and interactive iframes. See:

https://docs.databricks.com/user-guide/visualizations/index.html
https://docs.databricks.com/user-guide/visualizations/index.html#displayhtml-function
https://docs.databricks.com/user-guide/visualizations/html-d3-and-svg.html
https://forums.databricks.com/topics/displayhtml.html

With some hacking, I am able to get proper expected image and iframe outputs from CARTOframes 0.10.1 in Databricks. But applying the same hacks does not yield the same success in CARTOframes 1.0b1. It seems the iframe Javascript code in 1.0b1 has additional complexity including some base64 encoding libraries that run afoul of whatever security/embedding procedures Databricks does and throw a few nonsensical `Unexpected identifier` JS errors.

Attached is a zip of 2 notebooks - one using cartoframes 0.10.1 and using the specific displayHTML function to get its iframes to show up, and the other using 1.0b1 and the same operations failing.

[Archive 8.zip](https://github.com/CartoDB/cartoframes/files/3418933/Archive.8.zip)

Databricks has a free-to-use Community edition that is more than sufficient for testing CARTOframes and debugging this, just sign up at: https://databricks.com/try-databricks

**Comment by cmongut** [comment]
I had a try to learn about databricks and I got the same result. We will try to see what is happening in the next cycle. Thanks for the heads up!

**Comment by elenatorro** [comment]
I've been testing the current cartoframes code in Databricks (by generating a Python egg locally and importing it into my Databricks cluster) However, I've also tried to parse the HTML output from the iframes generated by jupyter notebooks (which runs great when saved as an html file) and I found there're a couple of issues.

First of all, using `displayHTML` method to render the content gives some errors when parsing strings that contain escaping characters (i.e.: `"SELECT * from \"spend_data\""`).

I'd need more time to test it deeper and learn if there's something better than `displayHTML` for this purpose.

**Comment by jatorre** [comment]
Hi all. Can I get an update on this? I had a meeting with databricks the other day and would like to talk to customers now. Have we tried ?

**Comment by cmongut** [comment]
I'll try to do a quick test today. The rendering wasn't working and we didn't do anything to fix it. Let's see if they have updated something in their end

**Comment by cmongut** [comment]
Hey @jatorre, we have done some tests and the visualization piece is working! I'll close this issue and we will open new ones if we find other issues.

![image](https://user-images.githubusercontent.com/711025/72909822-e7d1bf80-3d37-11ea-8bbe-f567b343984b.png)

**Comment by jatorre** [comment]
Wait wait, where did you test his and under what versions... i would like a video to showcas it.

**Comment by cmongut** [comment]
I tried cartoframes 1.0 with their [community version](https://databricks.com/signup/signup-community). I can help you if you want :)
