### ISSUE TITLE
Error not very helpful if geopandas is not installed

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#867]
When creating a map from a dataframe and geopandas is not installed, the error thrown is not very clear:
![image](https://user-images.githubusercontent.com/1041056/61717494-2fe33b80-ad2f-11e9-9e6d-4654afb7db0d.png)

Code to reproduce:
```python
from cartoframes.viz import Map, Layer
import pandas as pd

data = {'lat': [0, 10, 20, 30], 'lng': [0, 10, 20, 30]}
df = pd.DataFrame.from_dict(data)

Map(Layer(df))
```

We should say `RuntimeError: Install geopandas to create a map from a dataframe` or something like that.

cc @malgar

**Comment by alrocar** [comment]
We've been struggling to avoid distributing geopandas with the library and it's hurting us more than helping us. Little by little we are coupling the library to geopandas and it makes sense to include it as a dependency.

I'm closing this one in favour of https://github.com/CartoDB/cartoframes/issues/1047
