### ISSUE TITLE
IPython no longer a dependency

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#878]
It's time to remove IPython as a dependency :)

https://github.com/CartoDB/cartoframes/blob/250ec179aa36eed342df4dab5b8c209e9fa47b30/setup.py#L32-L39

I'm pretty sure it's nowhere in the code base anymore.

cc @oleurud 
Related: https://github.com/CartoDB/cartoframes/pull/874

**Comment by oleurud** [comment]
Removing dependency in the beta2 release https://github.com/CartoDB/cartoframes/pull/881
