### ISSUE TITLE
Refactoring Source class

### ISSUE THREAD

**Issue by oleurud** [CartoDB/cartoframes#903]
The source class is doing:
1. Support different source types
2. Create a Dataset
3. Get query and bounds

The first 2 points are now resolved by Dataset, so we should do it using it instead of having a functionality duplication. Also, this class will be a good example for future integrations into CARTOframes, so it is important to have it in the best fit possible, focus on one functionality (Get query and bounds), extracting whatever we see that it could be useful in other integrations and so on

**Comment by VictorVelarde** [comment]
Have we postpone this or was it done inside another PR?

**Comment by oleurud** [comment]
It was done in https://github.com/CartoDB/cartoframes/pull/915
