### ISSUE TITLE
Dataset extends pandas.DataFrame (or geopandas.GeoDataFrame)

### ISSUE THREAD

**Issue by oleurud** [CartoDB/cartoframes#910]
### Context
Right now, we have 2 main entities to work with data in CARTOframes: a DataFrame or a Dataset. This situation generates some doubts / troubles / a bit of confusion in some cases, for example:
- what we should return in the DO enrich method? A DataFrame? A Dataset?
- same as before in download or upload  Dataset methods
- some people ask: why do I need a new entity? I want to work with pandas, I don't want to learn a new entity.

### Extending DataFrame (or GeoDataFrame)
If Dataset class extends pandas.DataFrame or even better extending from geopandas.GeoDataFrame:
- all these doubts will be resolved and at the same time
- we will simplify the understanding of this class
  
This is an idea, it is not defined at a low level. But it seems as possible. At the end the class Dataset should have:
- all the DataFrame methods and properties
- credentials
- `table`, `query`, `schema`, `dataset_info` props and methods
- download / upload
- delete, exists and is_public
- is_remote, is_local, compute_geom_type, get_table_column_names, get_table_names, get_query

Some changes that we will need to tackle:
- `_df` prop and `dataframe` method disappear. Also, every internal reference to it should we changed (a reminder: `_df` can have a geoDataFrame or a DataFrame)
- methods related to CARTO tables/queries/stuff should be renamed making them more explicit about the context of the action done by the method, for example: `delete` to `delete_table`, `exists` to `table_exists`, `dataset_info` to `table_info`.

We dont have to go crazy, but the context of class changes a bit, so we should reflect it.

### About geoDataFrame
As I said before, `_df` can have a geoDataFrame or a DataFrame depending on the source of the data. Of course, it doesn't seem as the best of the scenarios. Basically, we are using geoDataframe in 2 cases:
- if the Dataset is created from a geoJSON or a geoDataFrame
- when we are going to render data in a map, if the data is not a geoDataFrame, we are changing it.

It could be the moment to move (or not) to a geoDataFrame. We have to take into account some things like:
- all the methods supported by it: http://geopandas.org/reference.html#geodataframe (for example the `plot` method should be overwritten)
- we have some geometry helpers like `compute_geom_type` that maybe are solved in a different way in geoDataFrame

cc @alasarr @alrocar @andy-esch

**Comment by alasarr** [comment]
Copying an interesting comment @andy-esch wrote at Slack channel:

I definitely think it's tricky! I actually tried to do that in a hackier way when I first created cartoframes. DataFrames have/had a metadata property that could be populated but it wasn't very robust. GeoPandas subclasses pandas.DataFrame too, so I'm a little wary of subclassing GeoDataFrames too (edited) 

The need for this comes out of DO stuff?

I agree that the current Dataset class is a bit confusing but feel like it's nice and light and easy to develop on. And with its methods we can return dataframes in certain operations (.download())

One big benefit of the flip side is that it'd be wonderful if we could contribute back to geopandas

If we were to subclass GeoDataFrame, I think we should study carefully other successful projects that sit on top of DataFrames, like Dask

We're also limiting ourselves if we rely really heavily on dataframes as they have a big memory imprint

I think the idea of a 'remote' dataframe is cool (current Dataset('tablename')) so would be curious about what it'd look like if we extended the DataFrame/GeoDataFrame class and how natural that would feel to work with

Contributing back, we could strategically add things like GeoDataFrame.from_carto :wink:
:+1::skin-tone-3:

**Comment by alasarr** [comment]
My main concern about this is not about DO integrations. It’s about making the library easy to adapt to new users. It’s a killer point since Data Scientist are our main target and they will decide if bought our platform or not.

I think new users will feel comfortable if we will give them a regular data frame (geopandas) with extra functions. It’s basically with GeoPandas does (extend the DataFrame class). Saying that we extend GeoDataFrames removes any doubt about compatibility.

The current version gives users a regular class that could return a DataFrame but it’s not the same. You need to explain users how our library is compatible with pandas/geopandas. For example, comments like this will be tricky: “Converts DataFrame into GeoDataFrame if possible”. Users will say: is it not always compatible with GeodataFrames?  

In code: currently do we have: 
```python
d = Dataset('brooklyn_poverty_census_tracts')

# read a table from your CARTO account to a DataFrame
df = d.download()

# perform operations on you dataframe
df['poverty_per_pop'] = df['poverty_count'] / df['total_population']

# update CARTO table with all changes from this session
d_updated = Dataset(df)
d_updated.upload(
    table_name='brooklyn_poverty_census_tracts',
    if_exists='replace'
)
```

I think users will prefer the following way.

```python
df = cartoframes.read_from_carto('brooklyn_poverty_census_tracts') 

# perform operations on you dataframe
df['poverty_per_pop'] = df['poverty_count'] / df['total_population']

df.upload(
    table_name='brooklyn_poverty_census_tracts',
    if_exists='replace'
)
```
It could look we are just removing a couple of lines but the idea under the hood is a more compatible library with the current data scientist stack.

I feel we’ve tried to create a Dataset class which does two things:
- Manage CARTO’s datasets 
- Work with dataframes.

I think that’s something quite complicated to solve in a single class and not easy to understand for users. For example, if you created a dataset like this:

```python
d = Dataset('select ... from a inner join b on a.join_id=b.join_id  ')
d.delete()
```
It’s difficult to explain users we’re deleting dataset a and b.

**Comment by alasarr** [comment]
One of the tricky things will be if you want to delete a dataset you will need to read the whole dataset. 

What about if we bring all the managing capabilities of the dataset to the current `DatasetManager` of Python-SDK?

**Comment by alasarr** [comment]
Adding @cmongut for awareness.

**Comment by alasarr** [comment]
Anyways, I think it's a big change we need to talk carefully. I like the debate, but please don't change code yet until we carefully discuss it.

**Comment by alasarr** [comment]
Already done and merged in develop

**Comment by awa5114** [comment]
Hi. I'm not familiar with `cartoframes` but I'm definitely curious as to how successful you were in subclassing the `GeoDataFrame` class? I also need to do this for my own projects but am running into serious roadblocks with some of the class methods that generate GeoDataFrames from files or features. Please see my post on [SE](https://stackoverflow.com/questions/63260633/subclassing-a-class-from-geopandas) and my post on the geopandas [issues](https://github.com/geopandas/geopandas/issues/1355) for some more details.
