### ISSUE TITLE
Changes on namespace

### ISSUE THREAD

**Issue by oleurud** [CartoDB/cartoframes#911]
The idea is to create a new namespace `lib` containing the current `context` one. At the end, the namespace structure will be:
- Lib
  - Context
    - Base context
    - Api context
    - (here will be the analysis framework context)

### Why?
We want to send a message to the users: "this namespace is internal or private, you don't need to think about it".

it could be others like `private` or `internals` for example, but we have selected `lib` for being more generic.

cc @alasarr @alrocar @andy-esch

**Comment by alasarr** [comment]
The final goal is to have a namespace with room for the upcoming functionality.  We thought the final namespace should look like this:


- Auth 
  - Credentials
  - Set_default_credentials
  - ....
- Lib
  - Context
    - Api context
    - (Analysis framework context)

- Data
  - CARTODataframe
  - Catalog
    - Dataset (should it support datasets groups?)
    - Country
    - Variable (supports variables group and variables)
    - Category
    - Geography
  - Enrich_points
  - Enrich_polygons

- Analysis
  - Geocoding
  - Isochrones
  - .. 

- Viz
  - Map 
  - Layers
  - Helpers

- Utils
  - CARTO SQL client
  - Columns
  - Table (a helper class to get current Tables in a CARTO account)
  - ...

- Contrib (it could appears in the future)

**Comment by alasarr** [comment]
Apart from the creation of the `lib` namespace and including `Context`classes there. We also need to do:

- Add `CARTO SQL client` to Utils.  `Client` namespace will disappear when we will remove `data_obs_client` (it will be replaced with do v2). If it's not too much work we could move data_obs_client to Utils and clean the base namespace.

**Comment by oleurud** [comment]
After a talk with @alasarr & @jgoizueta, we want to consider geocoding or isochrones part of data as services (or data services) and keep analysis namespace to big analysis as [feature engineering](https://en.wikipedia.org/wiki/Feature_engineering).

Also, we want to add more structure to data elements.

So, finally:

- **Auth**
  - **Credentials**
  - **set_default_credentials**

- Lib
  - Context
    - Api context
    - (Analysis framework context)

- **Data**
  - **Dataset**
    - **Dataset class**
    - Registry
  - **Do**
    - **enrich functions (enrich_points & enrich_polygon)**
    - **Catalog**
    - Dataset
    - Country
    - Variable (supports variables group and variables)
    - Category
    - Geography
  - **Services**
    - **Geocoding**
    - **Isochrones**
    

- Analysis
  - ...

- **Viz**
  - **Map** 
  - **Layers**
  - **Helpers**
  - ...

- **Utils**
  - **CARTO SQL client**
  - Columns
  - **Table** (a helper class to get current Tables in a CARTO account)
  - ...

- Contrib (it could appears in the future)

Namespaces and classes **in bold** are public

**Comment by oleurud** [comment]
I want to add 2 comments here:
- Where do we keep the DO v1 class? It is not very important, we are going to remove it soon
- I don't see the SQL client in utils

I know nobody is "confortable" with SQL client in utils, but now, with the new structure inside data, I think it makes sense to have it inside `data.client`. And we could keep the DO v1 there too. Therefore data namespace would be:

- **Data**
  - **Dataset**
    - **Dataset class**
    - Registry
  - **Do**
    - **enrich functions (enrich_points & enrich_polygon)**
    - **Catalog**
    - Dataset
    - Country
    - Variable (supports variables group and variables)
    - Category
    - Geography
  - **Services**
    - **Geocoding**
    - **Isochrones**
  - **Client**
    - **SQL client**
    - **DO v1** (it is not the best place for it, but we will delete it when DOv2 will be added)

For me, this works better than putting it in `utils`

**Comment by alrocar** [comment]
DO v1 and SQL client inside the `client` namespace look good to me.

**Comment by oleurud** [comment]
Done
