### ISSUE TITLE
CARTOframes Dataset conflict with a Dataset constructor in the netCDF4 library  

### ISSUE THREAD

**Issue by giuliacarella** [CartoDB/cartoframes#916]
In the netCDF4 python  library there is a constructor called Dataset and if this is not imported with a different name, this will produce an error when using the Dataset call in CARTOframes. Should we change the name to something like cfDataset? A part from this library, which is not super commonly used, I am afraid that there could are other constructors with the same name in other libraries.

**Comment by andy-esch** [comment]
One way to avoid this problem is to use the module/namespace that something is contained within. In cartoframes, you can do this instead:
```python
from cartoframes import data

ds = data.Dataset('tablename')
```
_or_
```python
from cartoframes.data import Dataset as CFDataset

ds = CFDataset('tablename')
```

This gives you the flexibility to avoid name conflicts.

**Comment by giuliacarella** [comment]
Hi @andy-esch,

thanks, this is what I've done :)  However, just wondering it was worth naming it in a different way so that users don't have to do this to avoid any conflict.
