### ISSUE TITLE
Data Obs Augment not returning actionable Dataset

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#917]
The current state of `DataObsClient().augment()` is supposed to return a Dataset. That happens but the Dataset appears to be empty.

Even in the case that the augmentation is 'persist_as` to a tablename, in which case a Query Dataset should be returned, that Dataset does not seem to work in Layer. It appears that some wires are crossed somehow and Layer thinks its dealing with a DataframeDataset. In reality, with the new flow we decided, DataObsClient().augment should return:
- Dataset(table) if `persist_as` is set to a tablename
- DataFrame if `persist_as` is not set OR DataFrameDataset?

https://github.com/CartoDB/cartoframes/blob/ff4011f94bef5485f46b9f8159d3195c4df3c786/cartoframes/client/data_obs_client.py#L641-L646

`Dataset(query).download()` returns a dataset, but this method does not _set_ the dataset or DataFrame in the class (as far as I can tell).

cc @alexsroth

**Comment by cmongut** [comment]
It seems it's already solved :)
