### ISSUE TITLE
Dataset(df).upload() doesn't work if the only columns are the_geom and cartodb_id

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#922]
It seems to want more columns when it builds a query:
```
CartoException: Batch SQL job failed with result: {'user': 'eschbacher', 'status': 'failed',
'query': "BEGIN; DROP TABLE IF EXISTS test_upload; CREATE TABLE test_upload (, the_geom geometry(MultiPolygon, 4326)); SELECT CDB_CartodbfyTable('eschbacher', 'test_upload'); COMMIT;",
'created_at': '2019-08-20T18:26:51.936Z',
'updated_at': '2019-08-20T18:26:51.954Z',
'failed_reason': 'syntax error at or near ","',
'job_id': '5b6a1396-5b6d-4581-808f-27c3c8947464'}
```
Specifically, you can see the query it constructs here:
```sql
CREATE TABLE test_upload (, the_geom geometry(MultiPolygon, 4326))
```

**Comment by oleurud** [comment]
Related with #947

**Comment by oleurud** [comment]
More ideas (specific case of `cartodb_id`)
- rename columns
- check if `cartodb_id` is valid for us (positive integers, non-repeating, non-null, etc.) and using it as index (if not, rename the column)
- (it could be the implementation of the previous one) try to make it the cartodb_id in the db, and if that fails rename it and upload again
- convert into the index (remove current index) and upload it

**Comment by alrocar** [comment]
I wouldn't add specific logic like renaming columns, check nulls, existence, etc.

I'd upload what we have and when cartodbfying if there's an error (because `cartodb_id` is not unique for example), the backend will raise an error and the user should have to modify their dataframe to make it work (in most cases by just dropping or resetting the `cartodb_id` column). We can just solve this with good documentation.

I'd prefer we are able to explain a simple process so that users can understand it, than adding too much magic and find lots of corner cases (in any case we can add magic in the future, once we understand how users upload data).

> convert it into the index (remove current index) and upload it

About this, IIRC we upload the index as a regular column so when download back the dataset, the index is `cartodb_id` and you keep your previous index as a column. 

My 2 cents.

**Comment by oleurud** [comment]
And what do you do if a DataFrame has a column called `the_geom_webmercator`?

**Comment by alrocar** [comment]
I'd vote for excluding that column always.

**Comment by oleurud** [comment]
Ok :+1: I will do that way

**Comment by oleurud** [comment]
We have some tests that are failing after the changes:
- a dataframe with `the_geom` column where with every value is null, has 2 columns with latitude/longitude. The test does the upload using `with_lnglat` and expects to have no null `the_geom` values. In my opinion, we should upload `the_geom` as it is (we are prioritizing a geometry column over the `with_lnglat` parameters), so the upload creates a table with a `the_geom` with all its values as null

cc @andy-esch @alrocar

**Comment by alrocar** [comment]
mm not sure about that, I think if the user is explicit with `with_lnglat` we should prioritize it over `the_geom`, but I don't have a strong opinion about that.

We can do what you suggest, in that case, I'd like to have a note in the API docs exaplaining that.

**Comment by oleurud** [comment]
`CDB_CartodbfyTable` only allows one `geometry(xxx, 4326)` (drops and/or renames to the expected one: `the_geom`) https://github.com/CartoDB/cartodb-postgresql/blob/bf140890d8480ca78bb7aef2a7ea458f3490774a/scripts-available/CDB_CartodbfyTable.sql#L862-L867

So, joining that with the prioritization of `with_lnglat`, in the case of having a geometry in the dataframe and using `with_lnglat`:
- we are going to create `the_geom` from `with_lnglat` columns
- we are NOT going to update the previous geometry

**Comment by oleurud** [comment]
A collateral case would be having several geometries in any case (with or without `with_lnglat`). We are choosing `the_geom` and uploading the rest as text. This is the previous behavior. I don't want to spend more time on this now and I created an issue for that https://github.com/CartoDB/cartoframes/issues/1005

**Comment by andy-esch** [comment]
🥇Thanks @oleurud!
