### ISSUE TITLE
enable dynamic legends!

### ISSUE THREAD

**Issue by makella** [CartoDB/cartoframes#924]
while working on the cluster helpers, which use viewport aggregations, we've seen how the legend isn't updating its values to reflect the current view of the map even though as you zoom in and out, the clusters reaggregate themselves to the current viewport.

welll, great news!

i pinged @rjimenezda and he saw that if we set `dynamic: true` when creating the legend, that we can get the dynamic behavior! woot!! he's also offered to take a look at it for us to see if we can get this available in develop.

in the case of the clusters, since the largest, middle, and smallest symbol sizes are fixed, we don't see the sizes of symbols changing since the largest symbol size that we've set will always be the largest symbol size on the map and same with the values of 1 (they will always have the smallest symbol size).

![dynamic](https://user-images.githubusercontent.com/1566273/63373356-01b04600-c345-11e9-899b-227ff9f99d3b.gif)

there are a few options:
- for now, we can enable this behavior only on the cluster helper since it is the only helper that uses the viewport. 
- or we can enable globally knowing that it will only be triggered if there is a style (like viewport) that would trigger a change in the legend
- as @rjimenezda mentioned to me, we can think more about how to add this to the legend API as an option for non-helper based maps, but I think that can come later. 

I am inclined to vote for the enable global option and add it to the API vs. just for clusters. obviously, we'd want to do some testing over different scenarios but having dynamic legends in develop right now would be a great way to be able to do that. Either way, I'm super happy that this little add does the trick!!

**Comment by elenatorro** [comment]
Merged 🚀
