### ISSUE TITLE
Add default styles for `Layer`

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#927]
As far as I know we have not added default styles for simple layers. 

I could see this being helpful if we have several overlapping polygons, like below, where there could be some opacity a different stroke color, and maybe other enhancements(?):
<img width="946" alt="Screen Shot 2019-08-21 at 9 14 33 AM" src="https://user-images.githubusercontent.com/1041056/63435031-26afc200-c3f4-11e9-88f2-b24202fd4738.png">

**Comment by Jesus89** [comment]
I think this is the default style for polygons. cc @makella

**Comment by makella** [comment]
@Jesus89 @andy-esch yep, this is the default styling for polygons.

exactly what you are pointing out Andy is what I wrote [here](https://github.com/CartoDB/cartoframes/issues/966#event-2624649831) (of course the default_layer helper I describe below would also have the same style properties available in others like color, size, opacity, etc. in addition to the ability to add a widget on an attribute):

> On the other hand, current helpers are most useful if you want to create a data-driven visualization. The other way of seeing it is that we are missing just a default_layer helper where you aren't styling on an attribute but instead have a dataset that you want to explore and be able to add a widget , a legend, popups, etc. We have all the pieces to put that kind of default layer helper together and i'm wondering if we should think about adding something like that? I see where the complications will arise in enabling the option to choose the value for each (for example, during the exploratory phase you may want to add a category widget on one field and a histogram widget on another similarly the legend, etc.) For me, going straight to the legends, widgets, and popups at the layer level and then styling the final map with VL syntax, in the Quickstart, wouldn't demonstrate how "easy" we've made things! And this is a place where I'm guessing a lot of people will start.

**Comment by makella** [comment]
closing as we've added! woot!
