### ISSUE TITLE
Histogram legends are not filtering map

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#929]
When I create a map with a default histogram from a helper function, the histogram does not filter the map.

I get this error in the JS console:

```js
Error: [Property with an incorrect type] in(): invalid first parameter 'input'
        expected type was 'category', actual type was 'number'
```

From making this map:

```python
color_continuous_layer('capital_bikeshare_july_2019_pickup_dropoff_isochrone_augmented', 'pop_25_64_2011_2015_by_total_pop', widget=True)
```

I'm running this off of develop (3dc4e10d175069a7d7b734db3d9526127aad9dec).

**Comment by elenatorro** [comment]
Is this still happening? I've just tested and it seems to work ok. Could you give me the link to the dataset?

![Screenshot 2019-08-27 at 16 47 20](https://user-images.githubusercontent.com/3824953/63781719-7b6aa580-c8ea-11e9-8cad-0580d59974f6.png)

**Comment by elenatorro** [comment]
ok, I see the error now, I'm gonna fix it ASAP. Good catch!!
