### ISSUE TITLE
Feature request: layer selector check boxes in legends

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#930]
The ability to turn on or off a layer could help looking for patterns in more than one dataset so that a layer can be toggled on/off.

**Comment by makella** [comment]
+1 noticing that with our DS team that the only reason they go to Builder is to make a map with selectable layers

**Comment by cmongut** [comment]
Hi both :)

This was already added to CARTOframes, you can check it [here](https://carto.com/developers/cartoframes/examples/#example-multiple-layers)

Thank you 🤗
