### ISSUE TITLE
If a table does not exist, Dataset should throw an error

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#934]
Right now, Dataset will error with being unable to detect dataset type. Instead, I would expect it to identify that it's a table and that the table does not exist in my account.

**Comment by Jesus89** [comment]
Hi. With the latest updates this will return the following error `Dataset('not_existing_table').download()`: `400 Client Error: relation "arroyo-carto.not_existing_table" does not exist`. Is that OK for you?

**Comment by andy-esch** [comment]
Yep, great for me!

**Comment by Jesus89** [comment]
Cool. Closing then :)
