### ISSUE TITLE
RateLimitError when if_exists='replace' and table already exists

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#936]
I keep hitting this consistently. I'll fill in more details soon!

**Comment by oleurud** [comment]
More news about that?

**Comment by Jesus89** [comment]
Hi @andy-esch, is this still happening?

What is the scenario for this to happen? Thanks!

**Comment by andy-esch** [comment]
I'm trying to reproduce but now I'm not able to upload anything at all. I don't get the error above but keep getting the error reported in https://github.com/CartoDB/cartoframes/issues/908. I'm using a fresh (as of 7 Nov) version of the `develop` branch.

**Code**
```python
from cartoframes.auth import set_default_credentials, Credentials
from cartoframes.data import Dataset
import pandas as pd
import numpy as np

set_default_credentials(Credentials.from_file())


N = 100000

df = pd.DataFrame({
    'lat': np.random.random(N),
    'lng': np.random.random(N),
    'label': np.random.choice(list('abcdefghijklmnopqrstuvwxyz'), size=N)
})

Dataset(df).upload(table_name='issue_test', if_exists='replace')
```

**What happens**
1. `Dataset(df).upload(table_name='issue_test')` gives `BadRequestException: ['Connection closed by server: input data too slow']`
2. `Dataset(df).upload(table_name='issue_test')`: `CartoException: Table with name issue_test and schema eschbacher already exists in CARTO.Please choose a different `table_name` or use if_exists="replace" to overwrite it`
3. `Dataset(df).upload(table_name='issue_test', if_exists='replace')` gives `BadRequestException: ['Connection closed by server: input data too slow']`
4. Try again, and again, and again all with `BadRequestException: ['Connection closed by server: input data too slow']`
5. Reset connection and ran internet speed test 

  <img width="400" alt="Screen Shot 2019-11-07 at 11 09 19 AM" src="https://user-images.githubusercontent.com/1041056/68406741-50a19680-0150-11ea-8560-d995aeb3067e.png">

6. Manually delete table in dashboard and try again. `BadRequestException: ['Connection closed by server: input data too slow']`

**Comment by Jesus89** [comment]
True that. I have executed the same test and I get also the same error.

I'll tag this issue with the COPY tag

**Comment by alrocar** [comment]
A fix in the COPY API has been deployed, see related [issue](https://github.com/CartoDB/support/issues/2239#issuecomment-556218123).

@andy-esch could you help us to test a `Dataset.upload` with a more than 1GB csv?

Thanks!

**Comment by andy-esch** [comment]
Sure, I'll tackle that tomorrow. For now, I just tried the code snippet above that previously errored and it worked. It was pretty slow for only being a 4.6MB payload though.

**Comment by andy-esch** [comment]
I just uploaded a 967MB file with no issues. And after several trials with smaller files, I've not been able to replicate the original issue here. cc @Jesus89

**Comment by Jesus89** [comment]
Cool. We can close it :tada:
