### ISSUE TITLE
Docs: ReadTheDocs vs Developer Center

### ISSUE THREAD

**Issue by alrocar** [CartoDB/cartoframes#937]
Proposal:

- Ideally, developer center for written documentation: guides, workflows, etc.
- ReadTheDocs: Only for API docs (docstrings) (They are also shown in the Notebook, where they are more useful)

IMO ReadTheDocs was useful when we (and other projects) didn't have an infrastructure for documentation. We used it when there was no Developer Center and we didn't have a clear workflow to write tech docs. Currently we do have a developer center which is aimed to be the place where to have all our tech docs.

@giuliacarella @andy-esch @djfan @malgar @josemazo @alejandrohall @arredond 

Thoughts? Do you find more useful having docs in read the docs rather in developer center for any reason?

**Comment by VictorVelarde** [comment]
We have a plan for moving from 'ReadTheDocs' to 'Dev Center'.

We need to properly split this one into several issues. We'll make a proposal soon.

cc/ @elenatorro @csubira @alejandraarri

**Comment by elenatorro** [comment]
I've opened the issue in the developer center (https://github.com/CartoDB/developers/issues/631) and linked it in the EPIC issue: https://github.com/CartoDB/cartoframes/issues/967

Do you think we should close this one in favor of these issues?
