### ISSUE TITLE
Widget not showing in tab when responsive display is narrow

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#940]
<img width="699" alt="Screen Shot 2019-08-27 at 4 01 50 PM" src="https://user-images.githubusercontent.com/1041056/63803943-08f6c700-c8e4-11e9-91f7-a67c9dbb60fd.png">

```python
from cartoframes.auth import set_default_credentials
from cartoframes.viz import Map
from cartoframes.viz.helpers import size_continuous_layer

set_default_credentials('cartoframes', 'default_public')

Map([
    size_continuous_layer('bikeshare_july_agg', 'total_events', widget=True)
])
```

I'm not seeing any errors in the console.

**Comment by elenatorro** [comment]
Yeah! You're right. I've fixed that in this issue https://github.com/CartoDB/cartoframes/pull/941, by drawing the widget once the layer has been loaded 👍
