### ISSUE TITLE
Histogram filtering bug

### ISSUE THREAD

**Issue by cmongut** [CartoDB/cartoframes#951]
**Current result:**
![image](https://user-images.githubusercontent.com/711025/64125833-c170af00-cdab-11e9-9560-638fce7b89ed.png)

**Snippet used:**
```
Map(size_continuous_layer('arlington_bikeshare_july_agg.geojson',
                          'total_events',
                          'Pickups + Drop Offs',
                          widget=True))
```
**File used:**
[arlington_bikeshare_july_agg.geojson.zip](https://github.com/CartoDB/cartoframes/files/3566639/arlington_bikeshare_july_agg.geojson.zip)

**Expected result:**
Filtering works and no error is shown in the console

**Comment by elenatorro** [comment]
Hi, @cmongut 👋 I've tested it in `develop` and it seems to work fine, can't reproduce the error:

![widget_test](https://user-images.githubusercontent.com/3824953/64333152-42ab8a00-cfd6-11e9-9e7b-0cefe7f20219.gif)

**Comment by cmongut** [comment]
Me neither! Thank you for taking a look!
