### ISSUE TITLE
pandas slice recommendation

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#958]
This is probably a good idea for a small refactor:
```
/home/jupyter/src/cartoframes/cartoframes/data/utils.py:67: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['geometry'] = _compute_geometry_from_geom(geom_column)
```

I get this warning when I create a map from a DataFrame that's not been used before but now I'm having trouble reproducing but I've seen this error regardless of dataset. It seems to happen when I filter a dataframe like so:

```python
Map(Layer(df[df.temperature > 10]))
```

It seems to be dealing with this line: https://github.com/CartoDB/cartoframes/blob/39cd7c9205cd1b597176f942cec3d66b946c3497/cartoframes/data/utils.py#L67

**Comment by Jesus89** [comment]
I have tested the following, but then I get the error `TypeError: float() argument must be a string or a number, not 'Point'`.

```py
dataframe.loc[:, 'geometry'] = _compute_geometry_from_geom(geom_column)
```

**Comment by Jesus89** [comment]
Since this is not exactly a but, but a SettingWithCopyWarning I would remove the tag.

**Comment by andy-esch** [comment]
Another way to set the `geometry` column is passing the dataframe into the `GeoDataFrame` constructor and using the kwarg geometry:
```python
gpd.GeoDataFrame(df, geometry=_compute_geometry_from_geom(geom_column))
```

That might work and give more reliable results? I just worry about warnings because the dataframe may not be constructed correctly and have some unintended effects. 🤷‍♂

**Comment by Jesus89** [comment]
This is obsolete. The current implementation improves the geometry column management
