### ISSUE TITLE
Wrong installation instructions for CARTOframes v1.0b1 

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/cartoframes#959]
The install instructions of both [Dev Center](https://carto.com/developers/cartoframes/v1.0b1/guides/Quickstart/#install-cartoframes) and [readthedocs](https://cartoframes.readthedocs.io/en/v1.0b1/overview.html#install-instructions) define the next steps:

<img width="865" alt="Screenshot 2019-09-06 at 11 31 43" src="https://user-images.githubusercontent.com/11177693/64417736-ee69de00-d099-11e9-8d85-27f278ba7bc0.png">

<img width="717" alt="Screenshot 2019-09-06 at 11 29 43" src="https://user-images.githubusercontent.com/11177693/64417655-d09c7900-d099-11e9-9c47-50cdfe4a4f70.png">

However, both instructions install CARTOframes version 0.10.

In order to install CARTOframes v1.b01 you would need to apply the next command:

```bash
pip install cartoframes==1.0b1
```

**Comment by elenatorro** [comment]
I don't know how can we change it at this point, cause the documentation is generated from the version tag. Any ideas?

**Comment by Jesus89** [comment]
This will be solved in the next beta release soon, so there's no need to change b1, let's wait for the fix :smile:
