### ISSUE TITLE
Data Discovery - properties

### ISSUE THREAD

**Issue by alrocar** [CartoDB/cartoframes#961]
For example: Dataset.provider would return the provider of that dataset and Dataset.variables would return the variables of that dataset. However, since now we're using pandas directly, this notation overrides the pandas notation to access a column in which dataset.provider already returns the column provider. OTH, the expected behavior of Dataset.variables in our API is a little different since it wouldn't return the column variables but a DataFrame with all the variables (and their info) for that given dataset (info which is not available locally and it needs to be retrieved from the server).

Our conclusion for this issue is to use methods instead of properties for the extra navigation functionality and leave pandas notation as it is to access columns.

**Comment by alrocar** [comment]
Adding a reference to a previous comments in case they can be tackled as part of this issue:

- https://github.com/CartoDB/cartoframes/pull/949#discussion_r322844870

**Comment by oleurud** [comment]
I would raise an error when the user tries to get an entity using an unexisting id (`by_id` method) I would return `None` in the rest
