### ISSUE TITLE
Add count method to Dataset

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/cartoframes#965]
I propose adding a `count` method to `Dataset` to obtain the number of rows (which would be implemented in each strategy class).

It would serve to avoid this horror I wrote when I needed to find the size of a dataset: https://github.com/CartoDB/cartoframes/blob/ba7b08a59c34db8b5b3c8677f9424de5dd4de223/cartoframes/data/services/isolines.py#L11-L20

**Comment by Jesus89** [comment]
The `Dataset` class does not exist anymore. You can use `SQLClient.count` to get that information.
