### ISSUE TITLE
if_exists replace error after retry by query

### ISSUE THREAD

**Issue by oleurud** [CartoDB/cartoframes#968]
1. Create dataset from a query
2. upload it to a new table
3. check the number of rows
4. Via SQL API, make a truncate over the table
5. do the upload again with `if_exists=replace` 

After that, the table still remains empty and it should be in the same state of step 3

**Comment by Jesus89** [comment]
How can we reproduce this issue?

**Comment by oleurud** [comment]
I think it is related to Dataset class, so I would close this issue
