### ISSUE TITLE
Setting stroke_width=0 is ignored in helper methods

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#971]
This seems to happen because of the logic that's in the helper methods. 0 is a truthy False in Python, so the `or` is treating it as False and going for the default value instead. We should probably test for None instead. This seems to be the case for points, lines, polygons.

https://github.com/CartoDB/cartoframes/blob/bacce3d395007f8b8023a87e996e0b1fb84fb284/cartoframes/viz/helpers/color_continuous_layer.py#L58

**Comment by makella** [comment]
ah ha! ok i see what you are saying!

**Comment by makella** [comment]
ohhh it gets a little complicated because of the different geometry types... thinking/testing/trying.

**Comment by makella** [comment]
solved with: https://github.com/CartoDB/cartoframes/pull/1145

**Comment by andy-esch** [comment]
💥!
