### ISSUE TITLE
Map with no layer throws js error

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#975]
We created `Map` so that it requires zero or more Layers, however the case where there are zero layers is now throwing an error in the JavaScript console and no map is displaying: 
```
ReferenceError: None is not definedsrcdoc:1077:20
```

I'm using the latest develop branch and this code running in a Jupyter notebook:

```python
from cartoframes.auth import set_default_credentials
from cartoframes.viz import Map
username = 'eschbacher'
set_default_credentials(f'https://{username}.carto.com/')

Map()
```

**Comment by makella** [comment]
I'm having the same issue. For the Visualization guides, thought it would be a nice way to introduce Map() and then add a Layer inside. cc @cmongut
