### ISSUE TITLE
Discovery API - data sample

### ISSUE THREAD

**Issue by alrocar** [CartoDB/cartoframes#978]
Ideally we should be able to let a user exploring the catalog, view a sample of the data (similar as a `head`, like 10 lines or so).

Besides that we could add a helper method to get an empty dataframe from a Dataset, so a user can understand easily the schema and columns available.

**Comment by alrocar** [comment]
https://docs.google.com/document/d/1d1jklM0cWVjV5Sbu64Yv3ky-fJIMu2tRJC02qL1FbmE/edit#

Let's try if it's feasible to override the `tail` and `head` methods.

Let's think on a catalog dataframe as a `remote entity` which head and tail take the data from the information stored in the catalog (in the describe column) and not from the local dataframe itself.

**Comment by cmongut** [comment]
@alrocar could we close this issue? We already have `head` and `tail` methods for datasets.
