### ISSUE TITLE
[Doc - Guides] Links from guides to Reference

### ISSUE THREAD

**Issue by VictorVelarde** [CartoDB/cartoframes#980]
- [x] Check that we can create a proper link from guides to the (new) CF reference in dev. center
- [ ] Enrich guides, with references to the main classes & functions

**Comment by elenatorro** [comment]
I think this task is implicit in the different Guides tasks. Since it's possible now to add links to the Reference section, we can close it for now. I'm creating a `boilerplate guide` with examples about how to include the links.
