### ISSUE TITLE
[Doc - Guides] Content structure design

### ISSUE THREAD

**Issue by VictorVelarde** [CartoDB/cartoframes#981]
[EPIC] https://github.com/CartoDB/cartoframes/issues/967

**Context**

Design the final structure of the contents --> agree ASAP on a 'content-tree' with the desired guides and its general structure

**Proposed structure** _[WIP]_

- [ ] Introduction
- [ ] Quickstart
- [ ] Install CARTOframes in your Notebooks
- [ ] Login to CARTO Platform
- [ ] Visualize your Data
- [ ] Manage your Data
- [ ] Use Location Data Services
- [ ] Discover data
- [ ] Enrich your datasets
- [ ] Publish and share

**Note**
All the guides should be in .md format for its integration in the Dev-Center

**Comment by cmongut** [comment]
We are working on it here: https://docs.google.com/document/d/16UTXbj2M-s1ZX-g_t99N1ad4J-byfAj1eP6HMYnRuA4/edit

The idea is to have the quick start guide first an then create specific ones with links to the reference and the examples.

**Comment by elenatorro** [comment]
The proposed structure is added in the EPIC issue #967. Each section has its own issue, where we'll discuss the content and open a PR accordingly. The feature branch is [`docs/guides`](https://github.com/CartoDB/cartoframes/tree/docs/guides). Once we finish all the guides, we'll merge this branch in `develop`.
