### ISSUE TITLE
JS error on Base64 if visualizing dataframe in a colaboratory notebook

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#982]
In cell 8, I've had trouble visualizing dataframes off of the latest develop. See my [notebook here](https://colab.research.google.com/drive/1_bwKV6bEz-HhcUsjr-felb0PttmZzebt) -- code also below.

<img width="805" alt="Screen Shot 2019-09-12 at 3 21 45 PM" src="https://user-images.githubusercontent.com/1041056/64814229-144b2300-d571-11e9-9507-687d4fb7e64b.png">

Code to reproduce:

```python
from cartoframes.data import Dataset
from cartoframes.auth import set_default_credentials

set_default_credentials('eschbacher')
bikeshare_table = 'capital_bikeshare_july_2019_pickup_dropoff'
df = Dataset(bikeshare_table).download()
Layer(df)
```

**Comment by andy-esch** [comment]
Same happens in nbviewer: https://nbviewer.jupyter.org/gist/andy-esch/4395503fa5fc103332097a53952a0819#Create-a-map-off-of-local-data

**Comment by andy-esch** [comment]
I get this in google cloud too. Looking at the console, I see this:
<img width="1220" alt="Screen Shot 2019-09-19 at 3 32 23 PM" src="https://user-images.githubusercontent.com/1041056/65275062-ceeba000-daf2-11e9-831d-a2a38bc3bd27.png">

**Comment by andy-esch** [comment]
Looks like all we need to do is add an `s` to http here:
https://github.com/CartoDB/cartoframes/blob/063e5e9f6bbadbe469b729dbe82eca0b42fa05d7/cartoframes/assets/templates/viz/main.html.j2#L27

@elenatorro what do you think? I'm guessing that the cdn default supports https

**Comment by elenatorro** [comment]
Hi 👋 Sure!! Good catch, I didn't realize this could fail. Let's change it then :)

**Comment by alrocar** [comment]
Thanks @elenatorro 

Let's keep issues in the `In progress` column and add PRs to the `Review` column, being them unassigned so anyone can take them for revision.
