### ISSUE TITLE
[Doc - Examples] - Review current examples

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartoframes#985]
[EPIC] - https://github.com/CartoDB/cartoframes/issues/967

Proposed structure
-------------------

**Downloading and Uploading data**
Use data in GeoJSON format
Use a Dataframe
Use a dataset from CARTO
Save your data in CARTO
Geocode a dataset
Isochrones (?)

**Visualization Settings**
Use a color background
Change the default basemap
Set a custom viewport
Use the dark mode
Layout to compare visualizations
Add Popup interactivity

**Helper methods**
Visualize categorical data by color
Visualize numeric data by color
Visualize numeric data range by color
Visualize numeric data by size
Visualize categorical data by size
Visualize numeric data range by size
Visualize aggregated data in clusters
Visualize data changes through animation

**Layers**
Add a basic layer 
Add multiple layers
Add a legend to a layer
Add multiple legends to one layer
Add a widget
Add multiple widgets to a layer
Add an animation layer

**Data Enrichment**
**Data Discovery**
**Publishing and sharing**
**Real use cases**
**Cleaning Data** (TBD)

**Comment by makella** [comment]
hi @elenatorro given that we are actively adding content, just want to make sure that the best place to go through and test that each example works is in develop. thanks! i have a spreadsheet started will link here for review once i'm done going through each one.

**Comment by makella** [comment]
@elenatorro as discussed, I created a branch [docs/examples](https://github.com/CartoDB/cartoframes/tree/docs/examples) to start reviewing content. All existing examples are in the `old_examples` folder and I'll transfer the ones we want to keep into the other (currently empty) `examples` folder.

**Comment by elenatorro** [comment]
Closing this since it's merged in develop 🚀
