### ISSUE TITLE
[Doc - Examples] - Clean "debug" examples 

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartoframes#986]
[EPIC] - https://github.com/CartoDB/cartoframes/issues/967

Context
======

As part of the documentation tasks, we need to:

Go through the examples in the `old-examples/_debug` directory. The best option at this point is to remove them all for this beta, but it'd be great if we could take a look to all of them in case we could extract some example from there to the examples section.

**Comment by Jesus89** [comment]
Done https://github.com/CartoDB/cartoframes/pull/1115
