### ISSUE TITLE
[Doc - Examples] - Embed notebooks in dev center

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartoframes#988]
[EPIC] - https://github.com/CartoDB/cartoframes/issues/967

Demo: http://test-cartoframes-examples.developers.carto-staging.com/developers/cartoframes/examples/

There're two possible options for this task:
- [x] Check if we could have the notebook examples embedded in the devcenter (there's one example already added)
- [x] Create a task to generate and visualize the examples in the developer center
- ~~[ ] Use binder to link notebooks from the GitHub repository~~ -> Move to a different issue https://github.com/CartoDB/cartoframes/issues/1035

![screencapture-test-cartoframes-examples-developers-carto-staging-developers-cartoframes-examples-2019-09-26-16_52_08](https://user-images.githubusercontent.com/3824953/65699218-0cfe3c00-e07e-11e9-9363-f332797460e4.png)

**Comment by cmongut** [comment]
👋 
I think both options are compatible. We can check how to embed examples there and add a link to binder at the top, isn't it?
