### ISSUE TITLE
[Doc - Guides] - Introduction

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartoframes#990]
[EPIC] - https://github.com/CartoDB/cartoframes/issues/967

Context
======

We're going to change the current introduction section. Instead of a list of links, we'll include call to action buttons to each guide, and each one will contain:

- Title
- Description (including **key** terms)
- Icon that represents visually the content of the guide

For the next beta version, we will only publish 4 guides:

- Installation
- Login into CARTO
- Quickstart Part 1
- Quickstart Part 2

---

Current intro section:

![Screenshot 2019-09-16 at 16 30 50](https://user-images.githubusercontent.com/3824953/64966618-6658b500-d89f-11e9-8c29-fd996ed5ca55.png)

**Comment by newLadyAga** [comment]
Hi @elenatorro,  

Here is the [Sketch file](https://www.dropbox.com/s/zvhhtgm0x5bzehs/990%20%5BDoc%20-%20Guides%5D%20Introduction%20-%20CARTOframes.sketch?dl=0) with the design for the introduction section.

This is the new module for the guides...
![image](https://user-images.githubusercontent.com/49977486/67195629-909b1680-f3f9-11e9-9b06-f04bb33f4bcc.png)

And the module in context...
![image](https://user-images.githubusercontent.com/49977486/67195636-942e9d80-f3f9-11e9-98aa-4f362b028296.png)

Thank you!

**Comment by elenatorro** [comment]
Awesome, thank you so much @newLadyAga, I'll send you the link to staging once I finish it so you can review it 👍

**Comment by elenatorro** [comment]
This is how it looks so far:

![Screenshot 2019-10-21 at 14 56 17](https://user-images.githubusercontent.com/3824953/67207438-e1b80400-f413-11e9-9015-9f3c0e1bdeac.png)
