### ISSUE TITLE
[Doc - Guides] - Visualize your Data

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartoframes#992]
[EPIC] https://github.com/CartoDB/cartoframes/issues/967

**Comment by makella** [comment]
This is the outline that we've agreed to go with for the Visualization Guide:
https://docs.google.com/document/d/16UTXbj2M-s1ZX-g_t99N1ad4J-byfAj1eP6HMYnRuA4/edit#heading=h.u7hrvxxkqpez

**Comment by elenatorro** [comment]
Merged 🚀
